-- Lot 3b de l'import du contenu de référence : dons restants.
--
-- * Amélioration de caractéristique (don général du SRD 5.2, CC-BY-4.0, « System Reference
--   Document 5.2 » de Wizards of the Coast LLC, https://creativecommons.org/licenses/by/4.0/),
--   traduit.
-- * Dons du Manuel des Joueurs (2024) absents du SRD (Artisan, Musicien, Entraînement aux armes
--   de guerre, Véloce), dons de Fizban's Treasury of Dragons, Bigby Presents: Glory of the Giants,
--   Planescape: Adventures in the Multiverse et Dragonlance: Shadow of the Dragon Queen :
--   texte reformulé.
--
-- Idempotente : chaque entrée n'est insérée que si son nom FR n'existe pas déjà.

do $$
declare
  rec record;
  v_id int;
  v_inserted int := 0;
begin
  for rec in
    select * from (values
  -- SRD 5.2
  ($t$Amélioration de caractéristique$t$, $t$Ability Score Improvement$t$, $t${"text":"Niveau 4 (Don général)","level":4}$t$::jsonb,
   $t$Don général. Augmentez une valeur de caractéristique de votre choix de 2, ou deux valeurs de caractéristique de votre choix de 1 chacune. Ce don ne peut pas faire dépasser 20 à une valeur. Répétable : vous pouvez choisir ce don plusieurs fois.$t$),
  -- Manuel des Joueurs 2024 (hors SRD)
  ($t$Artisan$t$, $t$Crafter$t$, $t${"text":"Don d'origine"}$t$::jsonb,
   $t$Don d'origine. Vous obtenez la maîtrise de trois outils d'artisan de votre choix. Lorsque vous achetez un objet non magique, vous bénéficiez d'une remise de 20 %. Quand vous terminez un repos long, vous pouvez fabriquer un objet d'équipement ordinaire associé à l'un des outils d'artisan que vous maîtrisez (et que vous avez en main) ; l'objet dure jusqu'à la fin de votre prochain repos long, puis se défait.$t$),
  ($t$Musicien$t$, $t$Musician$t$, $t${"text":"Don d'origine"}$t$::jsonb,
   $t$Don d'origine. Vous obtenez la maîtrise de trois instruments de musique de votre choix. Quand vous terminez un repos court ou long, vous pouvez jouer un air sur un instrument que vous maîtrisez : un nombre d'alliés égal à votre bonus de maîtrise qui l'entendent (vous pouvez vous inclure) obtiennent l'Inspiration héroïque.$t$),
  ($t$Entraînement aux armes de guerre$t$, $t$Martial Weapon Training$t$, $t${"text":"Niveau 4 (Don général)","level":4}$t$::jsonb,
   $t$Don général. Force ou Dextérité +1 (max. 20). Vous obtenez la maîtrise des armes de guerre, ainsi que la formation au port des armures légères, des armures intermédiaires et des boucliers.$t$),
  ($t$Véloce$t$, $t$Speedy$t$, $t${"text":"Niveau 4, Dextérité ou Constitution 13 ou plus (Don général)","level":4}$t$::jsonb,
   $t$Don général. Dextérité ou Constitution +1 (max. 20). Votre vitesse augmente de 3 m. Lorsque vous effectuez l'action Foncer, le terrain difficile ne vous coûte pas de déplacement supplémentaire pour le reste du tour. Les attaques d'opportunité dirigées contre vous ont le désavantage.$t$),
  -- Fizban's Treasury of Dragons
  ($t$Don du dragon chromatique$t$, $t$Gift of the Chromatic Dragon$t$, $t${}$t$::jsonb,
   $t$Infusion chromatique : par une action bonus, vous touchez une arme courante ou de guerre et lui conférez l'un des types de dégâts suivants : acide, feu, foudre, froid ou poison. Pendant 1 minute, l'arme inflige 1d4 dégâts supplémentaires de ce type quand elle touche ; vous récupérez cette capacité après un repos long. Résistance réactive : lorsque vous subissez des dégâts d'acide, de feu, de foudre, de froid ou de poison, vous pouvez utiliser votre réaction pour obtenir la résistance contre ces dégâts. Utilisable un nombre de fois égal à votre bonus de maîtrise, toutes les utilisations étant récupérées après un repos long.$t$),
  ($t$Don du dragon de gemme$t$, $t$Gift of the Gem Dragon$t$, $t${}$t$::jsonb,
   $t$Intelligence, Sagesse ou Charisme +1 (max. 20). Représailles télékinétiques : lorsqu'une créature à 3 m ou moins vous inflige des dégâts, vous pouvez utiliser votre réaction pour libérer une onde télékinétique. La créature fait un jet de sauvegarde de Force (DD 8 + bonus de maîtrise + modificateur de la caractéristique augmentée par ce don) : en cas d'échec, elle subit 2d8 dégâts de force et est repoussée jusqu'à 3 m ; en cas de réussite, elle subit la moitié des dégâts et n'est pas repoussée. Utilisable un nombre de fois égal à votre bonus de maîtrise, récupéré après un repos long.$t$),
  ($t$Don du dragon métallique$t$, $t$Gift of the Metallic Dragon$t$, $t${}$t$::jsonb,
   $t$Guérison draconique : vous apprenez Soin des blessures, que vous pouvez lancer une fois sans emplacement (utilisation récupérée après un repos long) ou avec vos emplacements ; la caractéristique d'incantation est l'Intelligence, la Sagesse ou le Charisme (choisie en prenant le don). Ailes protectrices : lorsque vous ou une créature que vous voyez à 1,50 m ou moins êtes touchés par un jet d'attaque, vous pouvez utiliser votre réaction pour déployer brièvement des ailes spectrales et ajouter votre bonus de maîtrise à la CA de la cible contre cette attaque, ce qui peut la faire échouer. Utilisable un nombre de fois égal à votre bonus de maîtrise, récupéré après un repos long.$t$),
  -- Bigby Presents: Glory of the Giants
  ($t$Frappe des géants$t$, $t$Strike of the Giants$t$, $t${"text":"Maîtrise des armes de guerre ou historique Enfant des géants"}$t$::jsonb,
   $t$Choisissez une frappe parmi les suivantes. Une fois par tour, quand vous touchez une cible avec une attaque d'arme au corps à corps ou une attaque à distance avec une arme de lancer, vous pouvez y ajouter son effet. Frappe des nuages : +1d4 dégâts de tonnerre ; une créature ratant un jet de sauvegarde de Sagesse ne vous voit plus (vous êtes invisible pour elle) jusqu'au début de votre prochain tour ou jusqu'à ce que vous attaquiez ou lanciez un sort. Frappe du feu : +1d10 dégâts de feu. Frappe du givre : +1d6 dégâts de froid ; une créature ratant un jet de sauvegarde de Constitution voit sa vitesse réduite à 0 jusqu'au début de votre prochain tour. Frappe des collines : +1d6 dégâts du type de l'arme ; une créature ratant un jet de sauvegarde de Force tombe à terre. Frappe de pierre : +1d6 dégâts de force ; une créature ratant un jet de sauvegarde de Force est repoussée de 3 m en ligne droite. Frappe des tempêtes : +1d6 dégâts de foudre ; une créature ratant un jet de sauvegarde de Constitution a le désavantage aux jets d'attaque jusqu'au début de votre prochain tour. DD = 8 + bonus de maîtrise + modificateur de Force ou de Constitution. Utilisable un nombre de fois égal à votre bonus de maîtrise, récupéré après un repos long.$t$),
  ($t$Braise du géant du feu$t$, $t$Ember of the Fire Giant$t$, $t${"text":"Niveau 4, don Frappe des géants (Frappe du feu)","level":4}$t$::jsonb,
   $t$Force, Constitution ou Sagesse +1 (max. 20). Né de la flamme : vous obtenez la résistance aux dégâts de feu. Embrasement brûlant : quand vous effectuez l'action Attaque à votre tour, vous pouvez remplacer une attaque par une explosion de flammes magiques. Chaque créature de votre choix dans une sphère de 4,50 m de rayon centrée sur vous fait un jet de sauvegarde de Dextérité (DD 8 + bonus de maîtrise + modificateur de la caractéristique augmentée) : en cas d'échec, elle subit 1d8 + votre bonus de maîtrise dégâts de feu et subit l'état aveuglé jusqu'au début de votre prochain tour ; en cas de réussite, elle subit seulement la moitié des dégâts. Utilisable un nombre de fois égal à votre bonus de maîtrise (une fois par tour au plus), récupéré après un repos long.$t$),
  ($t$Fureur du géant du givre$t$, $t$Fury of the Frost Giant$t$, $t${"text":"Niveau 4, don Frappe des géants (Frappe du givre)","level":4}$t$::jsonb,
   $t$Force, Constitution ou Sagesse +1 (max. 20). Né de la glace : vous obtenez la résistance aux dégâts de froid. Riposte glaciale : juste après qu'une créature que vous voyez à 9 m ou moins vous a touché avec un jet d'attaque et infligé des dégâts, vous pouvez utiliser votre réaction pour la frapper d'une décharge de glace. Elle fait un jet de sauvegarde de Constitution (DD 8 + bonus de maîtrise + modificateur de la caractéristique augmentée) ; en cas d'échec, elle subit 1d8 + votre bonus de maîtrise dégâts de froid et sa vitesse tombe à 0 jusqu'à la fin de son prochain tour. Utilisable un nombre de fois égal à votre bonus de maîtrise, récupéré après un repos long.$t$),
  ($t$Ruse du géant des nuages$t$, $t$Guile of the Cloud Giant$t$, $t${"text":"Niveau 4, don Frappe des géants (Frappe des nuages)","level":4}$t$::jsonb,
   $t$Force, Constitution ou Charisme +1 (max. 20). Fuite nébuleuse : quand une créature que vous voyez vous touche avec un jet d'attaque, vous pouvez utiliser votre réaction pour obtenir la résistance aux dégâts de cette attaque, puis vous téléporter dans un espace inoccupé que vous voyez à 9 m ou moins. Utilisable un nombre de fois égal à votre bonus de maîtrise, récupéré après un repos long.$t$),
  ($t$Acuité du géant des pierres$t$, $t$Keenness of the Stone Giant$t$, $t${"text":"Niveau 4, don Frappe des géants (Frappe de pierre)","level":4}$t$::jsonb,
   $t$Force, Constitution ou Sagesse +1 (max. 20). Vision des cavernes : vous obtenez la vision dans le noir sur 18 m, ou sa portée augmente de 18 m si vous l'aviez déjà. Jet de pierre : par une action bonus, vous lancez une pierre de façon magique : attaque de sort à distance, portée 18 m, utilisant la caractéristique augmentée par ce don. Si elle touche, la pierre inflige 1d10 dégâts de force et la cible doit réussir un jet de sauvegarde de Force (DD 8 + bonus de maîtrise + modificateur de cette caractéristique) ou tomber à terre. Utilisable un nombre de fois égal à votre bonus de maîtrise, récupéré après un repos long.$t$),
  ($t$Âme du géant des tempêtes$t$, $t$Soul of the Storm Giant$t$, $t${"text":"Niveau 4, don Frappe des géants (Frappe des tempêtes)","level":4}$t$::jsonb,
   $t$Force, Sagesse ou Charisme +1 (max. 20). Aura de tourmente : par une action bonus, vous vous entourez d'une aura de vent et d'éclairs sur 3 m (bloquée par un abri total), jusqu'au début de votre prochain tour ou jusqu'à ce que vous soyez neutralisé. Tant qu'elle est active, vous avez la résistance aux dégâts de foudre et de tonnerre, les jets d'attaque contre vous ont le désavantage, et vous pouvez forcer toute autre créature qui commence son tour dans l'aura à faire un jet de sauvegarde de Force (DD 8 + bonus de maîtrise + modificateur de la caractéristique augmentée) ; en cas d'échec, sa vitesse est réduite de moitié jusqu'au début de son prochain tour. Utilisable un nombre de fois égal à votre bonus de maîtrise, récupéré après un repos long.$t$),
  ($t$Vigueur du géant des collines$t$, $t$Vigor of the Hill Giant$t$, $t${"text":"Niveau 4, don Frappe des géants (Frappe des collines)","level":4}$t$::jsonb,
   $t$Force, Constitution ou Sagesse +1 (max. 20). Rempart : quand un effet devrait vous déplacer d'au moins 1,50 m ou vous faire tomber à terre, vous pouvez utiliser votre réaction pour vous ancrer : vous n'êtes ni déplacé ni à terre. Estomac de fer : quand vous mangez pendant un repos court et dépensez des dés de vie pour récupérer des points de vie, vous récupérez en plus un nombre de points de vie égal à votre modificateur de Constitution + votre bonus de maîtrise.$t$),
  ($t$Façonneur de runes$t$, $t$Rune Shaper$t$, $t${"text":"Aptitude Incantation ou historique Graveur de runes"}$t$::jsonb,
   $t$Vous apprenez Compréhension des langues, que vous pouvez lancer une fois sans emplacement (utilisation récupérée après un repos long) ou avec vos emplacements. Magie runique : vous connaissez un nombre de runes égal à la moitié de votre bonus de maîtrise (arrondi à l'inférieur). À la fin d'un repos long, vous pouvez graver chacune sur un objet non magique que vous touchez (arme, armure, vêtement...) ; vous connaissez alors le sort de niveau 1 associé jusqu'à votre prochain repos long et pouvez le lancer avec vos emplacements tant que vous portez l'objet. Vous pouvez aussi invoquer une rune pour lancer son sort sans emplacement ni composantes matérielles, une fois par repos long. Runes et sorts : Nuage (Nappe de brouillard), Mort (Blessure), Dragon (Orbe chromatique), Ennemi (Déguisement), Feu (Mains brûlantes), Ami (Communication avec les animaux), Givre (Armure d'Agathys), Colline (Baie nourricière), Voyage (Grande foulée), Roi (Injonction), Montagne (Enchevêtrement), Pierre (Sanctuaire), Tempête (Vague tonnante). La caractéristique d'incantation est l'Intelligence, la Sagesse ou le Charisme (choisie en prenant le don). À chaque niveau gagné, vous pouvez échanger une rune connue contre une autre.$t$),
  -- Planescape: Adventures in the Multiverse
  ($t$Rejeton des plans extérieurs$t$, $t$Scion of the Outer Planes$t$, $t${"text":"Campagne Planescape"}$t$::jsonb,
   $t$Votre lien avec un plan extérieur vous imprègne de son énergie. Choisissez un type de plan : vous obtenez la résistance et le tour de magie indiqués, que vous pouvez lancer sans composantes matérielles (caractéristique d'incantation : Intelligence, Sagesse ou Charisme, choisie en prenant le don). Plan extérieur chaotique : poison, Illusion mineure. Plan extérieur mauvais : nécrotique, Contact glacial. Plan extérieur bon : radiant, Flamme sacrée. Plan extérieur loyal : force, Assistance. Les Terres Extérieures : psychique, Main de mage.$t$),
  ($t$Agent de l'ordre$t$, $t$Agent of Order$t$, $t${"text":"Niveau 4, don Rejeton des plans extérieurs (plan extérieur loyal)","level":4}$t$::jsonb,
   $t$Augmentez une valeur de caractéristique de votre choix de 1 (max. 20). Frappe de stase : une fois par tour, quand vous infligez des dégâts à une créature que vous voyez à 18 m ou moins, vous pouvez lui infliger 1d8 dégâts de force supplémentaires ; elle doit réussir un jet de sauvegarde de Sagesse (DD 8 + bonus de maîtrise + modificateur de la caractéristique choisie pour Rejeton des plans extérieurs) ou subir l'état entravé, prise dans des liens spectraux, jusqu'au début de votre prochain tour. Utilisable un nombre de fois égal à votre bonus de maîtrise, récupéré après un repos long.$t$),
  ($t$Rejeton funeste$t$, $t$Baleful Scion$t$, $t${"text":"Niveau 4, don Rejeton des plans extérieurs (plan extérieur mauvais)","level":4}$t$::jsonb,
   $t$Augmentez une valeur de caractéristique de votre choix de 1 (max. 20). Étreinte de l'avarice : une fois par tour, quand vous infligez des dégâts à une créature que vous voyez à 18 m ou moins, vous pouvez lui infliger en plus 1d6 + votre bonus de maîtrise dégâts nécrotiques et récupérer autant de points de vie. Utilisable un nombre de fois égal à votre bonus de maîtrise, récupéré après un repos long.$t$),
  ($t$Cohorte du chaos$t$, $t$Cohort of Chaos$t$, $t${"text":"Niveau 4, don Rejeton des plans extérieurs (plan extérieur chaotique)","level":4}$t$::jsonb,
   $t$Augmentez une valeur de caractéristique de votre choix de 1 (max. 20). Éruption chaotique : quand vous obtenez 1 ou 20 sur un jet d'attaque ou un jet de sauvegarde, lancez 1d4 ; l'effet dure jusqu'à la fin de votre prochain tour et aucun autre ne peut survenir avant sa fin. 1 — Furie guerrière : une créature de votre choix que vous voyez a l'avantage aux jets d'attaque et le désavantage aux tests de caractéristique. 2 — Champ perturbateur : toute créature qui commence son tour à 1,50 m ou moins de vous, ou y entre pour la première fois du tour, subit 1d8 dégâts de force. 3 — Délié : quand vous vous déplacez, vous pouvez utiliser tout ou partie de votre vitesse au sol pour vous téléporter une fois, avec votre équipement, vers un espace inoccupé que vous voyez à cette distance. 4 — Vents hurlants : des vents tourbillonnent dans une sphère de 4,50 m de rayon centrée sur vous ; les créatures qui s'y trouvent, vous compris, ont le désavantage aux jets de sauvegarde de Sagesse.$t$),
  ($t$Émissaire des Terres Extérieures$t$, $t$Outlands Envoy$t$, $t${"text":"Niveau 4, don Rejeton des plans extérieurs (Terres Extérieures)","level":4}$t$::jsonb,
   $t$Augmentez une valeur de caractéristique de votre choix de 1 (max. 20). Émissaire des carrefours : vous apprenez Pas brumeux et Don des langues. Vous pouvez lancer chacun une fois sans emplacement (utilisation récupérée après un repos long), Don des langues sans composantes matérielles dans ce cas, ou avec vos emplacements. La caractéristique d'incantation est celle choisie pour Rejeton des plans extérieurs.$t$),
  ($t$Vagabond planaire$t$, $t$Planar Wanderer$t$, $t${"text":"Niveau 4, don Rejeton des plans extérieurs","level":4}$t$::jsonb,
   $t$Adaptation planaire : à la fin d'un repos long, vous obtenez la résistance aux dégâts d'acide, de feu ou de froid (au choix) jusqu'à la fin de votre prochain repos long. Briseur de portails : par une action, en vous concentrant sur un portail connu à 1,50 m ou moins, vous faites un test d'Intelligence (Arcanes) DD 20 ; en cas d'échec, vous subissez 3d8 dégâts psychiques et ne pouvez plus retenter sur ce portail avant un repos long ; en cas de réussite, vous forcez son ouverture ou sa fermeture pendant 1 heure, durant laquelle sa clé ne fonctionne qu'avec un test d'Intelligence (Arcanes) DD 20 réussi par une action. Sens des portails : vous connaissez la direction du dernier portail utilisé tant que vous êtes sur le même plan ; par une action, vous détectez les portails à 9 m ou moins qui ne sont pas derrière un abri total (une fois par repos long).$t$),
  ($t$Héritier vertueux$t$, $t$Righteous Heritor$t$, $t${"text":"Niveau 4, don Rejeton des plans extérieurs (plan extérieur bon)","level":4}$t$::jsonb,
   $t$Augmentez une valeur de caractéristique de votre choix de 1 (max. 20). Apaiser la douleur : quand vous ou une créature à 9 m ou moins subissez des dégâts, vous pouvez utiliser votre réaction pour réduire ces dégâts de 1d10 + votre bonus de maîtrise. Utilisable un nombre de fois égal à votre bonus de maîtrise, récupéré après un repos long.$t$),
  -- Dragonlance: Shadow of the Dragon Queen
  ($t$Initié de la Haute Sorcellerie$t$, $t$Initiate of High Sorcery$t$, $t${"text":"Campagne Dragonlance ; classe ensorceleur ou magicien, ou historique Mage de la Haute Sorcellerie"}$t$::jsonb,
   $t$Choisissez l'une des trois lunes de Krynn pour influencer votre magie. Vous apprenez un tour de magie de la liste du magicien et deux sorts de niveau 1 selon la lune. Nuitari (lune noire) : deux sorts parmi Murmures dissonants, Simulacre de vie, Maléfice et Rayon empoisonné. Lunitari (lune rouge) : deux sorts parmi Couleurs dansantes, Déguisement, Feuille morte et Grande foulée. Solinari (lune blanche) : deux sorts parmi Compréhension des langues, Détection du mal et du bien, Protection contre le mal et le bien et Bouclier. Vous pouvez lancer chaque sort de niveau 1 une fois sans emplacement (utilisation récupérée après un repos long) ou avec vos emplacements. Caractéristique d'incantation : Intelligence, Sagesse ou Charisme (choisie en prenant le don).$t$),
  ($t$Adepte des Robes noires$t$, $t$Adept of the Black Robes$t$, $t${"text":"Niveau 4, don Initié de la Haute Sorcellerie (Nuitari)","level":4}$t$::jsonb,
   $t$Magie ambitieuse : vous apprenez un sort de niveau 2 d'enchantement ou de nécromancie, que vous pouvez lancer une fois sans emplacement (utilisation récupérée après un repos long) ou avec vos emplacements ; caractéristique d'incantation : celle choisie pour Initié de la Haute Sorcellerie. Canal vital : quand une créature que vous voyez à 18 m ou moins rate un jet de sauvegarde contre un sort infligeant des dégâts que vous avez lancé, vous pouvez dépenser un nombre de dés de vie égal au niveau du sort, les lancer et ajouter leur total aux dégâts qu'elle subit.$t$),
  ($t$Adepte des Robes rouges$t$, $t$Adept of the Red Robes$t$, $t${"text":"Niveau 4, don Initié de la Haute Sorcellerie (Lunitari)","level":4}$t$::jsonb,
   $t$Magie perspicace : vous apprenez un sort de niveau 2 d'illusion ou de transmutation, que vous pouvez lancer une fois sans emplacement (utilisation récupérée après un repos long) ou avec vos emplacements ; caractéristique d'incantation : celle choisie pour Initié de la Haute Sorcellerie. Équilibre magique : quand vous obtenez 9 ou moins au d20 d'un jet d'attaque ou d'un test de caractéristique, vous pouvez considérer le résultat comme un 10. Utilisable un nombre de fois égal à votre bonus de maîtrise, récupéré après un repos long.$t$),
  ($t$Adepte des Robes blanches$t$, $t$Adept of the White Robes$t$, $t${"text":"Niveau 4, don Initié de la Haute Sorcellerie (Solinari)","level":4}$t$::jsonb,
   $t$Magie protectrice : vous apprenez un sort de niveau 2 d'abjuration ou de divination, que vous pouvez lancer une fois sans emplacement (utilisation récupérée après un repos long) ou avec vos emplacements ; caractéristique d'incantation : celle choisie pour Initié de la Haute Sorcellerie. Garde protectrice : quand vous ou une créature que vous voyez à 9 m ou moins subissez des dégâts, vous pouvez utiliser votre réaction et dépenser un emplacement de sort : lancez autant de d6 que le niveau de l'emplacement et réduisez les dégâts du total + votre modificateur de caractéristique d'incantation.$t$),
  ($t$Favori divin$t$, $t$Divinely Favored$t$, $t${"text":"Niveau 4, campagne Dragonlance","level":4}$t$::jsonb,
   $t$Un dieu vous a confié une étincelle de son pouvoir. Vous apprenez un tour de magie de la liste du clerc, le sort Augure et un sort de niveau 1 selon votre alignement : mauvais, un sort d'occultiste ; bon, un sort de clerc ; neutre, un sort de druide. Vous pouvez lancer le sort de niveau 1 et Augure une fois chacun sans emplacement (utilisations récupérées après un repos long) ou avec vos emplacements. Caractéristique d'incantation : Intelligence, Sagesse ou Charisme (choisie en prenant le don). Vous pouvez utiliser un symbole sacré comme focaliseur pour les sorts qui utilisent cette caractéristique.$t$),
  ($t$Écuyer de Solamnie$t$, $t$Squire of Solamnia$t$, $t${"text":"Campagne Dragonlance ; classe guerrier ou paladin, ou historique Chevalier de Solamnie"}$t$::jsonb,
   $t$En selle : monter en selle ou en descendre ne vous coûte que 1,50 m de déplacement. Frappe précise : une fois par tour, quand vous effectuez un jet d'attaque avec une arme contre une créature, vous pouvez lui donner l'avantage ; si l'attaque touche, ajoutez 1d8 aux dégâts. Utilisable un nombre de fois égal à votre bonus de maîtrise (une utilisation n'est dépensée que si l'attaque touche), récupéré après un repos long.$t$),
  ($t$Chevalier de la Couronne$t$, $t$Knight of the Crown$t$, $t${"text":"Niveau 4, don Écuyer de Solamnie","level":4}$t$::jsonb,
   $t$Force, Dextérité ou Constitution +1 (max. 20). Ralliement impérieux : par une action bonus, vous ordonnez à un allié à 9 m ou moins d'attaquer ; s'il peut vous voir ou vous entendre, il peut aussitôt effectuer une attaque avec une arme en utilisant sa réaction, et ajoute 1d8 aux dégâts si elle touche. Utilisable un nombre de fois égal à votre bonus de maîtrise, récupéré après un repos long.$t$),
  ($t$Chevalier de la Rose$t$, $t$Knight of the Rose$t$, $t${"text":"Niveau 4, don Écuyer de Solamnie","level":4}$t$::jsonb,
   $t$Constitution, Sagesse ou Charisme +1 (max. 20). Ralliement revigorant : par une action bonus, vous encouragez une créature que vous voyez à 9 m ou moins (vous compris) ; si elle peut vous voir ou vous entendre, elle gagne 1d8 + votre bonus de maîtrise + le modificateur de la caractéristique augmentée par ce don points de vie temporaires. Utilisable un nombre de fois égal à votre bonus de maîtrise, récupéré après un repos long.$t$),
  ($t$Chevalier de l'Épée$t$, $t$Knight of the Sword$t$, $t${"text":"Niveau 4, don Écuyer de Solamnie","level":4}$t$::jsonb,
   $t$Intelligence, Sagesse ou Charisme +1 (max. 20). Frappe démoralisante : une fois par tour, quand vous touchez une créature avec un jet d'attaque d'arme, vous pouvez tenter de l'effrayer : elle fait un jet de sauvegarde de Sagesse (DD 8 + bonus de maîtrise + modificateur de la caractéristique augmentée). En cas d'échec, elle est effrayée par vous jusqu'à la fin de votre prochain tour ; en cas de réussite, elle a le désavantage à son prochain jet d'attaque avant la fin de son prochain tour. Utilisable un nombre de fois égal à votre bonus de maîtrise, récupéré après un repos long.$t$)
    ) as t(name_fr, name_en, prerequisites, description)
  loop
    if not exists (
      select 1 from public.translations tr
       where tr.entity_type = 'feat' and tr.field_name = 'name' and tr.locale = 'fr'
         and lower(tr.value) = lower(rec.name_fr)
    ) then
      insert into public.feats (prerequisites) values (rec.prerequisites) returning id into v_id;
      insert into public.translations (entity_type, entity_id, field_name, locale, value) values
        ('feat', v_id::text, 'name', 'fr', rec.name_fr),
        ('feat', v_id::text, 'name', 'en', rec.name_en),
        ('feat', v_id::text, 'description', 'fr', rec.description);
      v_inserted := v_inserted + 1;
    end if;
  end loop;
  raise notice 'dons insérés : %', v_inserted;
end $$;
