-- Partie 2/3 : objets magiques Necklace of Fireballs à la fin.
-- Contenu D&D — lot 2 : équipement et objets magiques du SRD 5.2 (règles 2024).
--
-- Ajoute 250 objets magiques (entrées du livre : les variantes par arme ou par
-- armure de l'API Open5e sont regroupées, ex. « Arme +1 », « Langue de feu ») et
-- 103 objets ordinaires absents de la base (matériel d'aventurier, munitions,
-- outils, montures, véhicules, mousquet et pistolet). Textes traduits en français
-- (poids convertis en kg, distances en mètres) ; le nom anglais est ajouté en
-- locale « en » pour faciliter les rapprochements futurs.
--
-- Source : Open5e API v2, documents srd-2024 (items, magicitems), récupérés le
-- 2026-09-30.
--
-- Licence : ce contenu inclut des éléments du System Reference Document 5.2
-- (« SRD 5.2 ») de Wizards of the Coast LLC, disponible sur
-- https://www.dndbeyond.com/srd. Le SRD 5.2 est placé sous licence Creative
-- Commons Attribution 4.0 International (https://creativecommons.org/licenses/by/4.0/legalcode).
--
-- Idempotente : un objet dont le nom FR existe déjà n'est pas réinséré.

do $$
declare
  rec record;
  v_id int;
  v_inserted int := 0;
begin
  for rec in
    select * from (values
  ($t$Collier de boules de feu$t$, $t$Necklace of Fireballs$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce collier porte 1d6 + 3 perles. Par une action Magie, vous pouvez en détacher une et la lancer jusqu'à 18 m : au bout de sa trajectoire, elle explose comme une Boule de feu de niveau 3 (DD 15). Vous pouvez lancer plusieurs perles, voire tout le collier, en même temps ; les dégâts de la Boule de feu augmentent alors de 1d6 par perle après la première (12d6 au maximum).$t$),
  ($t$Chapelet de prière$t$, $t$Necklace of Prayer Beads$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Harmonisation par un clerc, un druide ou un paladin.
Ce collier porte 1d4 + 2 perles magiques d'aigue-marine, de perle noire ou de topaze, parmi de nombreuses perles non magiques (ambre, héliotrope, citrine, corail, jade, perle, quartz…). Une perle magique retirée du collier perd sa magie.
Il en existe six types, choisis par le MJ ou au hasard (d20) ; un collier peut en avoir plusieurs du même type. Vous devez porter le collier pour les utiliser. Chaque perle contient un sort que vous pouvez lancer par une action bonus (avec votre DD de sauvegarde de sorts si besoin) ; elle n'est ensuite plus utilisable avant l'aube suivante.
1-6 Bénédiction : Bénédiction. 7-12 Guérison : Soins (version de niveau 2). 13-16 Faveur : Restauration supérieure. 17-18 Châtiment : Châtiment radieux. 19 Convocation : Gardien de la foi. 20 Marche sur le vent : Marche sur le vent.$t$),
  ($t$Voleuse de neuf vies$t$, $t$Nine Lives Stealer$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous bénéficiez d'un bonus de +2 aux jets d'attaque et de dégâts effectués avec cette arme magique.
Vol de vie. L'arme possède 1d8 + 1 charges. Quand vous attaquez avec elle une créature qui a moins de 100 points de vie et obtenez 20 au d20, la créature doit réussir un JS de Constitution DD 15 ou mourir sur le coup, l'épée arrachant sa force vitale (réussite automatique pour les artificiels et les morts-vivants). L'arme perd 1 charge si la créature meurt ; sans charge, elle perd cette propriété.$t$),
  ($t$Arc du serment$t$, $t$Oathbow$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Quand vous encochez une flèche, cet arc murmure en elfique : « Prompte défaite à mes ennemis. » Quand vous l'utilisez pour une attaque à distance, vous pouvez prononcer ou signer : « Prompte mort à toi qui m'as nui. » La cible devient votre ennemi juré jusqu'à sa mort ou jusqu'à l'aube, 7 jours plus tard. Vous ne pouvez avoir qu'un ennemi juré à la fois ; s'il meurt, vous pouvez en choisir un nouveau après l'aube suivante.
Contre votre ennemi juré, vos jets d'attaque à distance avec cet arc ont l'avantage, la cible ne bénéficie pas d'un abri partiel ou important, et la longue portée ne vous impose pas de désavantage. Si l'attaque touche, elle inflige 3d6 dégâts perforants supplémentaires. Tant que votre ennemi juré est en vie, vous avez le désavantage aux jets d'attaque avec toutes les autres armes.$t$),
  ($t$Huile éthérée$t$, $t$Oil of Etherealness$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Une fiole de cette huile suffit à enduire une créature de taille M ou inférieure et l'équipement qu'elle porte (une fiole de plus par catégorie de taille au-delà de M). L'application prend 10 minutes ; la créature obtient ensuite l'effet du sort Forme éthérée pendant 1 heure. Des gouttes de cette huile grise et trouble perlent sur la fiole et s'évaporent aussitôt.$t$),
  ($t$Huile glissante$t$, $t$Oil of Slipperiness$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Une fiole de cette huile suffit à enduire une créature de taille M ou inférieure et l'équipement qu'elle porte (une fiole de plus par catégorie de taille au-delà de M). L'application prend 10 minutes ; la créature obtient ensuite l'effet du sort Liberté de mouvement pendant 8 heures. Au lieu de cela, l'huile peut être versée au sol par une action Magie : elle couvre un carré de 3 m et reproduit l'effet du sort Graisse pendant 8 heures. Cet onguent noir est épais et lourd, mais coule vite quand on le verse.$t$),
  ($t$Perle de pouvoir$t$, $t$Pearl of Power$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Harmonisation par un lanceur de sorts.
Tant que cette perle est sur vous, vous pouvez effectuer une action Magie pour récupérer un emplacement de sort dépensé de niveau 3 ou inférieur. La perle n'est ensuite plus utilisable avant l'aube suivante.$t$),
  ($t$Talisman de santé$t$, $t$Periapt of Health$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez ce pendentif, vous pouvez effectuer une action Magie pour récupérer 2d4 + 2 points de vie ; propriété inutilisable ensuite avant l'aube suivante. Vous avez aussi l'avantage aux jets de sauvegarde pour éviter ou terminer l'état empoisonné.$t$),
  ($t$Talisman d'immunité au poison$t$, $t$Periapt of Proof against Poison$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette délicate chaîne d'argent porte un pendentif serti d'une gemme noire taillée en brillant. Tant que vous la portez, vous êtes immunisé contre l'état empoisonné et les dégâts de poison.$t$),
  ($t$Talisman de cicatrisation$t$, $t$Periapt of Wound Closure$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez ce pendentif, vous bénéficiez de ces avantages :
Préservation de la vie. Lors d'un jet de sauvegarde contre la mort, vous pouvez transformer un résultat de 9 ou moins en 10, changeant un échec en réussite.
Guérison naturelle accrue. Quand vous lancez un dé de vie pour récupérer des points de vie, doublez les points de vie qu'il rend.$t$),
  ($t$Philtre d'amour$t$, $t$Philter of Love$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$La prochaine créature que vous voyez dans les 10 minutes qui suivent la consommation de ce philtre vous charme : vous êtes charmé par elle pendant 1 heure. Ce liquide rosé et pétillant contient une bulle en forme de cœur, facile à manquer.$t$),
  ($t$Flûte d'épouvante$t$, $t$Pipes of Haunting$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette flûte possède 3 charges et en récupère 1d3 chaque jour à l'aube. Par une action Magie, vous pouvez en jouer et dépenser 1 charge pour produire un air étrange et envoûtant : chaque créature de votre choix à 9 m ou moins doit réussir un JS de Sagesse DD 15 ou être effrayée pendant 1 minute. Elle répète le jet à la fin de chacun de ses tours et met fin à l'effet en cas de réussite. Une créature qui réussit est immunisée contre cette flûte pendant 24 heures.$t$),
  ($t$Flûte des égouts$t$, $t$Pipes of the Sewers$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que cette flûte est sur vous, les rats ordinaires et les rats géants sont indifférents envers vous et ne vous attaquent pas à moins que vous ne les menaciez ou leur fassiez du mal. Elle possède 3 charges et en récupère 1d3 chaque jour à l'aube.
Si vous en jouez par une action Magie, vous pouvez par une action bonus dépenser 1 à 3 charges pour appeler une nuée de rats par charge, s'il y a assez de rats à 800 m ou moins (selon le MJ) ; sinon, la charge est perdue. Les nuées appelées se dirigent vers la musique par le chemin le plus court, sans être autrement sous votre contrôle.
Chaque fois qu'une nuée de rats non contrôlée arrive à 9 m ou moins pendant que vous jouez, elle effectue un JS de Sagesse DD 15. En cas de réussite, elle agit normalement et ne peut être influencée par la flûte pendant 24 heures. En cas d'échec, elle devient amicale envers vous et vos alliés tant que vous continuez à jouer chaque round par une action Magie, et obéit à vos ordres (sans ordre, elle se défend mais n'agit pas). Si elle commence son tour à plus de 9 m de vous, votre contrôle cesse et elle ne peut plus être influencée pendant 24 heures.$t$),
  ($t$Trou portatif$t$, $t$Portable Hole$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce fin tissu noir, doux comme la soie, est plié à la taille d'un mouchoir et se déplie en un disque de 1,80 m de diamètre. Par une action Magie, vous pouvez le déplier et le poser sur une surface solide : il crée un trou extradimensionnel de 3 m de profondeur. L'espace cylindrique se trouve sur un autre plan d'existence et ne peut donc pas servir à ouvrir un passage. Une créature à l'intérieur d'un trou ouvert peut en sortir en grimpant.
Par une action Magie, vous pouvez refermer le trou en saisissant les bords du tissu et en le repliant ; les créatures et objets à l'intérieur restent dans l'espace extradimensionnel. Quel que soit son contenu, le trou ne pèse presque rien. Trou replié, une créature à l'intérieur peut effectuer une action pour tenter un test de Force (Athlétisme) DD 10 ; en cas de réussite, elle force le passage et apparaît à 1,50 m ou moins du trou. Fermé, il contient assez d'air pour 1 heure de respiration, divisée par le nombre de créatures qui respirent à l'intérieur.
Placer le trou portatif dans un espace extradimensionnel (sac sans fond, havresac magique…) détruit les deux objets et ouvre un portail à sens unique vers le plan Astral, qui aspire toute créature à 3 m ou moins sans abri total puis se referme.$t$),
  ($t$Potion d'amitié avec les animaux$t$, $t$Potion of Animal Friendship$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Quand vous buvez cette potion, vous pouvez lancer la version de niveau 3 du sort Amitié avec les animaux (DD 13). En agitant son liquide boueux, on aperçoit une écaille de poisson, une plume de colibri, une griffe de chat ou un poil d'écureuil.$t$),
  ($t$Potion de clairvoyance$t$, $t$Potion of Clairvoyance$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Quand vous buvez cette potion, vous obtenez l'effet du sort Clairvoyance (sans concentration). Un globe oculaire flotte dans son liquide jaunâtre, mais disparaît quand on ouvre la fiole.$t$),
  ($t$Potion d'escalade$t$, $t$Potion of Climbing$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Commun$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Quand vous buvez cette potion, vous obtenez une vitesse d'escalade égale à votre vitesse pendant 1 heure, et l'avantage aux tests de Force (Athlétisme) pour escalader. La potion se sépare en couches brune, argentée et grise, comme des strates de pierre ; secouer la fiole ne mélange pas les couleurs.$t$),
  ($t$Potion de rapetissement$t$, $t$Potion of Diminution$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Quand vous buvez cette potion, vous obtenez l'effet « rapetisser » du sort Agrandissement/Rapetissement pendant 1d4 heures (sans concentration). Le rouge de son liquide se contracte sans cesse en une minuscule goutte avant de se diffuser à nouveau dans le liquide clair ; secouer la fiole n'interrompt pas le phénomène.$t$),
  ($t$Potion de vol$t$, $t$Potion of Flying$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Quand vous buvez cette potion, vous obtenez une vitesse de vol égale à votre vitesse pendant 1 heure, et vous pouvez faire du surplace. Si vous êtes en l'air quand l'effet prend fin, vous tombez, sauf autre moyen de rester en l'air. Son liquide clair flotte en haut de la fiole, parcouru d'impuretés blanches et troubles.$t$),
  ($t$Potion de forme gazeuse$t$, $t$Potion of Gaseous Form$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Quand vous buvez cette potion, vous obtenez l'effet du sort Forme gazeuse pendant 1 heure (sans concentration) ou jusqu'à ce que vous y mettiez fin par une action bonus. La fiole semble contenir un brouillard qui bouge et se verse comme de l'eau.$t$),
  ($t$Potion d'agrandissement$t$, $t$Potion of Growth$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Quand vous buvez cette potion, vous obtenez l'effet « agrandir » du sort Agrandissement/Rapetissement pendant 10 minutes (sans concentration). Le rouge de son liquide s'étend sans cesse depuis une minuscule goutte avant de se contracter à nouveau ; secouer la fiole n'interrompt pas le phénomène.$t$),
  ($t$Potion d'héroïsme$t$, $t$Potion of Heroism$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Quand vous buvez cette potion, vous gagnez 10 points de vie temporaires pendant 1 heure et, pour la même durée, vous êtes sous l'effet du sort Bénédiction (sans concentration). Son liquide bleu bouillonne et fume comme s'il était en ébullition.$t$),
  ($t$Potion d'invisibilité$t$, $t$Potion of Invisibility$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$La fiole semble vide mais on sent qu'elle contient un liquide. Quand vous buvez cette potion, vous êtes invisible pendant 1 heure. L'effet prend fin plus tôt si vous effectuez un jet d'attaque, infligez des dégâts ou lancez un sort.$t$),
  ($t$Potion de lecture des pensées$t$, $t$Potion of Mind Reading$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Quand vous buvez cette potion, vous obtenez l'effet du sort Détection des pensées (DD 13) pendant 10 minutes (sans concentration). Un nuage rose ovoïde flotte dans son liquide violet et dense.$t$),
  ($t$Potion empoisonnée$t$, $t$Potion of Poison$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette mixture ressemble à une potion de soins ou à une autre potion bénéfique, par son aspect, son odeur et son goût, mais c'est en réalité un poison masqué par une illusion ; le sort Identification révèle sa vraie nature. Si vous la buvez, vous subissez 4d6 dégâts de poison et devez réussir un JS de Constitution DD 13 ou être empoisonné pendant 1 heure.$t$),
  ($t$Potion de résistance$t$, $t$Potion of Resistance$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Quand vous buvez cette potion, vous avez la résistance à un type de dégâts pendant 1 heure. Le MJ choisit le type ou le détermine au hasard (d10) : 1 acide, 2 froid, 3 feu, 4 force, 5 foudre, 6 nécrotique, 7 poison, 8 psychique, 9 radiant, 10 tonnerre.$t$),
  ($t$Potion de rapidité$t$, $t$Potion of Speed$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Quand vous buvez cette potion, vous obtenez l'effet du sort Hâte pendant 1 minute (sans concentration), sans subir la vague de léthargie qui suit normalement la fin de l'effet. Son liquide jaune, strié de noir, tourbillonne de lui-même.$t$),
  ($t$Potion de respiration aquatique$t$, $t$Potion of Water Breathing$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous pouvez respirer sous l'eau pendant 24 heures après avoir bu cette potion. Son liquide vert et trouble sent la mer, et une bulle en forme de méduse y flotte.$t$),
  ($t$Anneau d'influence animale$t$, $t$Ring of Animal Influence$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cet anneau possède 3 charges et en récupère 1d3 chaque jour à l'aube. Tant que vous le portez, vous pouvez dépenser 1 charge pour lancer l'un de ces sorts (DD 13) : Amitié avec les animaux, Peur (n'affecte que les bêtes), Communication avec les animaux.$t$),
  ($t$Anneau de convocation de djinn$t$, $t$Ring of Djinni Summoning$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez cet anneau, vous pouvez effectuer une action Magie pour convoquer un djinn particulier du plan élémentaire de l'Air. Il apparaît dans un espace inoccupé de votre choix à 36 m ou moins et reste tant que vous maintenez votre concentration, jusqu'à 1 heure, ou jusqu'à ce qu'il tombe à 0 point de vie. Il est amical envers vous et vos alliés et obéit à vos ordres ; sans ordre, il se défend mais n'agit pas autrement. Après son départ, il ne peut plus être convoqué pendant 24 heures, et l'anneau perd sa magie si le djinn meurt. Ces anneaux sont souvent créés par les djinns eux-mêmes et offerts à des mortels en gage d'amitié ou d'estime.$t$),
  ($t$Anneau de contrôle élémentaire$t$, $t$Ring of Elemental Command$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Chaque anneau est lié à l'un des quatre plans élémentaires, choisi par le MJ ou au hasard. Tous ont les propriétés suivantes :
Fléau des élémentaires. Vous avez l'avantage aux jets d'attaque contre les élémentaires, qui ont le désavantage aux jets d'attaque contre vous.
Contrainte élémentaire. Par une action Magie, vous pouvez tenter de contraindre un élémentaire que vous voyez à 18 m ou moins : il effectue un JS de Sagesse DD 18 ; en cas d'échec, il est charmé jusqu'au début de votre prochain tour, et vous décidez de son déplacement et de son action à son prochain tour.
Focalisation élémentaire. Selon le plan lié :
Air : vous connaissez l'aérien, avez la résistance aux dégâts de foudre et une vitesse de vol égale à votre vitesse, avec vol stationnaire.
Terre : vous connaissez le terreux, avez la résistance aux dégâts d'acide ; les gravats, rochers et terre ne sont pas un terrain difficile pour vous, et vous pouvez traverser la terre et la roche comme un terrain difficile sans les perturber (si vous finissez votre tour dedans, vous êtes expulsé vers le dernier espace libre occupé).
Feu : vous connaissez l'igné et êtes immunisé contre les dégâts de feu.
Eau : vous connaissez l'aquatique, avez une vitesse de nage de 18 m et pouvez respirer sous l'eau.
Sorts. L'anneau possède 5 charges et en récupère 1d4 + 1 chaque jour à l'aube ; vous pouvez lancer un sort (DD 18) selon le plan lié :
Air : Chaîne d'éclairs (3 charges), Feuille morte (0), Bourrasque (2), Mur de vent (1).
Terre : Tremblement de terre (5), Façonnage de la pierre (2), Peau de pierre (3), Mur de pierre (3).
Feu : Mains brûlantes (1), Boule de feu (2), Tempête de feu (4), Mur de feu (3).
Eau : Création ou destruction d'eau (1), Tempête de grêle (2), Tsunami (5), Mur de glace (3), Marche sur l'eau (2).$t$),
  ($t$Anneau d'esquive$t$, $t$Ring of Evasion$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cet anneau possède 3 charges et en récupère 1d3 chaque jour à l'aube. Quand vous ratez un jet de sauvegarde de Dextérité alors que vous le portez, vous pouvez utiliser votre réaction et dépenser 1 charge pour réussir le jet à la place.$t$),
  ($t$Anneau de feuille morte$t$, $t$Ring of Feather Falling$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Quand vous tombez alors que vous portez cet anneau, vous descendez de 18 m par round et ne subissez aucun dégât de chute.$t$),
  ($t$Anneau de liberté d'action$t$, $t$Ring of Free Action$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez cet anneau, le terrain difficile ne vous coûte pas de déplacement supplémentaire. De plus, la magie ne peut ni réduire vos vitesses, ni vous paralyser, ni vous entraver.$t$),
  ($t$Anneau d'invisibilité$t$, $t$Ring of Invisibility$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez cet anneau, vous pouvez effectuer une action Magie pour devenir invisible. Vous le restez jusqu'à ce que vous retiriez l'anneau ou redeveniez visible par une action bonus.$t$),
  ($t$Anneau de saut$t$, $t$Ring of Jumping$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez cet anneau, vous pouvez lancer Saut avec lui, en ne ciblant que vous-même.$t$),
  ($t$Anneau de barrière mentale$t$, $t$Ring of Mind Shielding$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez cet anneau, vous êtes immunisé contre la magie qui permettrait à d'autres créatures de lire vos pensées, de savoir si vous mentez, de connaître votre alignement ou votre type de créature. On ne peut communiquer avec vous par télépathie que si vous l'autorisez. Par une action Magie, vous pouvez rendre l'anneau imperceptible jusqu'à ce que vous le rendiez perceptible par une autre action Magie, le retiriez ou mouriez.
Si vous mourez en le portant, votre âme y entre, à moins qu'il n'en abrite déjà une. Vous pouvez y rester ou partir vers l'au-delà. Tant que votre âme s'y trouve, vous pouvez communiquer par télépathie avec quiconque le porte, qui ne peut empêcher cette communication.$t$),
  ($t$Anneau de protection$t$, $t$Ring of Protection$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous bénéficiez d'un bonus de +1 à la CA et aux jets de sauvegarde tant que vous portez cet anneau.$t$),
  ($t$Anneau de régénération$t$, $t$Ring of Regeneration$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez cet anneau, vous récupérez 1d6 points de vie toutes les 10 minutes si vous avez au moins 1 point de vie. Si vous perdez une partie du corps, l'anneau la fait repousser, pleinement fonctionnelle, en 1d6 + 1 jours, si vous gardez au moins 1 point de vie pendant tout ce temps.$t$),
  ($t$Anneau de résistance$t$, $t$Ring of Resistance$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous avez la résistance à un type de dégâts tant que vous portez cet anneau. La pierre de l'anneau indique le type, choisi par le MJ ou au hasard (d10) : 1 acide (perle), 2 froid (tourmaline), 3 feu (grenat), 4 force (saphir), 5 foudre (citrine), 6 nécrotique (jais), 7 poison (améthyste), 8 psychique (jade), 9 radiant (topaze), 10 tonnerre (spinelle).$t$),
  ($t$Anneau d'étoiles filantes$t$, $t$Ring of Shooting Stars$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous pouvez lancer Lumières dansantes ou Lumière avec cet anneau. Il possède 6 charges et en récupère 1d6 chaque jour à l'aube ; vous pouvez les dépenser pour ces propriétés :
Lueurs féeriques. 1 charge pour lancer Lueurs féeriques.
Sphères de foudre. Par une action Magie et 2 charges, vous créez jusqu'à quatre sphères de foudre de 90 cm de diamètre, chacune dans un espace inoccupé que vous voyez à 36 m ou moins. Elles durent tant que vous maintenez votre concentration, jusqu'à 1 minute, et diffusent une lumière faible sur 9 m. Par une action bonus, vous pouvez déplacer chaque sphère de 9 m, sans dépasser 36 m de vous. La première fois qu'une sphère arrive à 1,50 m ou moins d'une autre créature sans abri total, elle se décharge sur elle et disparaît : la créature effectue un JS de Dextérité DD 15 et subit, en cas d'échec, des dégâts de foudre selon le nombre de sphères créées (1 : 4d12 ; 2 : 5d4 ; 3 : 2d6 ; 4 : 2d4), la moitié en cas de réussite.
Étoiles filantes. Par une action Magie, vous dépensez 1 à 3 charges ; pour chaque charge, un point lumineux jaillit vers un point que vous voyez à 18 m ou moins. Chaque créature dans un cube de 4,50 m à partir de ce point est criblée d'étincelles et effectue un JS de Dextérité DD 15 : 5d4 dégâts radiants en cas d'échec, la moitié en cas de réussite.$t$),
  ($t$Anneau de stockage de sorts$t$, $t$Ring of Spell Storing$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cet anneau stocke les sorts lancés dans lui jusqu'à ce que son porteur harmonisé les utilise. Il peut contenir jusqu'à 5 niveaux de sorts à la fois ; trouvé, il en contient 1d6 - 1 niveaux choisis par le MJ. N'importe quelle créature peut y lancer un sort de niveau 1 à 5 en touchant l'anneau pendant l'incantation ; le sort n'a d'autre effet que d'y être stocké, ou est perdu s'il ne tient pas. Le niveau de l'emplacement utilisé détermine la place occupée.
Tant que vous portez l'anneau, vous pouvez lancer n'importe quel sort qu'il contient ; le sort utilise le niveau d'emplacement, le DD, le bonus d'attaque et la caractéristique d'incantation du lanceur d'origine, mais est traité comme lancé par vous. Il libère alors sa place.$t$),
  ($t$Anneau de renvoi des sorts$t$, $t$Ring of Spell Turning$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez cet anneau, vous avez l'avantage aux jets de sauvegarde contre les sorts. Si vous réussissez le jet contre un sort de niveau 7 ou inférieur, il n'a aucun effet sur vous. Si ce sort ne ciblait que vous et ne créait pas de zone d'effet, vous pouvez utiliser votre réaction pour le renvoyer sur son lanceur, qui doit effectuer un jet de sauvegarde contre son propre DD.$t$),
  ($t$Anneau de nage$t$, $t$Ring of Swimming$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous avez une vitesse de nage de 12 m tant que vous portez cet anneau.$t$),
  ($t$Anneau de télékinésie$t$, $t$Ring of Telekinesis$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez cet anneau, vous pouvez lancer Télékinésie avec lui.$t$),
  ($t$Anneau du bélier$t$, $t$Ring of the Ram$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cet anneau possède 3 charges et en récupère 1d3 chaque jour à l'aube. Tant que vous le portez, vous pouvez effectuer une action Magie et dépenser 1 à 3 charges pour une attaque de sort à distance contre une créature que vous voyez à 18 m ou moins : l'anneau produit une tête de bélier spectrale et attaque avec un bonus de +7. En cas de réussite, pour chaque charge dépensée, la cible subit 2d10 dégâts de force et est repoussée de 1,50 m.
Au lieu de cela, par une action Magie et 1 à 3 charges, vous pouvez tenter de briser un objet non magique non porté que vous voyez à 18 m ou moins : l'anneau effectue un test de Force avec un bonus de +5 par charge dépensée.$t$),
  ($t$Anneau des trois souhaits$t$, $t$Ring of Three Wishes$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez cet anneau, vous pouvez dépenser l'une de ses 3 charges pour lancer Souhait avec lui. L'anneau perd sa magie quand vous utilisez la dernière charge.$t$),
  ($t$Anneau de chaleur$t$, $t$Ring of Warmth$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Si vous subissez des dégâts de froid alors que vous portez cet anneau, il les réduit de 2d8. De plus, tant que vous le portez, vous et tout ce que vous portez ne souffrez pas des températures de -18 °C ou moins.$t$),
  ($t$Anneau de marche sur l'eau$t$, $t$Ring of Water Walking$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez cet anneau, vous pouvez lancer Marche sur l'eau avec lui, en ne ciblant que vous-même.$t$),
  ($t$Anneau de vision aux rayons X$t$, $t$Ring of X-ray Vision$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez cet anneau, vous pouvez effectuer une action Magie pour obtenir la vision aux rayons X sur 9 m pendant 1 minute : les objets solides dans ce rayon vous paraissent transparents et laissent passer la lumière. Cette vision traverse 30 cm de pierre, 2,5 cm de métal commun ou jusqu'à 90 cm de bois ou de terre ; une matière plus épaisse ou une fine feuille de plomb la bloque. Chaque nouvelle utilisation avant un repos long exige un JS de Constitution DD 15, sous peine de gagner 1 niveau d'épuisement.$t$),
  ($t$Robe aux yeux$t$, $t$Robe of Eyes$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette robe est ornée de motifs en forme d'yeux. Tant que vous la portez, vous bénéficiez de ces avantages :
Vision panoramique. Vous avez l'avantage aux tests de Sagesse (Perception) basés sur la vue.
Sens spéciaux. Vous avez la vision dans le noir et la vision véritable sur 36 m.
Inconvénients. Le sort Lumière lancé sur la robe, ou Lumière du jour lancé à 1,50 m ou moins d'elle, vous aveugle pendant 1 minute. À la fin de chacun de vos tours, vous effectuez un JS de Constitution (DD 11 pour Lumière, DD 15 pour Lumière du jour) et mettez fin à l'état en cas de réussite.$t$),
  ($t$Robe de couleurs scintillantes$t$, $t$Robe of Scintillating Colors$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette robe possède 3 charges et en récupère 1d3 chaque jour à l'aube. Tant que vous la portez, vous pouvez effectuer une action Magie et dépenser 1 charge pour qu'elle affiche un motif changeant de couleurs éblouissantes jusqu'à la fin de votre prochain tour. Pendant ce temps, elle diffuse une lumière vive dans un rayon de 9 m et une lumière faible sur 9 m de plus, et les créatures qui vous voient ont le désavantage aux jets d'attaque contre vous. Toute créature dans la lumière vive qui vous voit au moment de l'activation doit réussir un JS de Sagesse DD 15 ou être étourdie jusqu'à la fin de l'effet.$t$),
  ($t$Robe étoilée$t$, $t$Robe of Stars$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette robe noire ou bleu nuit est brodée de petites étoiles blanches ou argentées. Vous bénéficiez d'un bonus de +1 aux jets de sauvegarde tant que vous la portez.
Six étoiles, sur le haut du devant, sont particulièrement grandes. Par une action Magie, vous pouvez en détacher une et la dépenser pour lancer la version de niveau 5 de Projectile magique. Chaque jour au crépuscule, 1d6 étoiles détachées réapparaissent.
Par une action Magie, vous pouvez aussi passer dans le plan Astral avec tout ce que vous portez, et y rester jusqu'à ce que vous reveniez sur votre plan d'origine par une autre action Magie ; vous réapparaissez dans le dernier espace occupé, ou le plus proche espace libre.$t$),
  ($t$Robe de l'archimage$t$, $t$Robe of the Archmagi$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Harmonisation par un ensorceleur, un magicien ou un occultiste.
Ce vêtement élégant, taillé dans une étoffe raffinée, est orné de runes. Tant que vous le portez, vous bénéficiez de ces avantages :
Armure. Si vous ne portez pas d'armure, votre CA de base est de 15 + votre modificateur de Dextérité.
Résistance à la magie. Vous avez l'avantage aux jets de sauvegarde contre les sorts et autres effets magiques.
Mage de guerre. Votre DD de sauvegarde des sorts et votre bonus d'attaque des sorts augmentent chacun de 2.$t$),
  ($t$Robe aux objets utiles$t$, $t$Robe of Useful Items$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette robe est couverte de pièces de tissu de formes et de couleurs variées. Tant que vous la portez, vous pouvez par une action Magie détacher une pièce, qui devient l'objet ou la créature qu'elle représente. Une fois la dernière pièce retirée, la robe devient un vêtement ordinaire.
Elle porte deux exemplaires de chacune de ces pièces : lanterne sourde (remplie et allumée), dague, miroir, perche, corde (enroulée), sac. Elle porte en plus 4d4 autres pièces, choisies par le MJ ou au hasard (d100) :
01-08 bourse de 100 po ; 09-15 coffret d'argent (30 × 15 × 15 cm) d'une valeur de 500 po ; 16-22 porte de fer (jusqu'à 3 m × 3 m, barrée du côté de votre choix) que vous pouvez placer dans une ouverture à votre portée, où elle s'ajuste et se fixe ; 23-30 10 gemmes de 100 po ; 31-44 échelle de bois de 7,20 m ; 45-51 cheval de selle avec sa selle ; 52-59 fosse ouverte (cube de 3 m) à placer au sol à 3 m ou moins ; 60-68 4 potions de soins ; 69-75 barque de 3,60 m ; 76-83 parchemin de sort de niveau 1, 2 ou 3 (au choix) ; 84-90 2 molosses ; 91-96 fenêtre (60 cm × 1,20 m, jusqu'à 60 cm de profondeur) à placer sur une surface verticale à votre portée ; 97-00 bélier portatif.$t$),
  ($t$Sceptre d'absorption$t$, $t$Rod of Absorption$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous tenez ce sceptre, vous pouvez utiliser votre réaction pour absorber un sort qui ne cible que vous et ne crée pas de zone d'effet. Son effet est annulé et son énergie (pas le sort lui-même) est stockée dans le sceptre, au niveau auquel il a été lancé ; les ressources dépensées par le lanceur sont perdues. Le sceptre peut absorber 50 niveaux d'énergie au total au cours de son existence, puis plus rien ; un sort qu'il ne peut stocker n'est pas affecté.
En vous harmonisant, vous savez combien de niveaux il a absorbés depuis sa création et combien il en contient. Si vous êtes lanceur de sorts, vous pouvez convertir l'énergie stockée en emplacements pour lancer des sorts que vous connaissez ou avez préparés, jusqu'au niveau de vos propres emplacements et au maximum de niveau 5 (par exemple, 3 niveaux stockés pour un emplacement de niveau 3). Un sceptre nouvellement trouvé contient généralement 1d10 niveaux. Un sceptre qui ne peut plus absorber et n'a plus d'énergie perd sa magie.$t$),
  ($t$Sceptre de vigilance$t$, $t$Rod of Alertness$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce sceptre a les propriétés suivantes :
Vigilance. Tant que vous le tenez, vous avez l'avantage aux tests de Sagesse (Perception) et aux jets d'initiative.
Sorts. Tant que vous le tenez, vous pouvez lancer avec lui : Détection du mal et du bien, Détection de la magie, Détection du poison et des maladies, Voir l'invisible.
Aura protectrice. Par une action Magie, vous plantez le sceptre dans le sol : sa tête diffuse une lumière vive dans un rayon de 18 m et une lumière faible sur 18 m de plus. Dans la lumière vive, vous et vos alliés bénéficiez d'un bonus de +1 à la CA et aux jets de sauvegarde, et percevez l'emplacement de toute créature invisible également dans la lumière vive. L'effet cesse après 10 minutes ou quand une créature arrache le sceptre par une action Magie. Propriété inutilisable avant l'aube suivante.$t$),
  ($t$Sceptre de puissance seigneuriale$t$, $t$Rod of Lordly Might$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce sceptre à tête à ailettes fonctionne comme une masse d'armes magique conférant un bonus de +3 aux jets d'attaque et de dégâts. Il possède six boutons alignés sur le manche, et trois autres propriétés.
Boutons. Vous pouvez presser un bouton par une action bonus ; son effet dure jusqu'à ce que vous en pressiez un autre, ou le même à nouveau pour revenir à la forme normale :
1. Une lame enflammée jaillit de l'extrémité opposée : elle diffuse une lumière vive sur 12 m et faible sur 12 m de plus, et fonctionne comme une épée longue ou courte magique (au choix) infligeant 2d6 dégâts de feu supplémentaires.
2. La tête se replie et deux lames en croissant surgissent : le sceptre devient une hache d'armes magique (+3).
3. La tête se replie, une pointe jaillit et le manche s'allonge à 1,80 m : le sceptre devient une lance magique (+3).
4. Le sceptre devient une perche d'escalade de 15 m au plus (longueur au choix), les boutons restant à portée. Une pointe à la base et trois crochets au sommet l'ancrent même dans le granite ; des barreaux de 7,5 cm se déplient tous les 30 cm pour former une échelle. Elle supporte 2 tonnes ; au-delà, ou sans ancrage solide, elle reprend sa forme normale.
5. Le sceptre devient un bélier à main et confère un bonus de +10 aux tests de Force (Athlétisme) pour enfoncer portes, barricades et autres obstacles.
6. Le sceptre prend ou garde sa forme normale et indique le nord magnétique (sans effet là où il n'y en a pas), et vous renseigne sur votre profondeur approximative sous terre ou votre altitude.
Drain de vie. Quand vous touchez une créature au corps à corps avec le sceptre, vous pouvez la forcer à faire un JS de Constitution DD 17 ; en cas d'échec, elle subit 4d6 dégâts nécrotiques supplémentaires et vous récupérez la moitié de ces dégâts en points de vie. Inutilisable avant l'aube suivante.
Paralysie. Quand vous touchez une créature au corps à corps, vous pouvez la forcer à faire un JS de Constitution DD 17 ; en cas d'échec, elle est paralysée pendant 1 minute et répète le jet à la fin de chacun de ses tours. Inutilisable avant l'aube suivante.
Terreur. Par une action Magie, chaque créature que vous voyez à 9 m ou moins doit réussir un JS de Sagesse DD 17 ou être effrayée pendant 1 minute, en répétant le jet à la fin de chacun de ses tours. Inutilisable avant l'aube suivante.$t$),
  ($t$Sceptre de souveraineté$t$, $t$Rod of Rulership$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Par une action Magie, vous pouvez brandir ce sceptre et exiger l'obéissance de chaque créature de votre choix que vous voyez à 36 m ou moins. Chaque cible doit réussir un JS de Sagesse DD 15 ou être charmée pendant 8 heures ; elle vous considère alors comme un chef de confiance. Elle cesse d'être charmée si vous ou vos alliés lui faites du mal ou si on lui ordonne d'agir contre sa nature. Propriété inutilisable avant l'aube suivante.$t$),
  ($t$Sceptre de sécurité$t$, $t$Rod of Security$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous tenez ce sceptre, vous pouvez l'activer par une action Magie : il transporte instantanément vous et jusqu'à 199 autres créatures consentantes que vous voyez dans un demi-plan dont vous choisissez la forme (jardin paisible, taverne joyeuse, palais immense, île tropicale, carnaval fantastique…). Quelle que soit sa nature, il contient assez d'eau et de nourriture pour ses visiteurs et son environnement ne peut pas leur nuire. Tout ce avec quoi on y interagit n'existe que là : une fleur cueillie disparaît si on l'emporte dehors.
Pour chaque heure passée dans le demi-plan, un visiteur récupère des points de vie comme s'il avait dépensé 1 dé de vie. Les créatures n'y vieillissent pas, bien que le temps s'écoule normalement. Les visiteurs peuvent y rester jusqu'à 200 jours divisés par le nombre de créatures présentes (arrondi à l'inférieur). Quand ce temps est écoulé ou que vous mettez fin à l'effet par une action Magie, tous réapparaissent à l'endroit où vous avez activé le sceptre ou dans l'espace libre le plus proche. Propriété inutilisable pendant 10 jours.$t$),
  ($t$Corde d'escalade$t$, $t$Rope of Climbing$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette corde de 18 m peut supporter jusqu'à 1,5 tonne. En tenant une extrémité, vous pouvez par une action Magie ordonner à l'autre extrémité de s'animer et de se diriger vers une destination de votre choix, dans la limite de sa longueur. Elle avance de 3 m au tour où vous donnez l'ordre, puis de 3 m au début de chacun de vos tours suivants, jusqu'à destination ou jusqu'à ce que vous l'arrêtiez. Vous pouvez aussi lui ordonner de s'attacher solidement à un objet ou de se détacher, de se nouer ou de se dénouer, ou de s'enrouler pour être transportée. Nouée, elle présente de gros nœuds tous les 30 cm, raccourcit à 15 m et confère l'avantage aux tests pour grimper le long d'elle.
La corde a CA 20, 20 PV et l'immunité aux dégâts de poison et psychiques. Elle récupère 1 point de vie toutes les 5 minutes tant qu'elle en a au moins 1, et est détruite à 0 point de vie.$t$),
  ($t$Corde d'enchevêtrement$t$, $t$Rope of Entanglement$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette corde mesure 9 m. En tenant une extrémité, vous pouvez par une action Magie ordonner à l'autre de s'élancer pour enchevêtrer une créature que vous voyez à 6 m ou moins, qui doit réussir un JS de Dextérité DD 15 ou être entravée. Vous pouvez la libérer en lâchant votre extrémité (la corde s'enroule dans l'espace de la cible) ou en répétant l'ordre par une action bonus (la corde s'enroule dans votre main).
Une cible entravée peut effectuer une action pour tenter, au choix, un test de Force (Athlétisme) ou de Dextérité (Acrobaties) DD 15 ; en cas de réussite, elle se libère. Si vous tenez encore la corde à ce moment, vous pouvez par une réaction la faire s'enrouler dans votre main ; sinon, elle s'enroule dans l'espace de la cible.
La corde a CA 20, 20 PV et l'immunité aux dégâts de poison et psychiques. Elle récupère 1 point de vie toutes les 5 minutes tant qu'elle en a au moins 1, et est détruite à 0 point de vie.$t$),
  ($t$Scarabée de protection$t$, $t$Scarab of Protection$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce médaillon en forme de scarabée procure trois avantages tant qu'il est sur vous :
Défense. Vous bénéficiez d'un bonus de +1 à la CA.
Préservation. Le scarabée possède 12 charges. Si vous ratez un jet de sauvegarde contre un sort de nécromancie ou un effet nuisible provenant d'un mort-vivant, vous pouvez utiliser votre réaction et dépenser 1 charge pour réussir le jet à la place. Le scarabée tombe en poussière quand sa dernière charge est dépensée.
Résistance aux sorts. Vous avez l'avantage aux jets de sauvegarde contre les sorts.$t$),
  ($t$Cimeterre de rapidité$t$, $t$Scimitar of Speed$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous bénéficiez d'un bonus de +2 aux jets d'attaque et de dégâts effectués avec cette arme magique. De plus, vous pouvez effectuer une attaque avec elle par une action bonus à chacun de vos tours.$t$),
  ($t$Bouclier d'attraction des projectiles$t$, $t$Shield of Missile Attraction$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous tenez ce bouclier, vous avez la résistance aux dégâts des attaques effectuées avec des armes à distance.
Malédiction. Le bouclier est maudit : vous y harmoniser vous maudit jusqu'à ce que vous soyez ciblé par Délivrance des malédictions ou une magie similaire, et retirer le bouclier ne met pas fin à la malédiction. Chaque fois qu'une attaque avec une arme à distance cible une créature à 3 m ou moins de vous, la malédiction fait de vous la cible à sa place.$t$),
  ($t$Bouclier +1$t$, $t$Shield, +1$t$, $t$objet_magique$t$, 3, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous tenez ce bouclier, vous bénéficiez d'un bonus de +1 à la CA (selon sa rareté), en plus du bonus normal du bouclier.$t$),
  ($t$Bouclier +2$t$, $t$Shield, +2$t$, $t$objet_magique$t$, 3, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous tenez ce bouclier, vous bénéficiez d'un bonus de +2 à la CA (selon sa rareté), en plus du bonus normal du bouclier.$t$),
  ($t$Bouclier +3$t$, $t$Shield, +3$t$, $t$objet_magique$t$, 3, null::jsonb, $t$Très rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous tenez ce bouclier, vous bénéficiez d'un bonus de +3 à la CA (selon sa rareté), en plus du bonus normal du bouclier.$t$),
  ($t$Chaussons de pattes d'araignée$t$, $t$Slippers of Spider Climbing$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez ces chaussures légères, vous pouvez vous déplacer sur les surfaces verticales et au plafond, les mains libres, et vous avez une vitesse d'escalade égale à votre vitesse. Elles ne fonctionnent pas sur une surface glissante, comme de la glace ou de l'huile.$t$),
  ($t$Colle universelle$t$, $t$Sovereign Glue$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette substance visqueuse d'un blanc laiteux peut lier de façon permanente deux objets quelconques. Elle doit être conservée dans un pot ou une fiole enduit à l'intérieur d'huile glissante. Trouvé, un récipient en contient 1d6 + 1 doses de 30 g ; une dose couvre une surface de 30 cm de côté. L'appliquer demande une action Utiliser, et la colle prend en 1 minute. Le lien ne peut ensuite être rompu que par du solvant universel, de l'huile éthérée ou un sort Souhait.$t$),
  ($t$Bouclier gardesort$t$, $t$Spellguard Shield$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous tenez ce bouclier, vous avez l'avantage aux jets de sauvegarde contre les sorts et autres effets magiques, et les jets d'attaque de sort contre vous ont le désavantage.$t$),
  ($t$Sphère d'annihilation$t$, $t$Sphere of Annihilation$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette sphère noire de 60 cm de diamètre est un trou dans le multivers, flottant dans l'espace et stabilisée par un champ magique. Elle anéantit toute matière qu'elle traverse ou qui la traverse, à l'exception des artefacts (sauf ceux vulnérables à une sphère d'annihilation). Tout ce qui la touche sans être entièrement englouti et anéanti subit 8d10 dégâts de force.
Contrôler la sphère. Elle reste immobile tant que personne ne la contrôle. À 18 m ou moins d'elle, vous pouvez par une action Magie faire un test d'Intelligence (Arcanes) DD 25. En cas de réussite, vous la contrôlez jusqu'au début de votre prochain tour (et la personne qui la contrôlait en perd le contrôle) ; en cas d'échec, elle se déplace de 3 m en ligne droite vers vous. Tant que vous la contrôlez, vous pouvez par une action bonus la déplacer dans la direction de votre choix d'un nombre de mètres égal à 1,50 × votre modificateur d'Intelligence (1,50 m minimum). Toute créature dont elle entre dans l'espace doit réussir un JS de Dextérité DD 19 ou être touchée et subir 8d10 dégâts de force ; une créature réduite à 0 PV par ces dégâts est anéantie, ne laissant que ses possessions.
Interactions. Si la sphère touche un portail planaire (comme celui de Portail) ou un espace extradimensionnel (comme un trou portatif), le MJ lance un d100 : 01-50 la sphère est détruite ; 51-85 elle traverse le portail ou entre dans l'espace ; 86-00 une faille spatiale envoie la sphère et chaque créature et objet à 54 m ou moins vers un plan d'existence aléatoire.$t$),
  ($t$Bâton d'envoûtement$t$, $t$Staff of Charming$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Harmonisation par un barde, un clerc, un druide, un ensorceleur, un magicien ou un occultiste.
Ce bâton possède 10 charges. Tant que vous le tenez, vous pouvez utiliser ses propriétés :
Lancer un sort. 1 charge pour lancer Charme-personne, Injonction ou Compréhension des langues, avec votre DD de sauvegarde.
Renvoyer un enchantement. Si vous réussissez un jet de sauvegarde contre un sort d'enchantement qui ne cible que vous, vous pouvez utiliser votre réaction et dépenser 1 charge pour le renvoyer sur son lanceur comme si vous l'aviez lancé.
Résister à un enchantement. Si vous ratez un jet de sauvegarde contre un sort d'enchantement qui ne cible que vous, vous pouvez le transformer en réussite. Inutilisable avant l'aube suivante.
Recharge. Le bâton récupère 1d8 + 2 charges chaque jour à l'aube. Si vous dépensez la dernière charge, lancez 1d20 : sur un 1, il tombe en poussière et est détruit.$t$),
  ($t$Bâton de feu$t$, $t$Staff of Fire$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Harmonisation par un druide, un ensorceleur, un magicien ou un occultiste.
Vous avez la résistance aux dégâts de feu tant que vous tenez ce bâton.
Sorts. Il possède 10 charges. Tant que vous le tenez, vous pouvez lancer avec lui, avec votre DD de sauvegarde : Mains brûlantes (1 charge), Boule de feu (3), Mur de feu (4).
Recharge. Il récupère 1d6 + 4 charges chaque jour à l'aube. Si vous dépensez la dernière charge, lancez 1d20 : sur un 1, il se réduit en cendres et est détruit.$t$),
  ($t$Bâton de givre$t$, $t$Staff of Frost$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Harmonisation par un druide, un ensorceleur, un magicien ou un occultiste.
Vous avez la résistance aux dégâts de froid tant que vous tenez ce bâton.
Sorts. Il possède 10 charges. Tant que vous le tenez, vous pouvez lancer avec lui, avec votre DD de sauvegarde : Cône de froid (5 charges), Nappe de brouillard (1), Tempête de grêle (4), Mur de glace (4).
Recharge. Il récupère 1d6 + 4 charges chaque jour à l'aube. Si vous dépensez la dernière charge, lancez 1d20 : sur un 1, il se change en eau et est détruit.$t$),
  ($t$Bâton de guérison$t$, $t$Staff of Healing$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Harmonisation par un barde, un clerc ou un druide.
Ce bâton possède 10 charges. Tant que vous le tenez, vous pouvez lancer avec lui, avec votre modificateur de caractéristique d'incantation : Soins (1 charge par niveau de sort, jusqu'à 4), Restauration partielle (2), Soins de groupe (5).
Recharge. Il récupère 1d6 + 4 charges chaque jour à l'aube. Si vous dépensez la dernière charge, lancez 1d20 : sur un 1, il disparaît dans un éclair de lumière, perdu à jamais.$t$),
  ($t$Bâton de surpuissance$t$, $t$Staff of Power$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Harmonisation par un ensorceleur, un magicien ou un occultiste.
Ce bâton possède 20 charges et peut être manié comme un bâton de combat magique conférant un bonus de +2 aux jets d'attaque et de dégâts. Tant que vous le tenez, vous bénéficiez d'un bonus de +2 à la CA, aux jets de sauvegarde et aux jets d'attaque de sort.
Sorts. Tant que vous le tenez, vous pouvez lancer avec lui, avec votre DD de sauvegarde : Cône de froid (5 charges), Boule de feu version niveau 5 (5), Globe d'invulnérabilité (6), Immobilisation de monstre (5), Lévitation (2), Éclair version niveau 5 (5), Projectile magique (1), Rayon affaiblissant (1), Mur de force (5).
Recharge. Il récupère 2d8 + 4 charges chaque jour à l'aube. Si vous dépensez la dernière charge, lancez 1d20 : sur un 1, il garde son bonus de +2 aux jets d'attaque et de dégâts mais perd toutes ses autres propriétés ; sur un 20, il récupère 1d8 + 2 charges.
Frappe vengeresse. Par une action Magie, vous pouvez briser le bâton sur votre genou ou contre une surface solide. Il est détruit et libère sa magie dans une explosion qui remplit une émanation de 9 m autour de lui. Vous avez 50 % de chances d'être instantanément transporté vers un plan aléatoire, évitant l'explosion ; sinon, vous subissez des dégâts de force égaux à 16 × le nombre de charges restantes. Chaque autre créature dans la zone effectue un JS de Dextérité DD 17 : dégâts de force égaux à 4 × le nombre de charges en cas d'échec, la moitié en cas de réussite.$t$),
  ($t$Bâton de frappe$t$, $t$Staff of Striking$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce bâton peut être manié comme un bâton de combat magique conférant un bonus de +3 aux jets d'attaque et de dégâts. Il possède 10 charges. Quand vous touchez au corps à corps avec lui, vous pouvez dépenser jusqu'à 3 charges ; chaque charge inflige 1d6 dégâts de force supplémentaires à la cible.
Recharge. Il récupère 1d6 + 4 charges chaque jour à l'aube. Si vous dépensez la dernière charge, lancez 1d20 : sur un 1, il devient un bâton de combat non magique.$t$),
  ($t$Bâton des essaims d'insectes$t$, $t$Staff of Swarming Insects$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Harmonisation par un barde, un clerc, un druide, un ensorceleur, un magicien ou un occultiste.
Ce bâton possède 10 charges.
Nuée d'insectes. Tant que vous le tenez, vous pouvez effectuer une action Magie et dépenser 1 charge pour qu'un essaim d'insectes volants inoffensifs remplisse une émanation de 9 m autour de vous pendant 10 minutes ; la zone est fortement obscurcie pour les autres créatures que vous. Un vent fort (comme celui de Bourrasque) disperse l'essaim.
Sorts. Vous pouvez lancer avec lui, avec votre DD et votre modificateur d'attaque de sort : Insecte géant (4 charges), Fléau d'insectes (5).
Recharge. Il récupère 1d6 + 4 charges chaque jour à l'aube. Si vous dépensez la dernière charge, lancez 1d20 : sur un 1, un essaim d'insectes dévore le bâton puis se disperse.$t$),
  ($t$Bâton du mage$t$, $t$Staff of the Magi$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Harmonisation par un ensorceleur, un magicien ou un occultiste.
Ce bâton possède 50 charges et peut être manié comme un bâton de combat magique conférant un bonus de +2 aux jets d'attaque et de dégâts. Tant que vous le tenez, vous bénéficiez d'un bonus de +2 aux jets d'attaque de sort.
Absorption des sorts. Tant que vous le tenez, vous avez l'avantage aux jets de sauvegarde contre les sorts. Quand une autre créature lance un sort qui ne cible que vous, vous pouvez utiliser votre réaction pour que le bâton en absorbe la magie : l'effet est annulé et le bâton gagne un nombre de charges égal au niveau du sort. Si son total dépasse alors 50, il explose comme par sa Frappe vengeresse.
Sorts. Vous pouvez lancer avec lui, avec votre DD : Verrou magique (0), Invocation d'élémentaire (7), Détection de la magie (0), Dissipation de la magie (3), Agrandissement/Rapetissement (0), Boule de feu version niveau 7 (7), Sphère de feu (2), Tempête de grêle (4), Invisibilité (2), Déblocage (2), Lumière (0), Éclair version niveau 7 (7), Main de mage (0), Passe-muraille (5), Changement de plan (7), Protection contre le mal et le bien (0), Télékinésie (5), Mur de feu (4), Toile d'araignée (2).
Recharge. Il récupère 4d6 + 2 charges chaque jour à l'aube. Si vous dépensez la dernière charge, lancez 1d20 : sur un 20, il récupère 1d12 + 1 charges.
Frappe vengeresse. Par une action Magie, vous pouvez briser le bâton ; il est détruit et explose dans une émanation de 9 m. Vous avez 50 % de chances d'être transporté vers un plan aléatoire ; sinon, vous subissez des dégâts de force égaux à 16 × le nombre de charges. Chaque autre créature dans la zone effectue un JS de Dextérité DD 17 : dégâts de force égaux à 6 × le nombre de charges en cas d'échec, la moitié en cas de réussite.$t$),
  ($t$Bâton du python$t$, $t$Staff of the Python$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Par une action Magie, vous pouvez lancer ce bâton dans un espace inoccupé à 3 m ou moins : il devient un serpent constricteur géant. Le serpent est sous votre contrôle et agit juste après vous dans l'ordre d'initiative. À votre tour, vous pouvez lui donner mentalement des ordres (sans action) s'il est à 18 m ou moins et que vous n'êtes pas neutralisé : vous décidez de son action et de son déplacement, ou lui donnez un ordre général (attaquer vos ennemis, garder un lieu…). Sans ordre, il se défend.
Par une action bonus, vous pouvez lui ordonner de reprendre sa forme de bâton dans son espace ; la propriété n'est alors plus utilisable pendant 1 heure. S'il tombe à 0 point de vie, il meurt et redevient un bâton, qui se brise et est détruit. S'il reprend sa forme de bâton avant d'avoir perdu tous ses points de vie, il les récupère tous.$t$),
  ($t$Bâton des forêts$t$, $t$Staff of the Woodlands$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Harmonisation par un druide.
Ce bâton possède 6 charges et peut être manié comme un bâton de combat magique conférant un bonus de +2 aux jets d'attaque et de dégâts. Tant que vous le tenez, vous bénéficiez d'un bonus de +2 aux jets d'attaque de sort.
Sorts. Vous pouvez lancer avec lui, avec votre DD : Amitié avec les animaux (1 charge), Éveil (5), Peau d'écorce (2), Localisation d'animaux ou de plantes (2), Passage sans trace (2), Communication avec les animaux (1), Communication avec les plantes (3), Mur d'épines (6).
Forme d'arbre. Par une action Magie, vous plantez une extrémité du bâton dans la terre d'un espace inoccupé et dépensez 1 charge pour le transformer en un arbre vigoureux de 18 m de haut, au tronc de 1,50 m de diamètre et aux branches déployées sur 6 m de rayon. Il semble ordinaire mais dégage une faible aura de transmutation détectable par Détection de la magie. En le touchant, par une action Magie, vous lui rendez sa forme de bâton ; toute créature dans l'arbre tombe alors.
Recharge. Il récupère 1d6 charges chaque jour à l'aube. Si vous dépensez la dernière charge, lancez 1d20 : sur un 1, il perd ses propriétés et devient un bâton de combat non magique.$t$),
  ($t$Bâton de tonnerre et de foudre$t$, $t$Staff of Thunder and Lightning$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce bâton peut être manié comme un bâton de combat magique conférant un bonus de +2 aux jets d'attaque et de dégâts. Il a aussi les propriétés suivantes, chacune inutilisable avant l'aube suivante une fois employée :
Foudre. Quand vous touchez au corps à corps avec le bâton, la cible peut subir 2d6 dégâts de foudre supplémentaires (sans action).
Tonnerre. Quand vous touchez au corps à corps, le bâton peut émettre un coup de tonnerre audible jusqu'à 90 m (sans action) : la cible doit réussir un JS de Constitution DD 17 ou être étourdie jusqu'à la fin de votre prochain tour.
Tonnerre et foudre. Juste après avoir touché au corps à corps, vous pouvez par une action bonus utiliser Foudre et Tonnerre en même temps, sans consommer leur usage quotidien, seulement celui-ci.
Coup de foudre. Par une action Magie, un éclair jaillit du bâton en une ligne de 1,50 m de large sur 36 m de long. Chaque créature dans la ligne effectue un JS de Dextérité DD 17 : 9d6 dégâts de foudre en cas d'échec, la moitié en cas de réussite.
Coup de tonnerre. Par une action Magie, le bâton produit un coup de tonnerre audible jusqu'à 180 m. Chaque créature dans une émanation de 18 m autour de vous effectue un JS de Constitution DD 17 : en cas d'échec, 2d6 dégâts de tonnerre et assourdie pendant 1 minute ; en cas de réussite, la moitié des dégâts seulement.$t$),
  ($t$Bâton de flétrissement$t$, $t$Staff of Withering$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce bâton possède 3 charges et en récupère 1d3 chaque jour à l'aube. Il peut être manié comme un bâton de combat magique. Quand il touche, il inflige les dégâts normaux d'un bâton de combat, et vous pouvez dépenser 1 charge pour infliger 2d10 dégâts nécrotiques supplémentaires et forcer la cible à faire un JS de Constitution DD 15 ; en cas d'échec, elle a le désavantage pendant 1 heure aux tests de caractéristique et jets de sauvegarde de Force et de Constitution.$t$),
  ($t$Pierre de contrôle des élémentaires de la terre$t$, $t$Stone of Controlling Earth Elementals$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$En posant cette pierre de 2,5 kg contre le sol, vous pouvez effectuer une action Magie pour convoquer un élémentaire de la terre. Il apparaît dans un espace inoccupé de votre choix à 9 m ou moins, obéit à vos ordres et agit juste après vous dans l'ordre d'initiative. Il disparaît après 1 heure, à sa mort ou quand vous le congédiez par une action bonus. La pierre n'est plus utilisable ainsi avant l'aube suivante.$t$),
  ($t$Pierre porte-bonheur$t$, $t$Stone of Good Luck$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que cette agate polie est sur vous, vous bénéficiez d'un bonus de +1 aux tests de caractéristique et aux jets de sauvegarde.$t$),
  ($t$Lame du soleil$t$, $t$Sun Blade$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cet objet ressemble à une poignée d'épée.
Lame de radiance. En tenant la poignée, vous pouvez par une action bonus faire apparaître ou disparaître une lame de pure lumière. Tant qu'elle existe, cette arme magique fonctionne comme une épée longue dotée de la propriété finesse ; si vous maîtrisez l'épée longue ou l'épée courte, vous la maîtrisez. Vous bénéficiez d'un bonus de +2 aux jets d'attaque et de dégâts, et elle inflige des dégâts radiants au lieu de tranchants. Quand vous touchez un mort-vivant, il subit 1d8 dégâts radiants supplémentaires.
Lumière du soleil. La lame émet une lumière vive dans un rayon de 4,50 m et une lumière faible sur 4,50 m de plus ; c'est de la lumière du soleil. Tant qu'elle existe, vous pouvez par une action Magie augmenter ou réduire chacun de ces rayons de 1,50 m (entre 3 m et 9 m).$t$),
  ($t$Épée voleuse de vie$t$, $t$Sword of Life Stealing$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Quand vous attaquez une créature avec cette arme magique et obtenez 20 au d20, la cible subit 15 dégâts nécrotiques supplémentaires si ce n'est ni un artificiel ni un mort-vivant, et vous gagnez autant de points de vie temporaires que les dégâts nécrotiques subis.$t$),
  ($t$Épée acérée$t$, $t$Sword of Sharpness$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Quand vous attaquez un objet avec cette arme magique et le touchez, les dés de dégâts de l'arme sont au maximum contre lui.
Quand vous attaquez une créature et obtenez 20 au d20, la cible subit 14 dégâts tranchants supplémentaires et gagne 1 niveau d'épuisement.$t$),
  ($t$Épée meurtrière$t$, $t$Sword of Wounding$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Quand vous touchez une créature avec cette arme magique, elle subit 2d6 dégâts nécrotiques supplémentaires et doit réussir un JS de Constitution DD 15 ou ne plus pouvoir récupérer de points de vie pendant 1 heure. Elle répète le jet à la fin de chacun de ses tours et met fin à l'effet en cas de réussite.$t$),
  ($t$Talisman du bien suprême$t$, $t$Talisman of Pure Good$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Harmonisation par un clerc ou un paladin.
Ce talisman est un puissant symbole de bonté. Un fiélon ou un mort-vivant qui le touche subit 8d6 dégâts radiants, et de nouveau chaque fois qu'il termine son tour en le tenant ou le portant.
Symbole sacré. Vous pouvez utiliser le talisman comme symbole sacré, et vous bénéficiez d'un bonus de +2 aux jets d'attaque de sort tant que vous le portez ou le tenez.
Réprimande pure. Le talisman possède 7 charges. Par une action Magie, vous pouvez dépenser 1 charge et cibler une créature au sol que vous voyez à 36 m ou moins : une fissure enflammée s'ouvre sous elle, et elle effectue un JS de Dextérité DD 20 (avec le désavantage si c'est un fiélon ou un mort-vivant). En cas d'échec, elle tombe dans la fissure et est détruite sans laisser de restes ; en cas de réussite, elle subit 4d6 dégâts psychiques. La fissure se referme ensuite sans laisser de trace. À la dernière charge, le talisman se dissipe en particules de lumière dorée et est détruit.$t$),
  ($t$Talisman de la sphère$t$, $t$Talisman of the Sphere$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous tenez ou portez ce talisman, vous avez l'avantage aux tests d'Intelligence (Arcanes) pour contrôler une sphère d'annihilation. De plus, quand vous commencez votre tour en contrôlant une sphère d'annihilation, vous pouvez par une action Magie la déplacer de 3 m plus 3 m par point de modificateur d'Intelligence, sans avoir à suivre une ligne droite.$t$),
  ($t$Talisman du mal absolu$t$, $t$Talisman of Ultimate Evil$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cet objet symbolise le mal sans repentir. Une créature qui n'est ni un fiélon ni un mort-vivant et qui le touche subit 8d6 dégâts nécrotiques, et de nouveau chaque fois qu'elle termine son tour en le tenant ou le portant.
Symbole sacré. Vous pouvez utiliser le talisman comme symbole sacré, et vous bénéficiez d'un bonus de +2 aux jets d'attaque de sort tant que vous le portez ou le tenez.
Fin ultime. Le talisman possède 6 charges. Par une action Magie, vous pouvez dépenser 1 charge et cibler une créature au sol que vous voyez à 36 m ou moins : une fissure enflammée s'ouvre sous elle, et elle effectue un JS de Dextérité DD 20 (avec le désavantage si c'est un céleste). En cas d'échec, elle tombe dans la fissure et est détruite sans laisser de restes ; en cas de réussite, elle subit 4d6 dégâts psychiques. La fissure se referme ensuite sans laisser de trace. À la dernière charge, le talisman se dissout en une vase nauséabonde et est détruit.$t$),
  ($t$Traité de perspicacité$t$, $t$Tome of Clear Thought$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce livre contient des exercices de mémoire et de logique chargés de magie. Si vous passez 48 heures, réparties sur 6 jours au plus, à étudier son contenu et à appliquer ses préceptes, votre Intelligence augmente de 2, jusqu'à un maximum de 30. Le livre perd alors sa magie, qu'il ne retrouve qu'au bout d'un siècle.$t$),
  ($t$Traité d'autorité et d'influence$t$, $t$Tome of Leadership and Influence$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce livre contient des préceptes pour influencer et charmer autrui, chargés de magie. Si vous passez 48 heures, réparties sur 6 jours au plus, à étudier son contenu et à appliquer ses préceptes, votre Charisme augmente de 2, jusqu'à un maximum de 30. Le livre perd alors sa magie, qu'il ne retrouve qu'au bout d'un siècle.$t$),
  ($t$Traité de compréhension$t$, $t$Tome of Understanding$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce livre contient des exercices d'intuition et de discernement chargés de magie. Si vous passez 48 heures, réparties sur 6 jours au plus, à étudier son contenu et à appliquer ses préceptes, votre Sagesse augmente de 2, jusqu'à un maximum de 30. Le livre perd alors sa magie, qu'il ne retrouve qu'au bout d'un siècle.$t$),
  ($t$Trident de domination aquatique$t$, $t$Trident of Fish Command$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette arme magique possède 3 charges et en récupère 1d3 chaque jour à l'aube. Tant que vous la portez, vous pouvez dépenser 1 charge pour lancer Domination de bête (DD 15) avec elle sur une bête dotée d'une vitesse de nage.$t$),
  ($t$Solvant universel$t$, $t$Universal Solvent$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce tube contient un liquide laiteux à forte odeur d'alcool ; trouvé, il en contient 1d6 + 1 doses de 30 g. Par une action Utiliser, vous pouvez verser une dose ou plus sur une surface à votre portée. Chaque dose dissout instantanément jusqu'à 30 cm de côté de toute substance adhésive, y compris la colle universelle.$t$),
  ($t$Arme vicieuse$t$, $t$Vicious Weapon$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette arme magique inflige 2d6 dégâts supplémentaires à toute créature qu'elle touche, du même type que ses dégâts normaux.$t$),
  ($t$Épée vorpale$t$, $t$Vorpal Sword$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous bénéficiez d'un bonus de +3 aux jets d'attaque et de dégâts effectués avec cette arme magique, qui ignore la résistance aux dégâts tranchants.
Quand vous attaquez avec elle une créature qui a au moins une tête et obtenez 20 au d20, vous tranchez l'une de ses têtes ; la créature meurt si elle ne peut survivre sans. Est immunisée une créature qui a l'immunité aux dégâts tranchants, qui n'a pas ou n'a pas besoin de tête, ou que le MJ juge trop grande pour que l'arme la décapite ; elle subit à la place 30 dégâts tranchants supplémentaires. Une créature dotée de résistance légendaire peut dépenser un usage quotidien de ce trait pour ne pas perdre sa tête et subir les dégâts supplémentaires à la place.$t$),
  ($t$Baguette d'entrave$t$, $t$Wand of Binding$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette baguette possède 7 charges. Tant que vous la tenez, vous pouvez lancer avec elle (DD 17) : Immobilisation de monstre (5 charges), Immobilisation de personne (2).
Recharge. Elle récupère 1d6 + 1 charges chaque jour à l'aube. Si vous dépensez la dernière charge, lancez 1d20 : sur un 1, elle tombe en cendres et est détruite.$t$),
  ($t$Baguette de détection de l'ennemi$t$, $t$Wand of Enemy Detection$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette baguette possède 7 charges. Tant que vous la tenez, vous pouvez effectuer une action Magie et dépenser 1 charge : pendant 1 minute, vous connaissez la direction (mais pas la distance) de la créature hostile la plus proche à 18 m ou moins, qu'elle soit invisible, éthérée, déguisée, cachée ou bien visible. L'effet cesse si vous lâchez la baguette.
Recharge. Elle récupère 1d6 + 1 charges chaque jour à l'aube. Si vous dépensez la dernière charge, lancez 1d20 : sur un 1, elle tombe en cendres et est détruite.$t$),
  ($t$Baguette de terreur$t$, $t$Wand of Fear$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette baguette possède 7 charges. Tant que vous la tenez, vous pouvez lancer avec elle (DD 15) : Injonction (« fuis » ou « rampe » uniquement, 1 charge), Peur (cône de 18 m, 3 charges).
Recharge. Elle récupère 1d6 + 1 charges chaque jour à l'aube. Si vous dépensez la dernière charge, lancez 1d20 : sur un 1, elle tombe en cendres et est détruite.$t$),
  ($t$Baguette de boules de feu$t$, $t$Wand of Fireballs$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Harmonisation par un lanceur de sorts.
Cette baguette possède 7 charges. Tant que vous la tenez, vous pouvez dépenser jusqu'à 3 charges pour lancer Boule de feu (DD 15) avec elle : 1 charge pour la version de niveau 3, un niveau de plus par charge supplémentaire.
Recharge. Elle récupère 1d6 + 1 charges chaque jour à l'aube. Si vous dépensez la dernière charge, lancez 1d20 : sur un 1, elle tombe en cendres et est détruite.$t$),
  ($t$Baguette d'éclairs$t$, $t$Wand of Lightning Bolts$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Harmonisation par un lanceur de sorts.
Cette baguette possède 7 charges. Tant que vous la tenez, vous pouvez dépenser jusqu'à 3 charges pour lancer Éclair (DD 15) avec elle : 1 charge pour la version de niveau 3, un niveau de plus par charge supplémentaire.
Recharge. Elle récupère 1d6 + 1 charges chaque jour à l'aube. Si vous dépensez la dernière charge, lancez 1d20 : sur un 1, elle tombe en cendres et est détruite.$t$),
  ($t$Baguette de détection de la magie$t$, $t$Wand of Magic Detection$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette baguette possède 3 charges. Tant que vous la tenez, vous pouvez dépenser 1 charge pour lancer Détection de la magie avec elle. Elle récupère 1d3 charges chaque jour à l'aube.$t$),
  ($t$Baguette de projectiles magiques$t$, $t$Wand of Magic Missiles$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette baguette possède 7 charges. Tant que vous la tenez, vous pouvez dépenser jusqu'à 3 charges pour lancer Projectile magique avec elle : 1 charge pour la version de niveau 1, un niveau de plus par charge supplémentaire.
Recharge. Elle récupère 1d6 + 1 charges chaque jour à l'aube. Si vous dépensez la dernière charge, lancez 1d20 : sur un 1, elle tombe en cendres et est détruite.$t$),
  ($t$Baguette de paralysie$t$, $t$Wand of Paralysis$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Harmonisation par un lanceur de sorts.
Cette baguette possède 7 charges. Tant que vous la tenez, vous pouvez effectuer une action Magie et dépenser 1 charge pour projeter un fin rayon bleu vers une créature que vous voyez à 18 m ou moins, qui doit réussir un JS de Constitution DD 15 ou être paralysée pendant 1 minute. Elle répète le jet à la fin de chacun de ses tours et met fin à l'effet en cas de réussite.
Recharge. Elle récupère 1d6 + 1 charges chaque jour à l'aube. Si vous dépensez la dernière charge, lancez 1d20 : sur un 1, elle tombe en cendres et est détruite.$t$),
  ($t$Baguette de métamorphose$t$, $t$Wand of Polymorph$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Harmonisation par un lanceur de sorts.
Cette baguette possède 7 charges. Tant que vous la tenez, vous pouvez dépenser 1 charge pour lancer Métamorphose (DD 15) avec elle.
Recharge. Elle récupère 1d6 + 1 charges chaque jour à l'aube. Si vous dépensez la dernière charge, lancez 1d20 : sur un 1, elle tombe en cendres et est détruite.$t$),
  ($t$Baguette des secrets$t$, $t$Wand of Secrets$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette baguette possède 3 charges et en récupère 1d3 chaque jour à l'aube. Tant que vous la tenez, vous pouvez effectuer une action Magie et dépenser 1 charge : si une porte secrète ou un piège se trouve à 18 m ou moins, la baguette vibre et pointe vers le plus proche.$t$),
  ($t$Baguette du mage de guerre$t$, $t$Wand of the War Mage$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun à très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous tenez cette baguette, vous bénéficiez d'un bonus aux jets d'attaque de sort qui dépend de sa rareté (+1 peu commune, +2 rare, +3 très rare). De plus, vous ignorez l'abri partiel quand vous effectuez un jet d'attaque de sort.$t$),
  ($t$Baguette de toiles d'araignée$t$, $t$Wand of Web$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Harmonisation par un lanceur de sorts.
Cette baguette possède 7 charges. Tant que vous la tenez, vous pouvez dépenser 1 charge pour lancer Toile d'araignée (DD 15) avec elle.
Recharge. Elle récupère 1d6 + 1 charges chaque jour à l'aube. Si vous dépensez la dernière charge, lancez 1d20 : sur un 1, elle tombe en cendres et est détruite.$t$),
  ($t$Baguette merveilleuse$t$, $t$Wand of Wonder$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette baguette possède 7 charges. Tant que vous la tenez, vous pouvez effectuer une action Magie et dépenser 1 charge en choisissant un point à 36 m ou moins : ce point devient l'origine d'un sort ou d'un effet magique déterminé sur la table ci-dessous. Les sorts lancés avec la baguette ont un DD de 15 ; si leur portée maximale est normalement inférieure à 36 m, elle passe à 36 m. Si un effet peut toucher plusieurs sujets, le MJ détermine au hasard lesquels.
Recharge. Elle récupère 1d6 + 1 charges chaque jour à l'aube. Si vous dépensez la dernière charge, lancez 1d20 : sur un 1, elle tombe en poussière et est détruite.
Effets (d100) :
01-20 : vous lancez un sort depuis le point choisi (d10) — 1-2 Ténèbres, 3-4 Lueurs féeriques, 5-6 Boule de feu, 7-8 Lenteur, 9-10 Nuage nauséabond.
21-25 : rien ne se passe au point choisi ; vous êtes étourdi jusqu'au début de votre prochain tour, persuadé que quelque chose d'extraordinaire vient d'arriver.
26-30 : vous lancez Bourrasque, la ligne allant de vous jusqu'au point choisi.
31-35 : rien ne se passe au point choisi ; vous subissez 1d6 dégâts psychiques.
36-40 : une forte pluie tombe pendant 1 minute dans un cylindre de 36 m de haut et 18 m de rayon centré sur le point ; la zone est légèrement obscurcie.
41-45 : un nuage de 600 papillons géants remplit un cylindre de 18 m de haut et 9 m de rayon centré sur le point pendant 10 minutes ; la zone est fortement obscurcie.
46-50 : vous lancez Éclair, la ligne allant de vous jusqu'au point choisi.
51-55 : la créature la plus proche du point est agrandie comme par Agrandissement/Rapetissement ; si ce n'est pas vous et qu'elle ne peut être affectée, c'est vous qui l'êtes.
56-60 : une créature apparaît près du point, hors de votre contrôle, et disparaît après 1 heure ou à 0 PV (d4 : 1 rhinocéros, 2 éléphant, 3-4 rat).
61-64 : de l'herbe couvre un cercle de 18 m de rayon centré au plus près du point ; l'herbe existante pousse jusqu'à dix fois sa taille pendant 1 minute.
65-68 : un objet non porté de 3 m au plus, à 36 m ou moins du point, choisi par le MJ, disparaît dans le plan Éthéré (rien s'il n'y en a pas).
69-72 : rien ne se passe au point choisi ; vous rapetissez comme par Agrandissement/Rapetissement pendant 1 minute.
73-77 : des feuilles poussent sur la créature la plus proche du point ; si on ne les arrache pas, elles brunissent et tombent après 24 heures.
78-82 : rien ne se passe au point choisi ; une gerbe de lumière chatoyante jaillit de vous en une émanation de 9 m. Chaque créature dans la zone doit réussir un JS de Constitution DD 15 ou être aveuglée pendant 1 minute, en répétant le jet à la fin de chacun de ses tours.
83-87 : rien ne se passe au point choisi ; vous lancez Invisibilité sur vous-même.
88-92 : rien ne se passe au point choisi ; un flot de 1d4 × 10 gemmes de 1 po jaillit de la baguette en une ligne de 9 m sur 1,50 m vers le point. Chaque gemme inflige 1 dégât contondant, le total étant réparti équitablement entre les créatures dans la ligne.
93-97 : vous lancez Métamorphose sur la créature la plus proche du point (d4 : 1 ours noir, 2 guêpe géante, 3-4 grenouille).
98-00 : la créature la plus proche du point effectue un JS de Constitution DD 15. En cas d'échec, elle est entravée et commence à se pétrifier ; elle répète le jet à la fin de son prochain tour : en cas de réussite l'effet cesse, en cas d'échec elle est pétrifiée jusqu'à ce qu'un sort Restauration supérieure ou une magie similaire la libère.$t$),
  ($t$Arme d'alerte$t$, $t$Weapon of Warning$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que cette arme est à votre portée et que vous y êtes harmonisé, vous et vos alliés à 9 m ou moins bénéficiez de ces avantages :
Alarme. L'arme réveille par magie chaque sujet qui dort naturellement quand un combat commence (pas ceux plongés dans un sommeil magique).
Vigilance surnaturelle. Chaque sujet a l'avantage à ses jets d'initiative.$t$),
  ($t$Arme +1$t$, $t$Weapon, +1$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous bénéficiez d'un bonus de +1 aux jets d'attaque et de dégâts effectués avec cette arme magique (le bonus dépend de sa rareté).$t$),
  ($t$Arme +2$t$, $t$Weapon, +2$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous bénéficiez d'un bonus de +2 aux jets d'attaque et de dégâts effectués avec cette arme magique (le bonus dépend de sa rareté).$t$),
  ($t$Arme +3$t$, $t$Weapon, +3$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous bénéficiez d'un bonus de +3 aux jets d'attaque et de dégâts effectués avec cette arme magique (le bonus dépend de sa rareté).$t$),
  ($t$Puits des mondes$t$, $t$Well of Many Worlds$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce fin tissu noir, doux comme la soie, est plié à la taille d'un mouchoir et se déplie en un disque de 1,80 m de diamètre. Par une action Magie, vous pouvez le déplier et le poser sur une surface solide : il forme un portail circulaire à double sens de 1,80 m de diamètre vers un autre monde ou un autre plan, que le MJ choisit à chaque ouverture. Le portail reste ouvert jusqu'à ce qu'une créature à 1,50 m ou moins le referme par une action Magie en saisissant les bords du tissu et en le repliant. Une fois un portail ouvert, l'objet ne peut plus en ouvrir pendant 1d8 heures.$t$),
  ($t$Éventail du vent$t$, $t$Wind Fan$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous tenez cet éventail, vous pouvez lancer Bourrasque (DD 13) avec lui. Chaque utilisation suivante avant l'aube suivante a 20 % de chances cumulatives d'échouer ; en cas d'échec, l'éventail se déchire en lambeaux inutiles et non magiques.$t$),
  ($t$Bottes ailées$t$, $t$Winged Boots$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ces bottes possèdent 4 charges et en récupèrent 1d4 chaque jour à l'aube. Tant que vous les portez, vous pouvez effectuer une action Magie et dépenser 1 charge pour obtenir une vitesse de vol de 9 m pendant 1 heure. Si vous volez quand l'effet prend fin, vous descendez de 9 m par round jusqu'à toucher le sol.$t$),
  ($t$Ailes de vol$t$, $t$Wings of Flying$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez cette cape, vous pouvez effectuer une action Magie pour la transformer en une paire d'ailes dans votre dos, pendant 1 heure ou jusqu'à ce que vous y mettiez fin par une action Magie. Les ailes vous confèrent une vitesse de vol de 18 m. Si vous êtes en l'air quand elles disparaissent, vous tombez. Une fois disparues, elles ne sont plus utilisables pendant 1d12 heures.$t$),
  ($t$Potion de soins$t$, $t$Potion of Healing$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Commun à très rare$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Quand vous buvez cette potion, vous récupérez des points de vie selon sa rareté : potion de soins (commune) 2d4 + 2 ; potion de soins supérieurs (peu commune) 4d4 + 4 ; potion de soins intenses (rare) 8d4 + 8 ; potion de soins suprêmes (très rare) 10d4 + 20. Quelle que soit sa puissance, son liquide rouge scintille quand on l'agite.$t$),
  ($t$Potion de force de géant$t$, $t$Potion of Giant Strength$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun à légendaire$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Quand vous buvez cette potion, votre Force passe pendant 1 heure à une valeur qui dépend du type de géant (aucun effet si votre Force est déjà égale ou supérieure) : géant des collines For 21 (peu commune) ; géant du givre ou des pierres For 23 (rare) ; géant du feu For 25 (rare) ; géant des nuages For 27 (très rare) ; géant des tempêtes For 29 (légendaire). Un minuscule fragment d'ongle d'un géant du type correspondant flotte dans son liquide transparent.$t$),
  ($t$Parchemin de sort$t$, $t$Spell Scroll$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Commun à légendaire$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Un parchemin de sort contient les mots d'un sort, écrits dans un code mystique. Si le sort figure sur votre liste de sorts, vous pouvez le lire et le lancer sans composante matérielle ; sinon, le parchemin est illisible. Le lancer depuis le parchemin prend le temps d'incantation normal du sort. Une fois le sort lancé, le parchemin tombe en poussière ; si l'incantation est interrompue, il n'est pas perdu.
Si le sort est d'un niveau supérieur à celui que vous pouvez normalement lancer, vous devez réussir un test d'Intelligence (Arcanes) DD 10 + niveau du sort ; en cas d'échec, le sort disparaît du parchemin sans effet.
Le niveau du sort détermine sa rareté, son DD de sauvegarde et son bonus d'attaque : sort mineur ou niveau 1 commun (DD 13, +5) ; niveau 2 peu commun (DD 13, +5) ; niveau 3 peu commun (DD 15, +7) ; niveau 4-5 rare (DD 15-17, +7-9) ; niveau 6-8 très rare (DD 17-18, +9-10) ; niveau 9 légendaire (DD 19, +11). Un magicien peut copier le sort d'un parchemin dans son grimoire.$t$),
  ($t$Pierre de Ioun$t$, $t$Ioun Stone$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare à légendaire$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Une pierre de Ioun porte le nom d'une ancienne divinité du savoir. Il en existe de nombreux types, chacun d'une forme et d'une couleur distinctes. Par une action Utiliser, vous pouvez lancer la pierre en l'air : elle se met à graviter à 30 cm de votre tête et vous confère son avantage. Une créature peut ensuite la saisir ou la faire tomber (attaque ou test d'Acrobaties/Athlétisme contre la CA 24 de la pierre) ; vous pouvez la reprendre par une action Utiliser. La pierre a CA 24, 10 PV et la résistance à tous les dégâts.
Types courants : Absorption (neutralise les sorts de niveau 4 ou inférieur qui vous visent, jusqu'à 20 niveaux), Agilité (+2 Dextérité, max. 20), Réserve (stocke des sorts), Vivacité (avantage à l'initiative et +1 à la vitesse), Intellect (+2 Intelligence), Perspicacité (+2 Sagesse), Protection (+1 CA), Régénération (15 PV par heure), Résilience (+2 Constitution), Force (+2 Force), Leadership (+2 Charisme), Maîtrise (+1 bonus de maîtrise, légendaire), Nourriture (dispense de boire et manger).$t$)
    ) as t(name_fr, name_en, category, weight, cost, rarity, attunement, consumable, source, description)
  loop
    if not exists (
      select 1 from public.translations tr
       where tr.entity_type = 'item' and tr.field_name = 'name' and tr.locale = 'fr'
         and lower(tr.value) = lower(rec.name_fr)
    ) then
      insert into public.items (category, weight, cost, source, rarity, requires_attunement, consumable)
        values (rec.category, rec.weight, rec.cost, rec.source, rec.rarity, rec.attunement, rec.consumable)
        returning id into v_id;
      insert into public.translations (entity_type, entity_id, field_name, locale, value) values
        ('item', v_id::text, 'name', 'fr', rec.name_fr),
        ('item', v_id::text, 'name', 'en', rec.name_en),
        ('item', v_id::text, 'description', 'fr', rec.description);
      v_inserted := v_inserted + 1;
    end if;
  end loop;
  raise notice 'objets insérés : %', v_inserted;
end $$;

