-- Partie 1/3 : objets magiques A à Necklace of Adaptation.
-- Contenu D&D — lot 2 : équipement et objets magiques du SRD 5.2 (règles 2024).
--
-- Ajoute 250 objets magiques (entrées du livre : les variantes par arme ou par
-- armure de l'API Open5e sont regroupées, ex. « Arme +1 », « Langue de feu ») et
-- 103 objets ordinaires absents de la base (matériel d'aventurier, munitions,
-- outils, montures, véhicules, mousquet et pistolet). Textes traduits en français
-- (poids convertis en kg, distances en mètres) ; le nom anglais est ajouté en
-- locale « en » pour faciliter les rapprochements futurs.
--
-- Source : Open5e API v2, documents srd-2024 (items, magicitems), récupérés le
-- 2026-09-30.
--
-- Licence : ce contenu inclut des éléments du System Reference Document 5.2
-- (« SRD 5.2 ») de Wizards of the Coast LLC, disponible sur
-- https://www.dndbeyond.com/srd. Le SRD 5.2 est placé sous licence Creative
-- Commons Attribution 4.0 International (https://creativecommons.org/licenses/by/4.0/legalcode).
--
-- Idempotente : un objet dont le nom FR existe déjà n'est pas réinséré.

do $$
declare
  rec record;
  v_id int;
  v_inserted int := 0;
begin
  for rec in
    select * from (values
  ($t$Armure d'adamantium$t$, $t$Adamantine Armor$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette armure est renforcée d'adamantium, l'une des substances les plus dures qui existent. Tant que vous la portez, tout coup critique qui vous est porté devient un coup normal.$t$),
  ($t$Munition tueuse$t$, $t$Ammunition of Slaying$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette munition magique est destinée à tuer les créatures d'un type particulier, choisi par le MJ ou déterminé aléatoirement sur la table ci-dessous. Si une créature de ce type subit des dégâts de la munition, elle effectue un jet de sauvegarde de Constitution DD 17 ; elle subit 6d10 dégâts de force supplémentaires en cas d'échec, ou la moitié de ces dégâts supplémentaires en cas de réussite.
Après avoir infligé ses dégâts supplémentaires à une créature, la munition perd sa magie.
d100 — Type de créature : 01-10 Aberrations ; 11-15 Bêtes ; 16-20 Célestes ; 21-25 Artificiels ; 26-35 Dragons ; 36-45 Élémentaires ; 46-50 Humanoïdes ; 51-60 Fées ; 61-70 Fiélons ; 71-75 Géants ; 76-80 Créatures monstrueuses ; 81-85 Vases ; 86-90 Plantes ; 91-00 Morts-vivants.$t$),
  ($t$Munition +1$t$, $t$Ammunition, +1$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous bénéficiez d'un bonus aux jets d'attaque et de dégâts effectués avec cette munition magique ; ce bonus dépend de sa rareté (+1 pour peu commun). Une fois qu'elle a touché une cible, la munition perd sa magie. On la trouve ou on l'achète généralement par lots de dix ou vingt. Dix munitions valent autant qu'une potion de même rareté.$t$),
  ($t$Munition +2$t$, $t$Ammunition, +2$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous bénéficiez d'un bonus aux jets d'attaque et de dégâts effectués avec cette munition magique ; ce bonus dépend de sa rareté (+2 pour rare). Une fois qu'elle a touché une cible, la munition perd sa magie. On la trouve ou on l'achète généralement par lots de dix ou vingt. Dix munitions valent autant qu'une potion de même rareté.$t$),
  ($t$Munition +3$t$, $t$Ammunition, +3$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous bénéficiez d'un bonus aux jets d'attaque et de dégâts effectués avec cette munition magique ; ce bonus dépend de sa rareté (+3 pour très rare). Une fois qu'elle a touché une cible, la munition perd sa magie. On la trouve ou on l'achète généralement par lots de dix ou vingt. Dix munitions valent autant qu'une potion de même rareté.$t$),
  ($t$Amulette de santé$t$, $t$Amulet of Health$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Votre Constitution est de 19 tant que vous portez cette amulette. Elle n'a aucun effet si votre Constitution est déjà de 19 ou plus sans elle.$t$),
  ($t$Amulette d'antidétection$t$, $t$Amulet of Proof against Detection and Location$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez cette amulette, vous ne pouvez pas être ciblé par des sorts de divination ni être perçu par des capteurs de scrutation magiques, à moins que vous ne l'autorisiez.$t$),
  ($t$Amulette des plans$t$, $t$Amulet of the Planes$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez cette amulette, vous pouvez effectuer une action Magie pour nommer un lieu que vous connaissez sur un autre plan d'existence, puis faire un test d'Intelligence (Arcanes) DD 15. En cas de réussite, vous lancez Changement de plan. En cas d'échec, vous et chaque créature et objet dans un rayon de 4,50 m autour de vous êtes transportés vers une destination aléatoire (d100) :
01-60 : lieu aléatoire du plan nommé.
61-70 : lieu aléatoire d'un plan intérieur (d6) — 1 plan de l'Air, 2 plan de la Terre, 3 plan du Feu, 4 plan de l'Eau, 5 Féerie, 6 Gisombre.
71-80 : lieu aléatoire d'un plan extérieur (d8) — 1 Arborée, 2 Arcadie, 3 Terres des bêtes, 4 Bytopie, 5 Élysée, 6 Méchanus, 7 Mont Céleste, 8 Ysgard.
81-90 : lieu aléatoire d'un plan extérieur (d8) — 1 Abysses, 2 Achéron, 3 Carcères, 4 Géhenne, 5 Hadès, 6 Limbes, 7 Neuf Enfers, 8 Pandémonium.
91-00 : lieu aléatoire du plan Astral.$t$),
  ($t$Bouclier animé$t$, $t$Animated Shield$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous tenez ce bouclier, vous pouvez effectuer une action bonus pour l'animer. Il s'élève dans les airs et flotte dans votre espace pour vous protéger comme si vous le maniiez, vous laissant les mains libres. Il reste animé pendant 1 minute, jusqu'à ce que vous mettiez fin à l'effet par une action bonus, ou jusqu'à votre mort ou jusqu'à ce que vous subissiez l'état neutralisé ; il tombe alors au sol, ou dans votre main si vous en avez une de libre.$t$),
  ($t$Appareil de Kwalish$t$, $t$Apparatus of the Crab$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cet objet ressemble d'abord à un tonneau de fer scellé pesant 250 kg. Il comporte un loquet caché, qu'on peut trouver en réussissant un test d'Intelligence (Investigation) DD 20. Le libérer ouvre une trappe à une extrémité, par laquelle deux créatures de taille M ou inférieure peuvent se glisser à l'intérieur. Dix leviers alignés au fond, en position neutre, peuvent être poussés vers le haut ou vers le bas. Certains transforment l'appareil en une sorte de homard géant.
L'appareil est un objet de taille G : CA 20 ; 200 PV ; vitesse 9 m, nage 9 m (0 m si les pattes ne sont pas déployées) ; immunité aux dégâts de poison et psychiques.
Il faut un pilote pour le conduire. Trappe fermée, l'habitacle est étanche à l'air et à l'eau et contient assez d'air pour 10 heures de respiration, divisées par le nombre de créatures qui respirent à l'intérieur. L'appareil flotte et peut plonger jusqu'à 270 m de profondeur ; au-delà, il subit 2d6 dégâts contondants par minute à cause de la pression.
Une créature dans l'habitacle peut effectuer une action Utiliser pour actionner jusqu'à deux leviers ; chacun revient ensuite en position neutre. Leviers, de gauche à droite (haut / bas) :
1 : les pattes se déploient, l'appareil peut marcher et nager / les pattes se rétractent, vitesses réduites à 0.
2 : le volet de la fenêtre avant s'ouvre / se ferme.
3 : les volets latéraux (deux de chaque côté) s'ouvrent / se ferment.
4 : deux pinces sortent à l'avant / les pinces se rétractent.
5 : chaque pince déployée attaque au corps à corps (+8 au toucher, allonge 1,50 m, 7 (2d6) dégâts contondants) / chaque pince attaque (+8 au toucher, allonge 1,50 m, la cible est empoignée, évasion DD 15).
6 : l'appareil avance (pattes déployées) / recule.
7 : pivote de 90° vers la gauche / vers la droite.
8 : des « yeux » émettent une lumière vive sur 9 m et faible sur 9 m de plus / la lumière s'éteint.
9 : l'appareil s'enfonce de 6 m dans un liquide / remonte de 6 m.
10 : la trappe arrière s'ouvre / se ferme hermétiquement.$t$),
  ($t$Armure éthérée$t$, $t$Armor of Etherealness$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez cette armure, vous pouvez effectuer une action Magie et prononcer un mot de commande pour obtenir l'effet du sort Forme éthérée. Le sort prend fin immédiatement si vous retirez l'armure ou répétez le mot de commande par une action Magie. Cette propriété n'est plus utilisable avant l'aube suivante.$t$),
  ($t$Armure d'invulnérabilité$t$, $t$Armor of Invulnerability$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous avez la résistance aux dégâts contondants, perforants et tranchants tant que vous portez cette armure.
Carapace de métal. Par une action Magie, vous obtenez l'immunité aux dégâts contondants, perforants et tranchants pendant 10 minutes ou jusqu'à ce que vous ne portiez plus l'armure. Cette propriété n'est plus utilisable avant l'aube suivante.$t$),
  ($t$Armure de résistance$t$, $t$Armor of Resistance$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous avez la résistance à un type de dégâts tant que vous portez cette armure. Le MJ choisit le type ou le détermine au hasard (d10) : 1 acide, 2 froid, 3 feu, 4 force, 5 foudre, 6 nécrotique, 7 poison, 8 psychique, 9 radiant, 10 tonnerre.$t$),
  ($t$Armure de vulnérabilité$t$, $t$Armor of Vulnerability$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez cette armure, vous avez la résistance à l'un de ces types de dégâts : contondants, perforants ou tranchants (choisi par le MJ ou au hasard).
Malédiction. L'armure est maudite, ce qui ne se révèle que si le sort Identification est lancé sur elle ou si vous vous y harmonisez. L'harmonisation vous maudit jusqu'à ce que vous soyez ciblé par Délivrance des malédictions ou une magie similaire ; retirer l'armure ne met pas fin à la malédiction. Tant que vous êtes maudit, vous êtes vulnérable aux deux autres types de dégâts associés à l'armure (pas celui auquel elle vous rend résistant).$t$),
  ($t$Armure +1$t$, $t$Armor, +1$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous bénéficiez d'un bonus de +1 à la Classe d'Armure tant que vous portez cette armure (le bonus dépend de sa rareté).$t$),
  ($t$Armure +2$t$, $t$Armor, +2$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous bénéficiez d'un bonus de +2 à la Classe d'Armure tant que vous portez cette armure (le bonus dépend de sa rareté).$t$),
  ($t$Armure +3$t$, $t$Armor, +3$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous bénéficiez d'un bonus de +3 à la Classe d'Armure tant que vous portez cette armure (le bonus dépend de sa rareté).$t$),
  ($t$Bouclier attrape-flèches$t$, $t$Arrow-Catching Shield$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous maniez ce bouclier, vous bénéficiez d'un bonus de +2 à la CA contre les jets d'attaque à distance, en plus du bonus normal du bouclier. Chaque fois qu'un attaquant effectue un jet d'attaque à distance contre une cible située à 1,50 m ou moins de vous, vous pouvez utiliser votre réaction pour devenir la cible de l'attaque à sa place.$t$),
  ($t$Sac à haricots$t$, $t$Bag of Beans$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce lourd sac de tissu contient 3d4 haricots secs quand on le trouve. Il pèse 250 g quel que soit le nombre de haricots, et devient un objet non magique quand il est vide.
Si vous videz un ou plusieurs haricots hors du sac, ils explosent dans une sphère de 3 m de rayon centrée sur eux. Les haricots sont détruits et chaque créature dans la sphère, vous compris, effectue un jet de sauvegarde de Dextérité DD 15 ; elle subit 5d4 dégâts de force en cas d'échec, ou la moitié en cas de réussite.
Si vous sortez un haricot, le plantez dans la terre ou le sable puis l'arrosez, il disparaît et produit un effet 1 minute plus tard à cet endroit (au choix du MJ ou au hasard, d100) :
01 : 5d4 champignons poussent. Une créature qui en mange lance un dé : sur un résultat impair, elle doit réussir un JS de Constitution DD 15 ou subir 5d6 dégâts de poison et être empoisonnée 1 heure ; sur un résultat pair, elle gagne 5d6 points de vie temporaires pendant 1 heure.
02-10 : un geyser projette de l'eau, de la bière, de la mayonnaise, du thé, du vinaigre, du vin ou de l'huile (au choix du MJ) à 9 m de haut pendant 1d4 minutes.
11-20 : un sylvanien pousse ; lancez un dé : impair, il est chaotique mauvais ; pair, chaotique bon.
21-30 : une statue de pierre animée mais immobile à votre effigie se dresse et vous menace. Si vous partez et que d'autres approchent, elle vous décrit comme le pire des scélérats et les pousse à vous traquer. Tant que vous êtes sur le même plan, elle sait où vous êtes. Elle devient inanimée après 24 heures.
31-40 : un feu de camp aux flammes vertes brûle 24 heures ou jusqu'à ce qu'on l'éteigne.
41-50 : trois criards poussent.
51-60 : 1d4 + 4 crapauds rose vif surgissent. Quand on touche un crapaud, il se transforme en un monstre de taille G ou inférieure au choix du MJ, qui agit selon sa nature, pendant 1 minute, puis disparaît dans un nuage de fumée rose.
61-70 : une bulette affamée surgit du sol et attaque.
71-80 : un arbre fruitier pousse, portant 1d10 + 20 fruits dont 1d8 agissent comme des potions déterminées au hasard. L'arbre disparaît après 1 heure ; les fruits cueillis gardent leur magie 30 jours.
81-90 : un nid de 1d4 + 3 œufs arc-en-ciel apparaît. Une créature qui en mange un effectue un JS de Constitution DD 20 : en cas de réussite, sa valeur de caractéristique la plus basse augmente définitivement de 1 ; en cas d'échec, elle subit 10d6 dégâts de force.
91-95 : une pyramide de 18 m de côté jaillit du sol. Elle abrite une chambre funéraire contenant une momie, un seigneur momie ou un autre mort-vivant au choix du MJ, et un trésor dans son sarcophage.
96-00 : un haricot géant pousse jusqu'à une hauteur choisie par le MJ ; son sommet mène où le MJ le souhaite (un point de vue, le château d'un géant des nuages, un autre plan…).$t$),
  ($t$Sac dévoreur$t$, $t$Bag of Devouring$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce sac ressemble à un sac sans fond, mais c'est en réalité l'orifice nourricier d'une gigantesque créature extradimensionnelle ; le retourner ferme l'orifice. La créature perçoit tout ce qu'on place dans le sac. Toute matière animale ou végétale entièrement placée dedans est dévorée et perdue à jamais. Quand une partie d'une créature vivante y est introduite (en y plongeant la main, par exemple), il y a 50 % de chances que la créature soit aspirée à l'intérieur. Une créature dans le sac peut effectuer une action pour tenter de s'échapper, avec un test de Force (Athlétisme) DD 15. Une autre créature peut effectuer une action pour l'en tirer avec un test de Force (Athlétisme) DD 20, si elle n'est pas aspirée d'abord. Toute créature qui commence son tour dans le sac est dévorée et son corps détruit.
Le sac peut contenir jusqu'à 30 dm³ d'objets inanimés, mais une fois par jour il les avale et les recrache sur un autre plan d'existence (moment et plan choisis par le MJ). Si le sac est percé ou déchiré, il est détruit et son contenu est transporté en un lieu aléatoire du plan Astral.$t$),
  ($t$Sac sans fond$t$, $t$Bag of Holding$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce sac est bien plus grand à l'intérieur qu'à l'extérieur : environ 60 cm de côté et 1,20 m de profondeur. Il peut contenir jusqu'à 250 kg, dans un volume maximal de 1,8 m³, et pèse 2,5 kg quel que soit son contenu. Récupérer un objet dans le sac demande une action Utiliser.
S'il est surchargé, percé ou déchiré, le sac est détruit et son contenu dispersé dans le plan Astral. Retourné, il répand son contenu sans dommage, mais doit être remis à l'endroit avant de resservir. Il contient assez d'air pour 10 minutes de respiration, divisées par le nombre de créatures qui respirent à l'intérieur.
Placer un sac sans fond dans un espace extradimensionnel créé par un havresac magique, un trou portatif ou un objet similaire détruit instantanément les deux objets et ouvre un portail vers le plan Astral, là où l'un a été placé dans l'autre. Toute créature dans une sphère de 3 m de rayon centrée sur le portail est aspirée vers un lieu aléatoire du plan Astral, puis le portail se referme. Il est à sens unique et ne peut pas être rouvert.$t$),
  ($t$Sac à malice$t$, $t$Bag of Tricks$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce sac de tissu gris, rouille ou beige semble vide, mais en y plongeant la main on sent un petit objet duveteux.
Par une action Magie, vous pouvez sortir l'objet et le lancer jusqu'à 6 m. En touchant le sol, il se transforme en une créature déterminée sur la table correspondant à la couleur du sac. Elle disparaît à l'aube suivante ou quand elle tombe à 0 point de vie.
La créature est amicale envers vous et vos alliés et agit juste après vous dans l'ordre d'initiative. Par une action bonus, vous pouvez lui indiquer comment se déplacer et quelle action effectuer à son prochain tour ; sinon, elle agit selon sa nature.
Une fois trois objets sortis, le sac n'est plus utilisable avant l'aube suivante.
Sac gris (d8) : 1 belette, 2 rat géant, 3 blaireau, 4 sanglier, 5 panthère, 6 blaireau géant, 7 loup sanguinaire, 8 élan géant.
Sac rouille (d8) : 1 rat, 2 chouette, 3 molosse, 4 chèvre, 5 chèvre géante, 6 sanglier géant, 7 lion, 8 ours brun.
Sac beige (d8) : 1 chacal, 2 singe, 3 babouin, 4 bec de hache, 5 ours noir, 6 belette géante, 7 hyène géante, 8 tigre.$t$),
  ($t$Perle de force$t$, $t$Bead of Force$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette petite sphère noire de 2 cm de diamètre pèse une trentaine de grammes. On en trouve généralement 1d4 + 4 ensemble. Par une action Magie, vous pouvez lancer la perle jusqu'à 18 m. Elle explose à l'impact dans une sphère de 3 m de rayon et est détruite. Chaque créature dans la sphère doit réussir un JS de Dextérité DD 15 ou subir 5d4 dégâts de force. Une sphère de force transparente enferme ensuite la zone pendant 1 minute : toute créature qui a raté son jet et se trouve entièrement dans la zone est piégée à l'intérieur ; celles qui ont réussi ou ne sont que partiellement dans la zone sont repoussées hors de la sphère.
Seul l'air respirable traverse la paroi ; aucune attaque ni aucun autre effet ne la franchit. Une créature enfermée peut effectuer une action Utiliser pour pousser la paroi et déplacer la sphère de la moitié de sa vitesse. La sphère peut être soulevée et ne pèse que 500 g, quel que soit le poids des créatures à l'intérieur.$t$),
  ($t$Ceinturon des nains$t$, $t$Belt of Dwarvenkind$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez ce ceinturon, vous bénéficiez de ces avantages :
Nain. Vous connaissez le nain.
Ami des nains. Vous avez l'avantage aux tests de Charisme (Persuasion) pour interagir avec les nains et les duergars.
Robustesse. Votre Constitution augmente de 2, jusqu'à un maximum de 20.
De plus, tant que vous y êtes harmonisé, vous avez chaque jour à l'aube 50 % de chances de voir pousser une barbe fournie si vous le pouvez, ou de l'épaissir si vous en avez déjà une.
Si vous n'êtes ni nain ni duergar, vous gagnez aussi :
Vision dans le noir. Vous avez la vision dans le noir sur 18 m.
Résilience. Vous avez la résistance aux dégâts de poison et l'avantage aux jets de sauvegarde pour éviter ou terminer l'état empoisonné.$t$),
  ($t$Ceinturon de force de géant$t$, $t$Belt of Giant Strength$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare à légendaire$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez ce ceinturon, votre Force passe à la valeur accordée par le ceinturon, selon le type de géant. Il n'a aucun effet si votre Force sans lui est déjà égale ou supérieure.
Géant des collines : For 21 (rare). Géant du givre ou des pierres : For 23 (très rare). Géant du feu : For 25 (très rare). Géant des nuages : For 27 (légendaire). Géant des tempêtes : For 29 (légendaire).$t$),
  ($t$Hache du berserker$t$, $t$Berserker Axe$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous bénéficiez d'un bonus de +1 aux jets d'attaque et de dégâts effectués avec cette arme magique. De plus, tant que vous y êtes harmonisé, votre maximum de points de vie augmente de 1 par niveau que vous avez atteint.
Malédiction. L'arme est maudite et l'harmonisation étend la malédiction à vous. Tant que vous êtes maudit, vous refusez de vous en séparer et la gardez toujours à portée de main. Vous avez le désavantage aux jets d'attaque avec toute autre arme. Chaque fois qu'une autre créature vous inflige des dégâts alors que vous possédez l'arme, vous devez réussir un JS de Sagesse DD 15 ou entrer en furie. La furie prend fin quand vous commencez votre tour sans aucune créature visible ou audible à 18 m ou moins. En furie, vous considérez la créature la plus proche que vous voyez ou entendez comme votre ennemie (au hasard en cas d'égalité) ; à chacun de vos tours, vous devez vous en approcher le plus possible et effectuer l'action Attaquer contre elle. Si vous ne pouvez pas l'atteindre, votre tour s'arrête une fois votre déplacement épuisé. Si elle meurt ou disparaît de vos sens, la créature suivante la plus proche devient votre cible.$t$),
  ($t$Bottes elfiques$t$, $t$Boots of Elvenkind$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez ces bottes, vos pas ne font aucun bruit, quelle que soit la surface. Vous avez aussi l'avantage aux tests de Dextérité (Discrétion).$t$),
  ($t$Bottes de lévitation$t$, $t$Boots of Levitation$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez ces bottes, vous pouvez lancer Lévitation sur vous-même.$t$),
  ($t$Bottes de rapidité$t$, $t$Boots of Speed$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez ces bottes, vous pouvez effectuer une action bonus pour claquer des talons. Votre vitesse est alors doublée et toute créature qui vous porte une attaque d'opportunité a le désavantage au jet d'attaque. Claquer à nouveau des talons met fin à l'effet. Après un total de 10 minutes d'utilisation, la magie cesse de fonctionner pour vous jusqu'à ce que vous terminiez un repos long.$t$),
  ($t$Bottes de sept lieues$t$, $t$Boots of Striding and Springing$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez ces bottes, votre vitesse devient 9 m, à moins qu'elle ne soit supérieure, et elle n'est réduite ni par une charge dépassant votre capacité de charge ni par le port d'une armure lourde. Une fois à chacun de vos tours, vous pouvez sauter jusqu'à 9 m en ne dépensant que 3 m de déplacement.$t$),
  ($t$Bottes des terres gelées$t$, $t$Boots of the Winterlands$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ces bottes fourrées sont confortables et chaudes. Tant que vous les portez, vous bénéficiez de ces avantages :
Résistance au froid. Vous avez la résistance aux dégâts de froid et supportez des températures de -18 °C ou moins sans autre protection.
Marcheur de l'hiver. Vous ignorez le terrain difficile créé par la glace ou la neige.$t$),
  ($t$Bol de contrôle des élémentaires de l'eau$t$, $t$Bowl of Commanding Water Elementals$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que ce bol est rempli d'eau et que vous êtes à 1,50 m ou moins de lui, vous pouvez effectuer une action Magie pour convoquer un élémentaire de l'eau. Il apparaît dans un espace inoccupé aussi près que possible du bol, comprend vos langues, obéit à vos ordres et agit juste après vous dans l'ordre d'initiative. Il disparaît après 1 heure, à sa mort ou quand vous le congédiez par une action bonus. Le bol n'est plus utilisable ainsi avant l'aube suivante. Il mesure environ 30 cm de diamètre, pour 15 cm de profondeur, et contient une douzaine de litres.$t$),
  ($t$Bracelets d'archerie$t$, $t$Bracers of Archery$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez ces bracelets, vous maîtrisez l'arc long et l'arc court, et vous bénéficiez d'un bonus de +2 aux jets de dégâts effectués avec ces armes.$t$),
  ($t$Bracelets de défense$t$, $t$Bracers of Defense$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez ces bracelets, vous bénéficiez d'un bonus de +2 à la CA si vous ne portez pas d'armure et n'utilisez pas de bouclier.$t$),
  ($t$Brasero de contrôle des élémentaires du feu$t$, $t$Brazier of Commanding Fire Elementals$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous êtes à 1,50 m ou moins de ce brasero, vous pouvez effectuer une action Magie pour convoquer un élémentaire du feu. Il apparaît dans un espace inoccupé aussi près que possible du brasero, comprend vos langues, obéit à vos ordres et agit juste après vous dans l'ordre d'initiative. Il disparaît après 1 heure, à sa mort ou quand vous le congédiez par une action bonus. Le brasero n'est plus utilisable ainsi avant l'aube suivante.$t$),
  ($t$Broche de défense$t$, $t$Brooch of Shielding$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez cette broche, vous avez la résistance aux dégâts de force et l'immunité aux dégâts du sort Projectile magique.$t$),
  ($t$Balai volant$t$, $t$Broom of Flying$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce balai de bois fonctionne comme un balai ordinaire jusqu'à ce que vous l'enfourchiez et effectuiez une action Magie pour le faire flotter sous vous ; on peut alors le chevaucher dans les airs. Il a une vitesse de vol de 15 m et peut porter jusqu'à 200 kg, mais sa vitesse de vol tombe à 9 m au-delà de 100 kg. Il cesse de flotter quand vous atterrissez ou ne le chevauchez plus.
Par une action Magie, vous pouvez l'envoyer seul vers une destination à 1,5 km ou moins que vous nommez et connaissez. Il revient vers vous quand vous effectuez une action Magie et prononcez un mot de commande, s'il se trouve encore à 1,5 km ou moins.$t$),
  ($t$Cierge d'invocation$t$, $t$Candle of Invocation$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$La magie de ce cierge s'active quand on l'allume, ce qui demande une action Magie. Après 4 heures de combustion, il est détruit ; vous pouvez l'éteindre plus tôt pour le réutiliser plus tard (déduisez la durée écoulée, par tranches de 1 minute).
Allumé, il diffuse une lumière faible dans un rayon de 9 m. Tant que vous êtes dans cette lumière, vous avez l'avantage aux tests de d20. De plus, un clerc ou un druide dans la lumière peut lancer les sorts de niveau 1 qu'il a préparés sans dépenser d'emplacement.
Au lieu de cela, lors de sa première utilisation, vous pouvez lancer Portail avec le cierge, ce qui le détruit. Le portail mène à un plan extérieur choisi par le MJ ou déterminé au hasard (d100) : 01-05 Abysses, 06-10 Achéron, 11-17 Arborée, 18-25 Arcadie, 26-33 Terres des bêtes, 34-41 Bytopie, 42-46 Carcères, 47-54 Élysée, 55-59 Géhenne, 60-64 Hadès, 65-69 Limbes, 70-77 Méchanus, 78-85 Mont Céleste, 86-90 Neuf Enfers, 91-95 Pandémonium, 96-00 Ysgard.$t$),
  ($t$Cape du charlatan$t$, $t$Cape of the Mountebank$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette cape sent légèrement le soufre. Tant que vous la portez, vous pouvez l'utiliser pour lancer Porte dimensionnelle par une action Magie ; cette propriété n'est plus utilisable avant l'aube suivante. Quand vous vous téléportez ainsi, vous laissez derrière vous un nuage de fumée : l'espace que vous quittez est légèrement obscurci jusqu'à la fin de votre prochain tour.$t$),
  ($t$Tapis volant$t$, $t$Carpet of Flying$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Par une action Magie et en prononçant son mot de commande, vous pouvez faire flotter et voler ce tapis. Il obéit à vos directives tant que vous êtes à 9 m ou moins de lui.
Il existe quatre tailles, choisies par le MJ ou au hasard (d100) ; un tapis peut porter jusqu'au double de sa charge normale, mais sa vitesse de vol est alors divisée par deux :
01-20 : 1 m × 1,50 m, charge 100 kg, vol 24 m.
21-55 : 1,20 m × 1,80 m, charge 200 kg, vol 18 m.
56-80 : 1,50 m × 2,10 m, charge 300 kg, vol 12 m.
81-00 : 1,80 m × 2,70 m, charge 400 kg, vol 9 m.$t$),
  ($t$Encensoir de contrôle des élémentaires de l'air$t$, $t$Censer of Controlling Air Elementals$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$En balançant doucement cet encensoir, vous pouvez effectuer une action Magie pour convoquer un élémentaire de l'air. Il apparaît dans un espace inoccupé aussi près que possible de l'encensoir, comprend vos langues, obéit à vos ordres et agit juste après vous dans l'ordre d'initiative. Il disparaît après 1 heure, à sa mort ou quand vous le congédiez par une action bonus. L'encensoir n'est plus utilisable ainsi avant l'aube suivante.$t$),
  ($t$Carillon d'ouverture$t$, $t$Chime of Opening$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce tube de métal creux mesure environ 30 cm et pèse 500 g. Par une action Magie, vous pouvez le frapper pour lancer Déblocage ; le bruit habituel du sort est remplacé par le tintement clair du carillon, audible jusqu'à 90 m. Le carillon peut servir 10 fois ; après la dixième, il se fêle et devient inutilisable.$t$),
  ($t$Diadème de destruction$t$, $t$Circlet of Blasting$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez ce diadème, vous pouvez lancer Rayon ardent avec lui (+5 au toucher). Il ne peut plus lancer ce sort avant l'aube suivante.$t$),
  ($t$Cape de l'araignée$t$, $t$Cloak of Arachnida$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce vêtement raffiné est fait de soie noire tissée de fins fils argentés. Tant que vous le portez, vous bénéficiez de ces avantages :
Résistance au poison. Vous avez la résistance aux dégâts de poison.
Pattes d'araignée. Vous avez une vitesse d'escalade égale à votre vitesse et pouvez vous déplacer sur les surfaces verticales et au plafond, les mains libres.
Marche arachnéenne. Vous ne pouvez être pris dans aucune toile et traversez les toiles comme un terrain difficile.
Toile. Vous pouvez lancer Toile d'araignée (DD 13) ; la toile couvre le double de sa zone normale. Cette propriété n'est plus utilisable avant l'aube suivante.$t$),
  ($t$Cape de déplacement$t$, $t$Cloak of Displacement$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez cette cape, elle projette une illusion qui vous fait paraître à un endroit proche de votre position réelle : toute créature a le désavantage aux jets d'attaque contre vous. Si vous subissez des dégâts, la propriété cesse de fonctionner jusqu'au début de votre prochain tour. Elle est suspendue tant que votre vitesse est de 0.$t$),
  ($t$Cape elfique$t$, $t$Cloak of Elvenkind$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez cette cape, les tests de Sagesse (Perception) pour vous percevoir ont le désavantage, et vous avez l'avantage aux tests de Dextérité (Discrétion).$t$),
  ($t$Cape de protection$t$, $t$Cloak of Protection$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous bénéficiez d'un bonus de +1 à la CA et aux jets de sauvegarde tant que vous portez cette cape.$t$),
  ($t$Cape de la chauve-souris$t$, $t$Cloak of the Bat$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez cette cape, vous avez l'avantage aux tests de Dextérité (Discrétion). Dans une zone de lumière faible ou d'obscurité, vous pouvez saisir les bords de la cape pour obtenir une vitesse de vol de 12 m ; vous la perdez si vous lâchez les bords ou quittez la lumière faible ou l'obscurité.
Dans une zone de lumière faible ou d'obscurité, vous pouvez aussi lancer Métamorphose sur vous-même pour prendre la forme d'une chauve-souris, en conservant vos valeurs d'Intelligence, de Sagesse et de Charisme. Cette utilisation n'est plus possible avant l'aube suivante.$t$),
  ($t$Cape de la raie manta$t$, $t$Cloak of the Manta Ray$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez cette cape, vous pouvez respirer sous l'eau et vous avez une vitesse de nage de 18 m.$t$),
  ($t$Boule de cristal$t$, $t$Crystal Ball$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous touchez cet orbe de cristal, vous pouvez lancer Scrutation (DD 17) avec lui.$t$),
  ($t$Boule de cristal de lecture des pensées$t$, $t$Crystal Ball of Mind Reading$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous touchez cet orbe de cristal, vous pouvez lancer Scrutation (DD 17) avec lui. Vous pouvez de plus lancer Détection des pensées (DD 17) en ciblant des créatures que vous voyez à 9 m ou moins du capteur du sort. Vous n'avez pas besoin de vous concentrer sur Détection des pensées pour le maintenir, mais il prend fin avec Scrutation.$t$),
  ($t$Boule de cristal de télépathie$t$, $t$Crystal Ball of Telepathy$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous touchez cet orbe de cristal, vous pouvez lancer Scrutation (DD 17) avec lui. Vous pouvez de plus communiquer par télépathie avec les créatures que vous voyez à 9 m ou moins du capteur du sort, et lancer Suggestion (DD 17) à travers le capteur sur l'une d'elles. Vous n'avez pas besoin de vous concentrer sur cette Suggestion, mais elle prend fin avec Scrutation. Vous ne pouvez plus lancer Suggestion ainsi avant l'aube suivante.$t$),
  ($t$Boule de cristal de vision véritable$t$, $t$Crystal Ball of True Seeing$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous touchez cet orbe de cristal, vous pouvez lancer Scrutation (DD 17) avec lui. Vous avez de plus la vision véritable sur 36 m autour du capteur du sort.$t$),
  ($t$Cube de force$t$, $t$Cube of Force$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce cube d'environ 2,5 cm de côté porte un symbole différent sur chaque face. Vous pouvez presser une face, dépenser le nombre de charges indiqué et lancer le sort correspondant (DD 17) : Armure de mage (1 charge), Bouclier (1), Petite hutte de Léomund (3), Sanctuaire privé de Mordenkainen (4), Sphère résiliente d'Otiluke (4), Mur de force (5).
Le cube possède 10 charges et en récupère 1d6 chaque jour à l'aube.$t$),
  ($t$Cube portail$t$, $t$Cubic Gate$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce cube de 7,5 cm de côté irradie une énergie magique palpable. Chacune de ses six faces est liée à un plan d'existence différent, dont l'une au plan Matériel ; les autres sont choisies par le MJ. Le cube a 3 charges et en récupère 1d3 chaque jour à l'aube. Par une action Magie, vous pouvez dépenser 1 charge pour lancer l'un de ces sorts :
Portail. En pressant une face, vous lancez Portail et ouvrez un passage vers le plan lié à cette face.
Changement de plan. En pressant deux fois une face, vous lancez Changement de plan et transportez les cibles vers le plan lié à cette face.$t$),
  ($t$Dague venimeuse$t$, $t$Dagger of Venom$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous bénéficiez d'un bonus de +1 aux jets d'attaque et de dégâts effectués avec cette arme magique. Par une action bonus, vous pouvez enduire la lame de poison. Le poison reste 1 minute ou jusqu'à ce qu'une attaque avec l'arme touche une créature. Celle-ci doit réussir un JS de Constitution DD 15 ou subir 2d10 dégâts de poison et être empoisonnée pendant 1 minute. L'arme n'est plus utilisable ainsi avant l'aube suivante.$t$),
  ($t$Épée dansante$t$, $t$Dancing Sword$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Par une action bonus, vous pouvez lancer cette arme magique en l'air. Elle se met à flotter, vole jusqu'à 9 m et attaque une créature de votre choix à 1,50 m ou moins d'elle, en utilisant votre jet d'attaque et en ajoutant votre modificateur de caractéristique aux dégâts.
Tant qu'elle flotte, vous pouvez par une action bonus la faire voler jusqu'à 9 m vers un autre point à 9 m ou moins de vous et, par la même action bonus, attaquer une créature à 1,50 m ou moins d'elle.
Après sa quatrième attaque, l'arme revient vers vous et tente de regagner votre main ; si vous n'avez pas de main libre, elle tombe dans votre espace. Si aucun chemin dégagé ne la mène à vous, elle s'approche au plus près puis tombe. Elle cesse aussi de flotter si vous la saisissez ou si vous vous éloignez à plus de 9 m d'elle.$t$),
  ($t$Carafe intarissable$t$, $t$Decanter of Endless Water$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette carafe bouchée clapote quand on la secoue, comme si elle contenait de l'eau. Elle pèse 1 kg. Par une action Magie, vous pouvez la déboucher et prononcer l'un de trois mots de commande ; de l'eau douce ou salée (au choix) s'en écoule jusqu'au début de votre prochain tour :
Éclaboussure. 4 litres d'eau.
Fontaine. 20 litres d'eau.
Geyser. 120 litres d'eau jaillissent en une ligne de 9 m de long sur 30 cm de large. Si vous tenez la carafe, vous pouvez orienter le jet (sans action). Une créature de votre choix dans la ligne doit réussir un JS de Force DD 13 ou subir 1d4 dégâts contondants et tomber à terre. À la place, vous pouvez viser un objet non porté de 100 kg ou moins, qui est renversé.$t$),
  ($t$Jeu de cartes illusoires$t$, $t$Deck of Illusions$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette boîte contient un jeu de 34 cartes : 32 représentant des créatures et deux à la surface de miroir. Un jeu trouvé en trésor est généralement incomplet de 1d20 - 1 cartes.
La magie ne fonctionne que si les cartes sont tirées au hasard. Par une action Magie, vous pouvez tirer une carte et la jeter au sol à 9 m ou moins. L'illusion d'une créature (table ci-dessous) se forme au-dessus de la carte et dure jusqu'à ce qu'on la dissipe. Elle ressemble et se comporte comme une vraie créature, mais ne peut infliger aucun dommage. Tant que vous êtes à 36 m ou moins et la voyez, vous pouvez par une action Magie la déplacer n'importe où à 9 m ou moins de sa carte.
Toute interaction physique révèle l'illusion, car les objets la traversent. Une créature qui l'examine par une action Étudier la reconnaît comme illusion en réussissant un test d'Intelligence (Investigation) DD 15. L'illusion dure jusqu'à ce que sa carte soit déplacée ou qu'elle soit dissipée (Dissipation de la magie ou effet similaire) ; l'image disparaît alors de la carte, qui devient inutilisable.
d100 : 01-03 dragon rouge adulte ; 04-06 archimage ; 07-09 assassin ; 10-12 capitaine bandit ; 13-15 basilic ; 16-18 berserker ; 19-21 guerrier gobelours ; 22-24 géant des nuages ; 25-27 druide ; 28-30 érinye ; 31-33 ettin ; 34-36 géant du feu ; 37-39 géant du givre ; 40-42 guerrier gnoll ; 43-45 guerrier gobelin ; 46-48 naga gardien ; 49-51 géant des collines ; 52-54 guerrier hobgobelin ; 55-57 incube ; 58-60 golem de fer ; 61-63 chevalier ; 64-66 guerrier kobold ; 67-69 liche ; 70-72 méduse ; 73-75 guenaude nocturne ; 76-78 ogre ; 79-81 oni ; 82-84 prêtre ; 85-87 succube ; 88-90 troll ; 91-93 guerrier vétéran ; 94-96 vouivre ; 97-00 celui qui tire la carte.$t$),
  ($t$Défenseur$t$, $t$Defender$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous bénéficiez d'un bonus de +3 aux jets d'attaque et de dégâts effectués avec cette arme magique. La première fois que vous attaquez avec elle à chacun de vos tours, vous pouvez transférer tout ou partie de ce bonus à votre CA (par exemple, réduire le bonus d'attaque et de dégâts à +1 et gagner +2 à la CA). Les bonus ajustés durent jusqu'au début de votre prochain tour ; vous devez tenir l'arme pour profiter du bonus de CA.$t$),
  ($t$Armure démoniaque$t$, $t$Demon Armor$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez cette armure, vous bénéficiez d'un bonus de +1 à la CA et vous connaissez l'abyssal. De plus, ses gantelets griffus font infliger à vos frappes à mains nues 1d8 dégâts tranchants au lieu des dégâts contondants habituels, avec un bonus de +1 aux jets d'attaque et de dégâts de ces frappes.
Malédiction. Une fois cette armure maudite enfilée, vous ne pouvez plus l'ôter à moins d'être ciblé par Délivrance des malédictions ou une magie similaire. Tant que vous la portez, vous avez le désavantage aux jets d'attaque contre les démons et aux jets de sauvegarde contre leurs sorts et capacités spéciales.$t$),
  ($t$Menottes dimensionnelles$t$, $t$Dimensional Shackles$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Par une action Utiliser, vous pouvez passer ces menottes à une créature neutralisée ; elles s'ajustent à une créature de taille P à G. Elles empêchent la créature entravée d'utiliser tout moyen de déplacement extradimensionnel, y compris la téléportation et le voyage vers un autre plan, mais pas de franchir un portail interdimensionnel. Vous et toute créature désignée lors de la pose pouvez les retirer par une action Utiliser. Une fois tous les 30 jours, la créature entravée peut faire un test de Force (Athlétisme) DD 30 ; en cas de réussite, elle se libère et détruit les menottes.$t$),
  ($t$Orbe draconique$t$, $t$Dragon Orb$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Artefact$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Un orbe est un globe de cristal gravé d'environ 25 cm de diamètre. Utilisé, il grandit jusqu'à environ 50 cm et une brume tourbillonne à l'intérieur.
Tant que vous y êtes harmonisé, vous pouvez effectuer une action Magie pour sonder ses profondeurs, puis faire un JS de Charisme DD 15. En cas de réussite, vous contrôlez l'orbe tant que vous restez harmonisé. En cas d'échec, l'orbe vous charme tant que vous restez harmonisé : vous ne pouvez pas mettre fin volontairement à l'harmonisation, et l'orbe lance Suggestion sur vous à volonté (DD 18) pour vous pousser vers ses fins maléfiques (anéantir une société, se libérer, répandre la souffrance, étendre le culte de Tiamat…).
Sorts. L'orbe a 7 charges et en récupère 1d4 + 3 chaque jour à l'aube. Si vous le contrôlez, vous pouvez lancer : Soins (version de niveau 9, 4 charges), Lumière du jour (1), Protection contre la mort (2), Détection de la magie (0), Scrutation (DD 18, 3).
Appel des dragons. Si vous le contrôlez, vous pouvez par une action Magie émettre un appel télépathique dans un rayon de 65 km. Les dragons chromatiques à portée se sentent obligés de rejoindre l'orbe au plus vite par le chemin le plus direct (les divinités draconiques comme Tiamat ne sont pas affectées). Ils peuvent vous être hostiles d'avoir été contraints. Propriété inutilisable pendant 1 heure ensuite.
Détruire un orbe. Un orbe draconique a une CA de 20 et n'est détruit que par des dégâts d'une arme +3 ou du sort Désintégration.$t$),
  ($t$Armure d'écailles de dragon$t$, $t$Dragon Scale Mail$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette armure est faite des écailles d'une espèce de dragon, parfois offertes par les dragons eux-mêmes, parfois prélevées avec soin sur un dragon mort. Elle est très prisée.
Tant que vous la portez, vous bénéficiez d'un bonus de +1 à la CA, vous avez l'avantage aux jets de sauvegarde contre les souffles des dragons et la résistance à un type de dégâts selon le dragon : noir acide, bleu foudre, airain feu, bronze foudre, cuivre acide, or feu, vert poison, rouge feu, argent froid, blanc froid.
Par une action Magie, vous pouvez aussi concentrer vos sens pour connaître la distance et la direction du dragon de même type le plus proche à 50 km ou moins. Action inutilisable avant l'aube suivante.$t$),
  ($t$Tueuse de dragons$t$, $t$Dragon Slayer$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous bénéficiez d'un bonus de +1 aux jets d'attaque et de dégâts effectués avec cette arme magique. Elle inflige 3d6 dégâts supplémentaires du type de l'arme si la cible est un dragon.$t$),
  ($t$Poudre de disparition$t$, $t$Dust of Disappearance$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette poudre ressemble à du sable fin ; il y en a pour une utilisation. Quand vous la lancez en l'air par une action Utiliser, vous et chaque créature et objet dans une émanation de 3 m autour de vous devenez invisibles pendant 2d4 minutes (même durée pour tous) ; la poudre est consommée. L'invisibilité prend fin pour une créature dès qu'elle effectue un jet d'attaque, inflige des dégâts ou lance un sort.$t$),
  ($t$Poudre dessiccative$t$, $t$Dust of Dryness$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce petit sachet contient 1d6 + 4 pincées de poudre. Par une action Utiliser, vous pouvez en saupoudrer une pincée sur de l'eau : jusqu'à un cube de 4,50 m d'eau se change en une bille de la taille d'une agate, de poids négligeable, qui flotte ou repose près de l'endroit. Une créature peut la briser contre une surface dure par une action Utiliser pour libérer l'eau absorbée, ce qui détruit la bille.
Par une action Utiliser, vous pouvez aussi saupoudrer une pincée sur un élémentaire composé principalement d'eau (comme un élémentaire de l'eau) à 1,50 m ou moins. Il effectue un JS de Constitution DD 13 : 10d6 dégâts nécrotiques en cas d'échec, la moitié en cas de réussite.$t$),
  ($t$Poudre d'éternuement et d'étouffement$t$, $t$Dust of Sneezing and Choking$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Rangée dans un petit récipient, cette poudre ressemble à de la poudre de disparition, et le sort Identification la révèle comme telle. Il y en a pour une utilisation. Par une action Utiliser, vous pouvez la lancer en l'air : vous et chaque créature dans une émanation de 9 m autour de vous effectuez un JS de Constitution DD 15 (réussite automatique pour les artificiels, élémentaires, vases, plantes et morts-vivants). En cas d'échec, la créature éternue sans pouvoir s'arrêter : elle est neutralisée et suffoque. Elle répète le jet à la fin de chacun de ses tours et met fin à l'effet en cas de réussite. L'effet cesse aussi pour une créature ciblée par Restauration partielle.$t$),
  ($t$Harnois nain$t$, $t$Dwarven Plate$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez cette armure, vous bénéficiez d'un bonus de +2 à la CA. De plus, si un effet vous déplace contre votre gré sur le sol, vous pouvez utiliser votre réaction pour réduire la distance parcourue de 3 m au maximum.$t$),
  ($t$Lanceur nain$t$, $t$Dwarven Thrower$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Harmonisation par un nain ou une créature harmonisée à un ceinturon des nains.
Vous bénéficiez d'un bonus de +3 aux jets d'attaque et de dégâts effectués avec cette arme magique. Elle a la propriété lancer (portée 6 m / 18 m). Quand vous touchez avec une attaque à distance, elle inflige 1d8 dégâts de force supplémentaires, ou 2d8 si la cible est un géant. Aussitôt après avoir touché ou raté, l'arme revient dans votre main.$t$),
  ($t$Carquois d'Ehlonna$t$, $t$Efficient Quiver$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Chacun des trois compartiments de ce carquois donne sur un espace extradimensionnel : il peut contenir de nombreux objets sans jamais peser plus de 1 kg. Le plus court contient jusqu'à 60 flèches, carreaux ou objets similaires ; le moyen jusqu'à 18 javelines ou objets similaires ; le plus long jusqu'à 6 objets longs (arcs, bâtons, lances…). Vous pouvez en tirer n'importe quel objet comme d'un carquois ou d'un fourreau ordinaire.$t$),
  ($t$Bouteille d'éfrit$t$, $t$Efreeti Bottle$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Quand vous débouchez cette bouteille de laiton peint par une action Magie, une épaisse fumée s'en échappe. À la fin de votre tour, elle disparaît dans un éclair de feu inoffensif et un éfrit apparaît dans un espace inoccupé à 9 m ou moins de vous.
À la première ouverture, le MJ lance 1d10 :
1 : l'éfrit vous attaque ; après 5 rounds de combat, il disparaît et la bouteille perd sa magie.
2-9 : l'éfrit comprend vos langues et vous obéit pendant 1 heure, puis retourne dans la bouteille, scellée par un nouveau bouchon qui ne peut être retiré pendant 24 heures. Le même effet se produit aux deux ouvertures suivantes ; à la quatrième, l'éfrit s'échappe et la bouteille perd sa magie.
10 : l'éfrit comprend vos langues et peut lancer Souhait une fois pour vous. Il disparaît une fois le souhait exaucé ou après 1 heure, et la bouteille perd sa magie.$t$),
  ($t$Gemme élémentaire$t$, $t$Elemental Gem$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette gemme renferme une parcelle d'énergie élémentaire. Quand vous la brisez par une action Utiliser, un élémentaire est convoqué et la gemme perd sa magie. Il apparaît dans un espace inoccupé aussi près que possible de la gemme, comprend vos langues, obéit à vos ordres et agit juste après vous dans l'ordre d'initiative. Il disparaît après 1 heure, à sa mort ou quand vous le congédiez par une action bonus.
Saphir bleu : élémentaire de l'air. Émeraude : élémentaire de l'eau. Corindon rouge : élémentaire du feu. Diamant jaune : élémentaire de la terre.$t$),
  ($t$Cotte de mailles elfique$t$, $t$Elven Chain$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous bénéficiez d'un bonus de +1 à la CA tant que vous portez cette armure. Vous êtes considéré comme formé à son port, même sans formation aux armures lourdes.$t$),
  ($t$Bouteille fumigène$t$, $t$Eversmoking Bottle$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Par une action Magie, vous pouvez ouvrir ou fermer cette bouteille. Ouverte, elle laisse échapper une épaisse fumée qui remplit une émanation de 18 m autour d'elle ; la zone est fortement obscurcie. Chaque minute où la bouteille reste ouverte, l'émanation grandit de 3 m, jusqu'à 36 m. Fermer la bouteille fige le nuage, qui se dissipe après 10 minutes. Un vent fort (comme celui du sort Bourrasque) le disperse en 1 minute.$t$),
  ($t$Lentilles de charme$t$, $t$Eyes of Charming$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ces lentilles de cristal se posent sur les yeux. Elles ont 3 charges. Tant que vous les portez, vous pouvez dépenser 1 charge ou plus pour lancer Charme-personne (DD 13) : 1 charge pour la version de niveau 1, et un niveau de plus par charge supplémentaire. Elles récupèrent toutes leurs charges chaque jour à l'aube.$t$),
  ($t$Lentilles de vision minutieuse$t$, $t$Eyes of Minute Seeing$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ces lentilles de cristal se posent sur les yeux. Tant que vous les portez, votre vision s'améliore nettement jusqu'à 30 cm : vous avez la vision dans le noir à cette portée et l'avantage aux tests d'Intelligence (Investigation) pour examiner quelque chose à cette distance.$t$),
  ($t$Lentilles d'aigle$t$, $t$Eyes of the Eagle$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ces lentilles de cristal se posent sur les yeux. Tant que vous les portez, vous avez l'avantage aux tests de Sagesse (Perception) basés sur la vue. Par bonne visibilité, vous distinguez les détails de créatures et d'objets même très éloignés, jusqu'à 60 cm de large.$t$),
  ($t$Plume de Quaal$t$, $t$Feather Token$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun à rare$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cet objet ressemble à une plume. Il en existe plusieurs sortes, chacune à usage unique ; le MJ choisit le type ou le détermine au hasard (d100), ce qui fixe sa rareté :
01-20 Ancre (peu commune). Par une action Magie, vous touchez un bateau avec la plume : pendant 24 heures, il ne peut être déplacé par aucun moyen. Le toucher à nouveau met fin à l'effet ; la plume disparaît alors.
21-35 Oiseau (rare). Par une action Magie, vous lancez la plume à 1,50 m en l'air : elle disparaît et un immense oiseau multicolore prend sa place. Il a les statistiques d'un roc mais ne peut pas attaquer ; il obéit à vos ordres simples et peut porter 250 kg à vitesse maximale (25 km/h, 230 km par jour au plus, avec 1 heure de repos toutes les 3 heures de vol) ou 500 kg à mi-vitesse. Il disparaît après sa distance maximale quotidienne ou à 0 point de vie ; vous pouvez le congédier par une action Magie.
36-50 Éventail (peu commune). Sur un bateau, par une action Magie, vous lancez la plume jusqu'à 3 m en l'air : un éventail géant apparaît et crée un vent fort qui gonfle les voiles d'un navire, augmentant sa vitesse de 8 km/h pendant 8 heures. Vous pouvez le congédier par une action Magie.
51-65 Bateau-cygne (rare). Par une action Magie, vous touchez avec la plume une étendue d'eau d'au moins 18 m de diamètre : un bateau en forme de cygne de 15 m sur 6 apparaît. Il avance seul à 10 km/h ; à bord, une action Magie permet de le diriger ou de le faire pivoter de 90° au plus. Il disparaît après 24 heures ; vous pouvez le congédier par une action Magie.
66-90 Arbre (peu commune). En extérieur, par une action Magie, vous touchez avec la plume un espace inoccupé au sol : un chêne non magique de 18 m de haut, au tronc de 1,50 m de diamètre et aux branches déployées sur 6 m de rayon, surgit à sa place.
91-00 Fouet (rare). Par une action Magie, vous lancez la plume à 3 m ou moins : un fouet flottant apparaît. Par une action bonus, vous pouvez effectuer une attaque de sort au corps à corps (+9) contre une créature à 3 m ou moins du fouet ; en cas de réussite, elle subit 1d6 + 5 dégâts de force. Par une action bonus, vous pouvez le faire voler jusqu'à 6 m et répéter l'attaque. Il disparaît après 1 heure, si vous le congédiez par une action Magie, ou si vous mourez ou êtes neutralisé.$t$),
  ($t$Figurine merveilleuse$t$, $t$Figurine of Wondrous Power$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun à très rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette statuette tient dans une poche. Si vous la lancez au sol à 18 m ou moins par une action Magie, elle devient la créature vivante indiquée ci-dessous. Si l'espace est occupé ou trop petit, rien ne se passe.
La créature est amicale envers vous et vos alliés, comprend vos langues, obéit à vos ordres et agit juste après vous dans l'ordre d'initiative ; sans ordre, elle se défend mais n'agit pas autrement. Elle reprend sa forme de figurine à la fin de sa durée, si elle tombe à 0 point de vie, ou si vous la touchez et effectuez une action Magie. La propriété n'est ensuite plus utilisable pendant le délai indiqué.
Griffon de bronze (rare) : griffon, jusqu'à 6 heures ; 5 jours de recharge.
Mouche d'ébène (rare) : mouche géante chevauchable, jusqu'à 12 heures ; 2 jours de recharge.
Lions d'or (rare) : paire de lions, jusqu'à 1 heure ; 7 jours de recharge.
Chèvres d'ivoire (rare) : trois chèvres aux pouvoirs distincts (voyage, labeur, terreur), durées et recharges variables.
Éléphant de marbre (rare) : éléphant, jusqu'à 24 heures ; 7 jours de recharge.
Destrier d'obsidienne (très rare) : cauchemar, jusqu'à 24 heures ; 5 jours de recharge, avec un risque qu'il vous emporte vers les Enfers.
Chien d'onyx (rare) : molosse doté de vision dans le noir et d'une perception accrue, jusqu'à 6 heures ; 7 jours de recharge.
Chouette de serpentine (rare) : chouette géante télépathe, jusqu'à 8 heures ; 2 jours de recharge.
Corbeau d'argent (peu commun) : corbeau porteur de messages (Messager animal), jusqu'à 12 heures ; 2 jours de recharge.$t$),
  ($t$Langue de feu$t$, $t$Flame Tongue$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous tenez cette arme magique, vous pouvez effectuer une action bonus et prononcer un mot de commande pour que des flammes enveloppent sa partie offensive. Elles diffusent une lumière vive dans un rayon de 12 m et une lumière faible sur 12 m de plus. Tant que l'arme est embrasée, elle inflige 2d6 dégâts de feu supplémentaires quand elle touche. Les flammes durent jusqu'à ce que vous répétiez le mot de commande par une action bonus, ou que vous lâchiez, rangiez ou rengainiez l'arme.$t$),
  ($t$Bateau pliable$t$, $t$Folding Boat$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cet objet ressemble à une boîte en bois de 30 cm de long, 15 cm de large et 15 cm de haut. Elle pèse 2 kg, flotte et peut s'ouvrir pour y ranger des objets. Elle répond à trois mots de commande, chacun demandant une action Magie :
Premier mot. La boîte se déplie en barque.
Deuxième mot. La boîte se déplie en bateau à quille.
Troisième mot. Le bateau se replie en boîte s'il n'y a personne à bord ; les objets qui ne tiennent pas dans la boîte restent à l'extérieur, les autres y sont rangés.
Une fois déplié, l'objet prend le poids d'une embarcation normale de sa taille, et ce qui était rangé dans la boîte reste à bord. Si l'une ou l'autre embarcation tombe à 0 point de vie, le bateau pliable est détruit.$t$),
  ($t$Lame de givre$t$, $t$Frost Brand$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Quand vous touchez avec un jet d'attaque effectué avec cette arme magique, la cible subit 1d6 dégâts de froid supplémentaires. Tant que vous tenez l'arme, vous avez la résistance aux dégâts de feu. Par temps de gel, elle diffuse une lumière vive dans un rayon de 3 m et une lumière faible sur 3 m de plus.
Quand vous dégainez l'arme, vous pouvez éteindre toutes les flammes non magiques à 9 m ou moins de vous. Cette propriété n'est plus utilisable pendant 1 heure.$t$),
  ($t$Gantelets de puissance d'ogre$t$, $t$Gauntlets of Ogre Power$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Votre Force est de 19 tant que vous portez ces gantelets. Ils n'ont aucun effet si votre Force est déjà de 19 ou plus sans eux.$t$),
  ($t$Gemme de lumière$t$, $t$Gem of Brightness$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce prisme possède 50 charges. Tant que vous le tenez, vous pouvez effectuer une action Magie et prononcer l'un de trois mots de commande :
Premier mot. La gemme diffuse une lumière vive dans un rayon de 9 m et une lumière faible sur 9 m de plus, sans dépenser de charge, jusqu'à ce que vous répétiez le mot par une action bonus ou utilisiez une autre fonction.
Deuxième mot. Vous dépensez 1 charge : la gemme projette un rayon éblouissant sur une créature que vous voyez à 18 m ou moins, qui doit réussir un JS de Constitution DD 15 ou être aveuglée pendant 1 minute. Elle répète le jet à la fin de chacun de ses tours et met fin à l'effet en cas de réussite.
Troisième mot. Vous dépensez 5 charges : la gemme flamboie dans un cône de 9 m ; chaque créature dans le cône effectue le jet de sauvegarde comme si elle était frappée par le rayon.
Une fois toutes ses charges dépensées, la gemme devient un joyau non magique d'une valeur de 50 po.$t$),
  ($t$Gemme de vision$t$, $t$Gem of Seeing$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette gemme possède 3 charges. Par une action Magie, vous pouvez dépenser 1 charge : pendant 10 minutes, vous avez la vision véritable sur 36 m quand vous regardez à travers la gemme. Elle récupère 1d3 charges chaque jour à l'aube.$t$),
  ($t$Tueuse de géants$t$, $t$Giant Slayer$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous bénéficiez d'un bonus de +1 aux jets d'attaque et de dégâts effectués avec cette arme magique.
Quand vous touchez un géant avec elle, il subit 2d6 dégâts supplémentaires du type de l'arme et doit réussir un JS de Force DD 15 ou tomber à terre.$t$),
  ($t$Cuir clouté enchanté$t$, $t$Glamoured Studded Leather$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez cette armure, vous bénéficiez d'un bonus de +1 à la CA. Par une action bonus, vous pouvez aussi lui donner l'apparence de vêtements ordinaires ou d'un autre type d'armure, dont vous choisissez l'aspect (couleur, style, accessoires) ; elle conserve son encombrement et son poids. L'apparence illusoire dure jusqu'à ce que vous réutilisiez cette propriété ou ôtiez l'armure.$t$),
  ($t$Gants attrape-projectiles$t$, $t$Gloves of Missile Snaring$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Si vous êtes touché par un jet d'attaque effectué avec une arme à distance ou de lancer alors que vous portez ces gants, vous pouvez utiliser votre réaction pour réduire les dégâts de 1d10 + votre modificateur de Dextérité, si vous avez une main libre. Si vous réduisez les dégâts à 0, vous pouvez attraper la munition ou l'arme si elle est assez petite pour tenir dans cette main.$t$),
  ($t$Gants de nage et d'escalade$t$, $t$Gloves of Swimming and Climbing$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez ces gants, vous avez une vitesse d'escalade et une vitesse de nage égales à votre vitesse, et vous bénéficiez d'un bonus de +5 aux tests de Force (Athlétisme) pour escalader ou nager.$t$),
  ($t$Lunettes de nuit$t$, $t$Goggles of Night$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez ces verres sombres, vous avez la vision dans le noir sur 18 m. Si vous l'avez déjà, sa portée augmente de 18 m.$t$),
  ($t$Marteau de tonnerre$t$, $t$Hammer of Thunderbolts$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous bénéficiez d'un bonus de +1 aux jets d'attaque et de dégâts effectués avec cette arme magique. Elle possède 5 charges. Vous pouvez dépenser 1 charge pour effectuer une attaque à distance en la lançant comme si elle avait la propriété lancer (portée 6 m / 18 m). Si l'attaque touche, l'arme libère un coup de tonnerre audible jusqu'à 90 m : la cible et chaque autre créature à 9 m ou moins d'elle (sauf vous) doivent réussir un JS de Constitution DD 17 ou être étourdies jusqu'à la fin de votre prochain tour. Aussitôt après avoir touché ou raté, l'arme revient dans votre main. Elle récupère 1d4 + 1 charges chaque jour à l'aube.
Fléau des géants. Si vous êtes harmonisé à l'arme et portez un ceinturon de force de géant ou des gantelets de puissance d'ogre auxquels vous êtes aussi harmonisé, vous bénéficiez de ces avantages :
Fléau des géants. Quand vous obtenez 20 au d20 d'un jet d'attaque avec l'arme contre un géant, celui-ci doit réussir un JS de Constitution DD 17 ou mourir.
Puissance des géants. La valeur de Force accordée par votre ceinturon ou vos gantelets augmente de 4, jusqu'à un maximum de 30.$t$),
  ($t$Havresac magique$t$, $t$Handy Haversack$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce sac à dos comporte une poche centrale et deux poches latérales, chacune étant un espace extradimensionnel. Chaque poche latérale peut contenir jusqu'à 100 kg, dans un volume de 0,7 m³ au plus ; la poche centrale jusqu'à 250 kg, dans un volume de 1,8 m³ au plus. Le havresac pèse toujours 2,5 kg, quel que soit son contenu.
Récupérer un objet demande une action Utiliser ou une action bonus (au choix) ; l'objet recherché se trouve toujours, par magie, sur le dessus. Si une poche est surchargée, percée ou déchirée, le havresac se rompt et est détruit, et son contenu est perdu à jamais (un artefact finit toujours par réapparaître quelque part). Retourné, il répand son contenu sans dommage mais doit être remis à l'endroit avant de resservir. Chaque poche contient assez d'air pour 10 minutes de respiration, divisées par le nombre de créatures qui respirent à l'intérieur.
Placer le havresac dans un espace extradimensionnel créé par un sac sans fond, un trou portatif ou un objet similaire détruit instantanément les deux objets et ouvre un portail vers le plan Astral. Toute créature à 3 m ou moins du portail et sans abri total est aspirée vers un lieu aléatoire du plan Astral, puis le portail, à sens unique, se referme définitivement.$t$),
  ($t$Chapeau de déguisement$t$, $t$Hat of Disguise$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez ce chapeau, vous pouvez lancer le sort Déguisement. Le sort prend fin si vous retirez le chapeau.$t$),
  ($t$Bandeau d'intelligence$t$, $t$Headband of Intellect$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Votre Intelligence est de 19 tant que vous portez ce bandeau. Il n'a aucun effet si votre Intelligence est déjà de 19 ou plus sans lui.$t$),
  ($t$Heaume de brillance$t$, $t$Helm of Brilliance$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce heaume est serti de 1d10 diamants, 2d10 rubis, 3d10 opales de feu et 4d10 opales. Toute gemme arrachée du heaume tombe en poussière ; quand toutes ont disparu, il perd sa magie. Tant que vous le portez, vous bénéficiez de ces avantages :
Lumière de diamant. Tant qu'il reste au moins un diamant, le heaume génère une émanation de 9 m ; dès qu'un mort-vivant s'y trouve, elle se remplit de lumière faible, et tout mort-vivant qui commence son tour dans la zone subit 1d6 dégâts radiants.
Flammes d'opale de feu. Tant qu'il reste au moins une opale de feu, vous pouvez par une action Magie embraser une arme que vous tenez. Les flammes diffusent une lumière vive sur 3 m et faible sur 3 m de plus, sont inoffensives pour vous et l'arme, et infligent 1d6 dégâts de feu supplémentaires quand vous touchez. Elles durent jusqu'à ce que vous les éteigniez par une action bonus ou que vous lâchiez ou rangiez l'arme.
Résistance du rubis. Tant qu'il reste au moins un rubis, vous avez la résistance aux dégâts de feu.
Sorts. Vous pouvez lancer l'un de ces sorts (DD 18) en utilisant comme composante une gemme du type indiqué, qui est alors détruite : Lumière du jour (opale), Boule de feu (opale de feu), Rayons prismatiques (diamant), Mur de feu (rubis).
Dégâts de feu. Si vous portez le heaume et subissez des dégâts de feu après avoir raté un JS contre un sort, lancez 1d20. Sur un 1, le heaume projette des rayons de lumière depuis ses gemmes restantes puis est détruit : chaque créature dans une émanation de 18 m autour de vous doit réussir un JS de Dextérité DD 17 ou subir des dégâts radiants égaux au nombre de gemmes du heaume.$t$),
  ($t$Heaume de compréhension des langues$t$, $t$Helm of Comprehending Languages$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez ce heaume, vous pouvez lancer Compréhension des langues avec lui.$t$),
  ($t$Heaume de télépathie$t$, $t$Helm of Telepathy$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez ce heaume, vous avez la télépathie sur 9 m, et vous pouvez lancer Détection des pensées ou Suggestion (DD 13) avec lui. Une fois l'un de ces sorts lancé ainsi, il ne peut plus l'être avant l'aube suivante.$t$),
  ($t$Heaume de téléportation$t$, $t$Helm of Teleportation$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce heaume possède 3 charges. Tant que vous le portez, vous pouvez dépenser 1 charge pour lancer Téléportation avec lui. Il récupère 1d3 charges chaque jour à l'aube.$t$),
  ($t$Vengeresse sacrée$t$, $t$Holy Avenger$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Harmonisation par un paladin.
Vous bénéficiez d'un bonus de +3 aux jets d'attaque et de dégâts effectués avec cette arme magique. Quand vous touchez un fiélon ou un mort-vivant avec elle, il subit 2d10 dégâts radiants supplémentaires.
Tant que vous tenez l'arme dégainée, elle crée une émanation de 3 m autour de vous : vous et toutes les créatures amicales envers vous dans la zone avez l'avantage aux jets de sauvegarde contre les sorts et autres effets magiques. Si vous avez 17 niveaux ou plus de paladin, l'émanation passe à 9 m.$t$),
  ($t$Cor de dévastation$t$, $t$Horn of Blasting$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Par une action Magie, vous pouvez souffler dans ce cor, qui émet une déflagration tonitruante dans un cône de 9 m, audible jusqu'à 180 m. Chaque créature dans le cône effectue un JS de Constitution DD 15 : en cas d'échec, elle subit 5d8 dégâts de tonnerre et est assourdie pendant 1 minute ; en cas de réussite, elle ne subit que la moitié des dégâts. Les objets de verre ou de cristal non portés dans le cône subissent 10d8 dégâts de tonnerre.
Chaque utilisation a 20 % de chances de faire exploser le cor, qui inflige alors 10d6 dégâts de force à son utilisateur et est détruit.$t$),
  ($t$Cor du Valhalla$t$, $t$Horn of Valhalla$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Par une action Magie, vous pouvez souffler dans ce cor : des esprits guerriers venus du plan d'Ysgard apparaissent dans des espaces inoccupés à 18 m ou moins de vous. Chacun utilise le profil du berserker et retourne à Ysgard après 1 heure ou quand il tombe à 0 point de vie. Ils ressemblent à des guerriers bien vivants et sont immunisés contre les états charmé et effrayé. Une fois utilisé, le cor n'est plus utilisable pendant 7 jours.
Il en existe quatre types, chacun d'un métal différent, qui fixent le nombre d'esprits et la condition d'utilisation (choix du MJ ou d100) :
01-40 Argent : 2 esprits, aucune condition.
41-75 Laiton : 3 esprits, maîtrise de toutes les armes courantes.
76-90 Bronze : 4 esprits, formation à toutes les armures intermédiaires.
91-00 Fer : 5 esprits, maîtrise de toutes les armes de guerre.
Si vous soufflez dans le cor sans remplir la condition, les esprits vous attaquent. Sinon, ils sont amicaux envers vous et vos alliés et suivent vos ordres.$t$),
  ($t$Fers du zéphyr$t$, $t$Horseshoes of a Zephyr$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ces fers à cheval vont par quatre. Par une action Magie, vous pouvez toucher le sabot d'un cheval ou d'une créature similaire avec l'un d'eux, qui s'y fixe ; l'enlever demande aussi une action Magie. Quand les quatre fers sont fixés, la créature se déplace normalement en flottant à 10 cm au-dessus du sol : elle peut traverser ou se tenir au-dessus de surfaces non solides ou instables comme l'eau ou la lave, ne laisse aucune trace et ignore le terrain difficile. De plus, elle peut voyager jusqu'à 12 heures par jour sans subir de niveaux d'épuisement dus à la marche prolongée.$t$),
  ($t$Fers de rapidité$t$, $t$Horseshoes of Speed$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ces fers à cheval vont par quatre. Par une action Magie, vous pouvez toucher le sabot d'un cheval ou d'une créature similaire avec l'un d'eux, qui s'y fixe ; l'enlever demande aussi une action Magie. Quand les quatre fers sont fixés à la même créature, sa vitesse augmente de 9 m.$t$),
  ($t$Sceptre inamovible$t$, $t$Immovable Rod$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce sceptre de fer comporte un bouton à une extrémité. Par une action Utiliser, vous pouvez presser le bouton : le sceptre se fixe magiquement sur place et ne bouge plus, même en défiant la gravité, jusqu'à ce que vous ou une autre créature pressiez à nouveau le bouton par une action Utiliser. Il peut supporter jusqu'à 4 tonnes ; au-delà, il se désactive et tombe. Une créature peut effectuer une action Utiliser pour tenter un test de Force (Athlétisme) DD 30 et, en cas de réussite, déplacer le sceptre fixé de 3 m au maximum.$t$),
  ($t$Forteresse instantanée$t$, $t$Instant Fortress$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Par une action Magie, vous pouvez poser au sol cette statuette d'adamantium de 2,5 cm et, avec un mot de commande, la faire grandir rapidement en une tour carrée d'adamantium. Répéter le mot de commande la ramène à l'état de statuette, seulement si la tour est vide. Les créatures et objets non portés dans la zone où la tour apparaît sont repoussés dans des espaces inoccupés à côté d'elle.
La tour mesure 6 m de côté et 9 m de haut, avec des meurtrières sur tous les côtés et des créneaux au sommet. Son intérieur compte deux étages reliés par une échelle, un escalier ou une rampe (au choix), qui mène à une trappe donnant sur le toit. Elle a une seule porte au rez-de-chaussée, du côté tourné vers vous, qui ne s'ouvre que sur votre ordre (action bonus) et est immunisée contre Déblocage et les magies similaires. La magie empêche la tour de basculer.
Le toit, la porte et les murs ont chacun CA 20, 100 PV, l'immunité aux dégâts contondants, perforants et tranchants (sauf ceux des engins de siège) et la résistance à tous les autres dégâts. Rétrécir la tour ne répare pas ses dégâts ; seul un sort Souhait le peut (utilisation équivalente à reproduire un sort de niveau 8 ou moins), chaque lancer lui rendant tous ses points de vie.$t$),
  ($t$Bandes de fer$t$, $t$Iron Bands$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette sphère de fer rouillé de 7,5 cm de diamètre pèse 500 g. Par une action Magie, vous pouvez la lancer sur une créature de taille TG ou inférieure que vous voyez à 18 m ou moins. En vol, elle s'ouvre en un enchevêtrement de bandes de métal. Effectuez un jet d'attaque à distance avec un bonus égal à votre modificateur de Dextérité + votre bonus de maîtrise. En cas de réussite, la cible est entravée jusqu'à ce que vous la libériez par un ordre (action bonus). Libérer la cible ou rater l'attaque fait se rétracter les bandes en sphère.
Une créature pouvant toucher les bandes, y compris la créature entravée, peut effectuer une action pour tenter un test de Force (Athlétisme) DD 20 afin de les briser. En cas de réussite, l'objet est détruit et la créature libérée ; en cas d'échec, toute nouvelle tentative de cette créature échoue automatiquement pendant 24 heures. Une fois utilisées, les bandes ne sont plus utilisables avant l'aube suivante.$t$),
  ($t$Flasque de fer$t$, $t$Iron Flask$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous tenez cette flasque de fer au bouchon de laiton, vous pouvez effectuer une action Magie pour cibler une créature que vous voyez à 18 m ou moins. Si la flasque est vide et que la cible est originaire d'un autre plan d'existence que celui où vous vous trouvez, elle doit réussir un JS de Sagesse DD 17 ou être emprisonnée dans la flasque (avec l'avantage si elle y a déjà été piégée). Une créature piégée y reste jusqu'à sa libération ; la flasque ne contient qu'une créature à la fois, qui ne vieillit pas et n'a besoin ni de respirer, ni de manger, ni de boire.
Par une action Magie, vous pouvez déboucher la flasque et libérer la créature. Elle obéit alors à vos ordres pendant 1 heure, en les comprenant même sans connaître votre langue. Sans ordre, ou face à un ordre qui entraînerait probablement sa mort ou son emprisonnement, elle se défend mais n'agit pas autrement. Ensuite, elle agit selon sa nature et son alignement. Le sort Identification révèle si la flasque contient une créature, mais seule son ouverture en révèle le type. Une flasque nouvellement découverte peut déjà contenir une créature choisie par le MJ.$t$),
  ($t$Javeline de foudre$t$, $t$Javelin of Lightning$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Chaque fois que vous touchez avec un jet d'attaque effectué avec cette arme magique, vous pouvez lui faire infliger des dégâts de foudre au lieu de perforants.
Éclair. Quand vous lancez l'arme sur une cible à 36 m ou moins, vous pouvez renoncer au jet d'attaque à distance et la changer en éclair, qui forme une ligne de 1,50 m de large entre vous et la cible. La cible et chaque autre créature dans la ligne (sauf vous) effectuent un JS de Dextérité DD 13 : 4d6 dégâts de foudre en cas d'échec, la moitié en cas de réussite. L'arme réapparaît aussitôt dans votre main. Cette propriété n'est plus utilisable avant l'aube suivante.$t$),
  ($t$Lanterne de révélation$t$, $t$Lantern of Revealing$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Allumée, cette lanterne à capote brûle 6 heures avec 0,5 litre d'huile et diffuse une lumière vive dans un rayon de 9 m et une lumière faible sur 9 m de plus. Les créatures et objets invisibles sont visibles tant qu'ils sont dans sa lumière vive. Par une action Utiliser, vous pouvez baisser la capote pour réduire la lumière à une lumière faible dans un rayon de 1,50 m.$t$),
  ($t$Lame porte-bonheur$t$, $t$Luck Blade$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous bénéficiez d'un bonus de +1 aux jets d'attaque et de dégâts effectués avec cette arme magique. Tant que vous la portez sur vous, vous bénéficiez aussi d'un bonus de +1 aux jets de sauvegarde.
Chance. Si l'arme est sur vous et que vous n'êtes pas neutralisé, vous pouvez invoquer sa chance (sans action) pour relancer un test de d20 raté ; vous devez garder le second résultat. Propriété inutilisable avant l'aube suivante.
Souhait. L'arme possède 1d3 charges. Tant que vous la tenez, vous pouvez dépenser 1 charge pour lancer Souhait avec elle. Propriété inutilisable avant l'aube suivante ; l'arme la perd quand elle n'a plus de charges.$t$),
  ($t$Masse destructrice$t$, $t$Mace of Disruption$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Quand vous touchez un fiélon ou un mort-vivant avec cette arme magique, il subit 2d6 dégâts radiants supplémentaires. S'il a 25 points de vie ou moins après ces dégâts, il doit réussir un JS de Sagesse DD 15 ou être détruit ; en cas de réussite, il est effrayé jusqu'à la fin de votre prochain tour.
Lumière. Tant que vous tenez l'arme, elle diffuse une lumière vive dans un rayon de 6 m et une lumière faible sur 6 m de plus.$t$),
  ($t$Masse d'anéantissement$t$, $t$Mace of Smiting$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous bénéficiez d'un bonus de +1 aux jets d'attaque et de dégâts effectués avec cette arme magique, porté à +3 contre les artificiels. Quand vous obtenez 20 au jet d'attaque, la cible subit 7 dégâts contondants supplémentaires, ou 14 s'il s'agit d'un artificiel. Un artificiel qui a 25 points de vie ou moins après ces dégâts est détruit.$t$),
  ($t$Masse terrifiante$t$, $t$Mace of Terror$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Cette arme magique possède 3 charges et en récupère 1d3 chaque jour à l'aube. Tant que vous la tenez, vous pouvez effectuer une action Magie et dépenser 1 charge pour libérer une vague de terreur : chaque créature de votre choix à 9 m ou moins doit réussir un JS de Sagesse DD 15 ou être effrayée pendant 1 minute. Ainsi effrayée, elle doit passer ses tours à s'éloigner le plus possible de vous et ne peut pas faire d'attaques d'opportunité ; comme action, elle ne peut que Foncer ou tenter d'échapper à un effet qui l'empêche de bouger, ou Esquiver si elle ne peut aller nulle part. Elle répète le jet à la fin de chacun de ses tours et met fin à l'effet en cas de réussite.$t$),
  ($t$Manteau de résistance aux sorts$t$, $t$Mantle of Spell Resistance$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Rare$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Vous avez l'avantage aux jets de sauvegarde contre les sorts tant que vous portez ce manteau.$t$),
  ($t$Manuel de santé$t$, $t$Manual of Bodily Health$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce livre contient des conseils de santé et de nutrition chargés de magie. Si vous passez 48 heures, réparties sur 6 jours au plus, à étudier son contenu et à appliquer ses préceptes, votre Constitution augmente de 2, jusqu'à un maximum de 30. Le manuel perd alors sa magie, qu'il ne retrouve qu'au bout d'un siècle.$t$),
  ($t$Manuel d'exercice physique$t$, $t$Manual of Gainful Exercise$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce livre décrit des exercices physiques chargés de magie. Si vous passez 48 heures, réparties sur 6 jours au plus, à étudier son contenu et à appliquer ses préceptes, votre Force augmente de 2, jusqu'à un maximum de 30. Le manuel perd alors sa magie, qu'il ne retrouve qu'au bout d'un siècle.$t$),
  ($t$Manuel des golems$t$, $t$Manual of Golems$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce tome contient les informations et incantations nécessaires pour fabriquer un type de golem, choisi par le MJ ou déterminé au hasard. Pour le déchiffrer et l'utiliser, vous devez être un lanceur de sorts disposant d'au moins deux emplacements de niveau 5. Une créature qui ne peut pas l'utiliser et tente de le lire subit 6d6 dégâts psychiques.
Pour créer le golem, vous devez travailler sans interruption, manuel en main, pendant la durée indiquée, en ne vous reposant pas plus de 8 heures par jour, et payer le coût des fournitures. Une fois le golem achevé, le livre se consume dans des flammes surnaturelles ; le golem s'anime quand ses cendres sont répandues sur lui. Il est sous votre contrôle, comprend vos ordres et y obéit.
d20 : 1-5 golem d'argile (30 jours, 65 000 po) ; 6-17 golem de chair (60 jours, 50 000 po) ; 18 golem de fer (120 jours, 100 000 po) ; 19-20 golem de pierre (90 jours, 80 000 po).$t$),
  ($t$Manuel de vivacité$t$, $t$Manual of Quickness of Action$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce livre contient des exercices de coordination et d'équilibre chargés de magie. Si vous passez 48 heures, réparties sur 6 jours au plus, à étudier son contenu et à appliquer ses préceptes, votre Dextérité augmente de 2, jusqu'à un maximum de 30. Le manuel perd alors sa magie, qu'il ne retrouve qu'au bout d'un siècle.$t$),
  ($t$Pigments merveilleux$t$, $t$Marvelous Pigments$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, false, true, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce beau coffret de bois contient 1d4 pots de pigment et un pinceau (500 g en tout). Avec le pinceau et en consommant 1 pot, vous pouvez peindre autant d'objets et d'éléments de terrain en trois dimensions que vous le souhaitez (murs, portes, arbres, fleurs, armes, toiles, fosses…), à condition qu'ils tiennent tous dans un cube de 6 m. Le travail prend 10 minutes, pendant lesquelles vous devez rester dans le cube et vous concentrer. Si votre concentration est rompue ou si vous quittez le cube avant la fin, tout disparaît et le pot est perdu.
Une fois le travail achevé, les objets et éléments peints deviennent réels : une porte peinte sur un mur s'ouvre sur ce qui se trouve derrière, une fosse peinte devient une vraie fosse (entièrement contenue dans le cube). Aucun objet créé ne peut valoir plus de 25 po, et la valeur totale des objets créés par un pot ne peut dépasser 500 po ; des objets plus précieux (un tas d'or, par exemple) paraissent authentiques mais se révèlent, à l'examen, faits de pâte, de biscuit ou d'une autre matière sans valeur. Une énergie peinte, comme du feu ou de la foudre, se dissipe dès la fin de la peinture sans faire de mal.$t$),
  ($t$Médaillon des pensées$t$, $t$Medallion of Thoughts$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Ce médaillon possède 5 charges. Tant que vous le portez, vous pouvez dépenser 1 charge pour lancer Détection des pensées (DD 13) avec lui. Il récupère 1d4 charges chaque jour à l'aube.$t$),
  ($t$Miroir d'emprisonnement$t$, $t$Mirror of Life Trapping$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Très rare$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Regardé de biais, ce miroir de 1,20 m de haut sur 60 cm de large montre de vagues images de créatures. Il pèse 25 kg et a CA 11, 10 PV, l'immunité aux dégâts de poison et psychiques et la vulnérabilité aux dégâts contondants ; il se brise à 0 point de vie.
S'il est accroché à une surface verticale et que vous êtes à 1,50 m ou moins, vous pouvez l'activer par une action Magie et un mot de commande ; il reste actif jusqu'à ce que vous répétiez le mot par une action Magie. Toute autre créature qui voit son reflet dans le miroir actif à 9 m ou moins doit réussir un JS de Charisme DD 15 ou être emprisonnée, avec tout ce qu'elle porte, dans l'une des douze cellules extradimensionnelles du miroir (avantage si elle connaît sa nature ; réussite automatique pour les artificiels).
Une cellule est une étendue infinie emplie d'un épais brouillard limitant la visibilité à 3 m. Les prisonniers ne vieillissent pas et n'ont besoin ni de manger, ni de boire, ni de dormir ; ils ne peuvent s'échapper que par une magie de voyage planaire. Si les douze cellules sont occupées, le miroir libère un prisonnier au hasard pour faire place au nouveau ; il apparaît en vue du miroir, dos à lui. Si le miroir est brisé, tous les prisonniers sont libérés près de lui.
À 1,50 m ou moins, vous pouvez par une action Magie nommer un prisonnier ou un numéro de cellule : son image apparaît dans le miroir et vous pouvez communiquer. Par une action Magie et un second mot de commande, vous pouvez libérer un prisonnier, qui apparaît avec ses possessions dans l'espace libre le plus proche, dos au miroir.
Placer le miroir dans un espace extradimensionnel (sac sans fond, trou portatif…) détruit les deux objets et ouvre un portail à sens unique vers le plan Astral, qui aspire toute créature à 3 m ou moins sans abri total puis se referme.$t$),
  ($t$Armure de mithral$t$, $t$Mithral Armor$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Le mithral est un métal léger et souple ; une armure de mithral peut se porter sous des vêtements ordinaires. Si l'armure normale impose le désavantage aux tests de Dextérité (Discrétion) ou exige une valeur de Force minimale, sa version en mithral ne le fait pas.$t$),
  ($t$Jeu merveilleux$t$, $t$Mysterious Deck$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Légendaire$t$, false, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Généralement rangé dans une boîte ou une bourse, ce jeu contient des cartes d'ivoire ou de vélin : 13 cartes dans 75 % des cas, sinon 22. Avant de tirer, vous devez annoncer combien de cartes vous allez tirer, puis les tirer au hasard ; les cartes tirées au-delà n'ont aucun effet. La magie d'une carte agit dès qu'elle est tirée, et chaque tirage doit suivre le précédent dans l'heure ; sinon, les cartes restantes s'envolent d'elles-mêmes et agissent toutes à la fois. Une carte tirée disparaît puis réapparaît dans le jeu (sauf le Fou et le Bouffon ; relancez si l'une d'elles ressort).
Jeu de 13 cartes (d100) : 01-08 Euryale, 09-16 Flammes, 17-24 Bouffon, 25-32 Clé, 33-40 Chevalier, 41-48 Lune, 49-56 Voleur, 57-64 Ruine, 65-72 Crâne, 73-80 Étoile, 81-88 Soleil, 89-96 Trône, 97-00 Néant. Le jeu de 22 cartes y ajoute Équilibre, Comète, Donjon, Destin, Fou, Gemme, Énigme, Sage et Serres.
Équilibre. Vous pouvez augmenter une caractéristique de 2 (max. 22) en en diminuant une autre de 2 (impossible si elle est à 5 ou moins), ou ne rien changer.
Comète. Au prochain combat contre des créatures hostiles, désignez un adversaire lors de l'initiative ; si vous le faites tomber à 0 PV pendant ce combat, vous avez l'avantage aux jets de sauvegarde contre la mort pendant 1 an.
Donjon. Vous êtes emprisonné par magie (sous le Donjon, emplacement choisi par le MJ) jusqu'à ce qu'on vous délivre ; vous ne tirez plus de cartes.
Euryale. Le visage de méduse de la carte vous maudit : -2 aux jets de sauvegarde. Seul un dieu ou la carte Destin peut lever la malédiction.
Destin. La trame de la réalité se défait : vous pouvez effacer un événement comme s'il n'avait jamais eu lieu, dès le tirage ou plus tard avant votre mort.
Flammes. Un puissant diable devient votre ennemi et cherche votre perte jusqu'à la mort de l'un de vous.
Fou. Désavantage aux tests de d20 pendant 72 heures ; tirez une carte de plus (hors tirages annoncés).
Gemme. 25 bijoux de 2 000 po ou 50 gemmes de 1 000 po apparaissent à vos pieds.
Bouffon. Avantage aux tests de d20 pendant 72 heures, ou deux tirages supplémentaires.
Clé. Une arme magique rare ou plus que vous maîtrisez apparaît sur vous (choix du MJ).
Chevalier. Un chevalier de votre alignement apparaît à 9 m ou moins et vous sert loyalement jusqu'à la mort.
Lune. Vous pouvez lancer Souhait 1d3 fois.
Énigme. Votre Intelligence ou votre Sagesse diminue définitivement de 1d4 + 1 (min. 1) ; vous pouvez tirer une carte de plus.
Voleur. Un PNJ choisi par le MJ devient hostile envers vous, sans que vous connaissiez son identité ; seul un Souhait ou une intervention divine peut y mettre fin.
Ruine. Vous perdez toutes vos richesses hors objets magiques : biens portables, commerces, bâtiments, terres et titres de propriété disparaissent.
Sage. Dans l'année, vous pouvez poser une question en méditation et recevoir mentalement une réponse véridique.
Crâne. Un avatar de la mort (squelette spectral à la faux) apparaît près de vous et n'attaque que vous ; il disparaît à 0 PV ou à votre mort. Si un allié lui inflige des dégâts, il en convoque un autre qui ne vise que lui. Une créature tuée par un avatar ne peut pas être ramenée à la vie. (Avatar : CA 20, PV égaux à la moitié du maximum de celui qui l'a convoqué, vitesse et vol 18 m, déplacement intangible, fauche automatique infligeant 1d8 + 3 tranchants et 1d8 nécrotiques, autant d'attaques que la moitié du bonus de maîtrise de sa cible.)
Étoile. Une de vos caractéristiques augmente de 2 (max. 24).
Soleil. Un objet magique (choix du MJ) apparaît sur vous, et vous gagnez 10 points de vie temporaires chaque aube jusqu'à votre mort.
Serres. Tous vos objets magiques se désintègrent ; vos artefacts disparaissent.
Trône. Vous gagnez la maîtrise et l'expertise en Histoire, Intuition, Intimidation ou Persuasion (au choix), et la propriété d'un petit donjon, actuellement occupé par des monstres qu'il faut déloger.
Néant. Votre âme est arrachée et enfermée dans un objet, en un lieu gardé choisi par le MJ ; votre corps reste inerte sans vieillir. Un Souhait ne peut vous rendre votre âme mais révèle où se trouve l'objet. Vous ne tirez plus de cartes.$t$),
  ($t$Collier d'adaptation$t$, $t$Necklace of Adaptation$t$, $t$objet_magique$t$, null::numeric, null::jsonb, $t$Peu commun$t$, true, false, $t$Guide du maître (2024) / SRD 5.2$t$, $t$Tant que vous portez ce collier, vous pouvez respirer normalement dans n'importe quel environnement, et vous avez l'avantage aux jets de sauvegarde pour éviter ou terminer l'état empoisonné.$t$)
    ) as t(name_fr, name_en, category, weight, cost, rarity, attunement, consumable, source, description)
  loop
    if not exists (
      select 1 from public.translations tr
       where tr.entity_type = 'item' and tr.field_name = 'name' and tr.locale = 'fr'
         and lower(tr.value) = lower(rec.name_fr)
    ) then
      insert into public.items (category, weight, cost, source, rarity, requires_attunement, consumable)
        values (rec.category, rec.weight, rec.cost, rec.source, rec.rarity, rec.attunement, rec.consumable)
        returning id into v_id;
      insert into public.translations (entity_type, entity_id, field_name, locale, value) values
        ('item', v_id::text, 'name', 'fr', rec.name_fr),
        ('item', v_id::text, 'name', 'en', rec.name_en),
        ('item', v_id::text, 'description', 'fr', rec.description);
      v_inserted := v_inserted + 1;
    end if;
  end loop;
  raise notice 'objets insérés : %', v_inserted;
end $$;

