-- Chantier "Personnages" (app mobile) -- contenu D&D, lot 4 (relu par le chef de projet).
-- Complete public.class_features avec la progression multi-niveaux des sous-classes
-- hors SRD (license_status official_needs_verification dans class_features.json),
-- reformulee en texte original (jamais copie du livre) -- voir
-- scripts/class_features_non_srd_draft.json pour la trace complete, y compris les
-- 8 corrections factuelles faites en relecture par le chef de projet avant cette
-- migration (ex. "Aspect de la bete" Aigle confondait niveau 6 et niveau 14 ;
-- "Benediction de l'escroc"/"Linceul d'ombre"/"Pretre de guerre" du Clerc
-- decrivaient un effet mecaniquement different du RAW ; "Esprit eveille" de
-- l'Occultiste inventait un prerequis de langue commune qui n'existe pas RAW ;
-- type de degats de "Frappe divine" corrige pour Guerre/Duperie).
--
-- Occultiste "Le Genie" : le fichier source ne detaille pas les 4 variantes
-- (Dao/Djinn/Efrit/Maride) separement (mecanique de patron partagee, seul le
-- talent elementaire differe, deja hors perimetre de ce lot) -- les 10 lignes
-- du fichier pour "Le Genie" sont donc dupliquees sur les 4 sous-classes deja
-- en base (Genie - Dao/Djinn/Efrit/Maride, ids 76-79).
--
-- Paladin "Serment des anciens" (subclass_id=7) : c'est la sous-classe
-- "iconique" posee en Phase 1 pour ce serment (PAS le Serment de devotion
-- SRD, id=83, deja complete au lot 2) -- non-SRD comme les autres de ce lot.
--
-- Dedoublonnage par subclass_id + niveau + nom (idempotent, comme le lot 2).

do $$
declare
  rec record;
  v_id int;
begin
  for rec in
    select * from (values
      (13, 3, $q$Quêteur spirituel$q$, $q$Vous pouvez lancer les rituels invocation d'animaux ou communication avec les animaux, mais seulement sous forme de rituel.$q$, null, null::jsonb),
      (13, 3, $q$Esprit totem$q$, $q$Vous choisissez un esprit totem (Ours, Aigle ou Loup) qui vous octroie un bénéfice tant que vous êtes en rage : Ours (résistance à tous les dégâts sauf psychiques), Aigle (désavantage aux attaques d'opportunité contre vous et action bonus pour Foncer), ou Loup (vos alliés ont l'avantage aux attaques de mêlée contre une créature à 1,50 m de vous).$q$, null, null::jsonb),
      (13, 6, $q$Aspect de la bête$q$, $q$Vous gagnez un bénéfice permanent lié à votre esprit totem, même hors rage : Ours (force portée doublée, avantage aux tests de Force), Aigle (vous voyez jusqu'à 1,6 km sans difficulté et la pénombre ne vous impose pas de désavantage aux tests de Sagesse (Perception) fondés sur la vue), ou Loup (pistage à vitesse normale et déplacement furtif en groupe même à vitesse normale).$q$, null, null::jsonb),
      (13, 10, $q$Marcheur spirituel$q$, $q$Vous pouvez lancer le rituel communion avec la nature ; en le lançant ainsi, vous invoquez à la place un esprit spectral qui prend la forme de votre animal totem pour répondre à vos questions.$q$, null, null::jsonb),
      (13, 14, $q$Lien totémique$q$, $q$Tant que vous êtes en rage, vous gagnez un bénéfice supplémentaire puissant lié à votre esprit totem : Ours (vos alliés à 9 m gagnent la résistance à tous les dégâts sauf psychiques), Aigle (vitesse de vol égale à la vitesse de marche), ou Loup (vos attaques réussies mettent une grande créature à terre).$q$, null, null::jsonb),
      (18, 3, $q$Sens de la magie$q$, $q$Par une action, vous savez si un sort a été lancé à 18 m de vous au cours du dernier round, sans en connaître l'école ni la source exacte.$q$, null, null::jsonb),
      (18, 3, $q$Sursaut sauvage$q$, $q$Chaque fois que vous entrez en rage, vous lancez sur la table Éruption sauvage (d8) pour déclencher un effet magique aléatoire touchant vous-même et les créatures proches.$q$, null, null::jsonb),
      (18, 6, $q$Réserve de magie$q$, $q$Vous pouvez dépenser un dé d'Éruption sauvage non utilisé pour donner à une créature à 18 m un avantage à son prochain jet d'attaque, de sauvegarde ou de caractéristique.$q$, null, null::jsonb),
      (18, 10, $q$Réaction instable$q$, $q$En réaction lorsque vous subissez des dégâts d'une attaque ou ratez un jet de sauvegarde alors que vous êtes en rage, vous pouvez relancer sur la table Éruption sauvage.$q$, null, null::jsonb),
      (18, 14, $q$Sursaut contrôlé$q$, $q$Lorsque vous lancez sur la table Éruption sauvage, vous pouvez lancer deux fois et choisir l'un des deux résultats.$q$, null, null::jsonb),
      (20, 3, $q$Maîtrises supplémentaires$q$, $q$Vous gagnez la maîtrise des armures intermédiaires, des boucliers et des armes de guerre.$q$, null, null::jsonb),
      (20, 3, $q$Inspiration martiale$q$, $q$Une créature qui utilise votre dé d'Inspiration bardique sur un jet d'attaque peut ajouter le dé aux dégâts infligés par l'attaque en cas de réussite.$q$, null, null::jsonb),
      (20, 6, $q$Attaque supplémentaire$q$, $q$Vous pouvez attaquer deux fois, au lieu d'une, chaque fois que vous effectuez l'action Attaquer à votre tour.$q$, null, null::jsonb),
      (20, 14, $q$Magie de combat$q$, $q$Quand vous utilisez votre action pour lancer un sort de barde, vous pouvez effectuer une attaque avec une arme en action bonus.$q$, null, null::jsonb),
      (27, 1, $q$Sorts de domaine (Niveau de clerc 1)$q$, $q$Sorts de domaine toujours préparés, gagnés automatiquement à ce niveau de clerc (ne comptent pas dans le nombre de sorts préparés) : Charme-personne, Déguisement.$q$, $q$sort_domaine$q$, null::jsonb),
      (27, 3, $q$Sorts de domaine (Niveau de clerc 3)$q$, $q$Sorts de domaine toujours préparés : Reflets troublants, Passage sans trace.$q$, $q$sort_domaine$q$, null::jsonb),
      (27, 5, $q$Sorts de domaine (Niveau de clerc 5)$q$, $q$Sorts de domaine toujours préparés : Clignotement, Dissipation de la magie.$q$, $q$sort_domaine$q$, null::jsonb),
      (27, 7, $q$Sorts de domaine (Niveau de clerc 7)$q$, $q$Sorts de domaine toujours préparés : Porte dimensionnelle, Métamorphose.$q$, $q$sort_domaine$q$, null::jsonb),
      (27, 9, $q$Sorts de domaine (Niveau de clerc 9)$q$, $q$Sorts de domaine toujours préparés : Domination de personne, Modification de la mémoire.$q$, $q$sort_domaine$q$, null::jsonb),
      (27, 1, $q$Bénédiction de l'escroc$q$, $q$Par un rituel, vous touchez une créature consentante pour lui accorder l'avantage aux tests de Discrétion pendant 1 heure ; utilisable de nouveau seulement en répétant le rituel (annule l'effet précédent).$q$, null, null::jsonb),
      (27, 2, $q$Conduit divin : invocation de réplique$q$, $q$Vous utilisez votre Conduit divin pour créer une illusion parfaite de vous-même qui dure 1 minute et peut se déplacer et parler à votre place.$q$, null, null::jsonb),
      (27, 6, $q$Conduit divin : linceul d'ombre$q$, $q$Par une action, vous utilisez votre Conduit divin pour devenir invisible jusqu'à la fin de votre prochain tour ; vous redevenez visible si vous attaquez ou lancez un sort.$q$, null, null::jsonb),
      (27, 8, $q$Frappe divine$q$, $q$Une fois par tour, vous pouvez ajouter 1d8 dégâts de poison (2d8 au niveau 14) sur une attaque d'arme réussie.$q$, null, null::jsonb),
      (27, 17, $q$Réplique améliorée$q$, $q$Votre réplique illusoire (voir Invocation de réplique) peut désormais lancer les sorts que vous lui avez préparés en votre nom, en utilisant vos emplacements de sorts.$q$, null, null::jsonb),
      (28, 1, $q$Sorts de domaine (Niveau de clerc 1)$q$, $q$Sorts de domaine toujours préparés : Faveur divine, Bouclier de la foi.$q$, $q$sort_domaine$q$, null::jsonb),
      (28, 3, $q$Sorts de domaine (Niveau de clerc 3)$q$, $q$Sorts de domaine toujours préparés : Arme magique, Arme spirituelle.$q$, $q$sort_domaine$q$, null::jsonb),
      (28, 5, $q$Sorts de domaine (Niveau de clerc 5)$q$, $q$Sorts de domaine toujours préparés : Manteau du croisé, Gardiens spirituels.$q$, $q$sort_domaine$q$, null::jsonb),
      (28, 7, $q$Sorts de domaine (Niveau de clerc 7)$q$, $q$Sorts de domaine toujours préparés : Liberté de mouvement, Peau de pierre.$q$, $q$sort_domaine$q$, null::jsonb),
      (28, 9, $q$Sorts de domaine (Niveau de clerc 9)$q$, $q$Sorts de domaine toujours préparés : Frappe flamboyante, Immobilisation de monstre.$q$, $q$sort_domaine$q$, null::jsonb),
      (28, 1, $q$Maîtrises supplémentaires$q$, $q$Vous gagnez la maîtrise des armures lourdes et des armes de guerre.$q$, null, null::jsonb),
      (28, 1, $q$Prêtre de guerre$q$, $q$Quand vous utilisez l'action Attaquer, vous pouvez effectuer une attaque d'arme supplémentaire en action bonus. Utilisable un nombre de fois égal à votre modificateur de Sagesse (minimum 1) par repos long.$q$, null, null::jsonb),
      (28, 2, $q$Conduit divin : frappe guidée$q$, $q$Vous utilisez votre Conduit divin pour gagner +10 à un jet d'attaque que vous venez d'effectuer, après en avoir vu le résultat mais avant de connaître son issue.$q$, null, null::jsonb),
      (28, 6, $q$Conduit divin : bénédiction du dieu de la guerre$q$, $q$Vous utilisez votre Conduit divin, en réaction, pour donner à une créature à 9 m un bonus de +10 à un jet d'attaque qu'elle vient d'effectuer.$q$, null, null::jsonb),
      (28, 8, $q$Frappe divine$q$, $q$Une fois par tour, vos attaques d'arme infligent 1d8 dégâts supplémentaires du même type que l'arme utilisée (2d8 au niveau 14).$q$, null, null::jsonb),
      (28, 17, $q$Avatar de bataille$q$, $q$Vous obtenez la résistance aux dégâts contondants, perforants et tranchants provenant d'armes non magiques.$q$, null, null::jsonb),
      (29, 1, $q$Sorts de domaine (Niveau de clerc 1)$q$, $q$Sorts de domaine toujours préparés : Mains brûlantes, Lueurs féeriques.$q$, $q$sort_domaine$q$, null::jsonb),
      (29, 3, $q$Sorts de domaine (Niveau de clerc 3)$q$, $q$Sorts de domaine toujours préparés : Sphère de feu, Rayon ardent.$q$, $q$sort_domaine$q$, null::jsonb),
      (29, 5, $q$Sorts de domaine (Niveau de clerc 5)$q$, $q$Sorts de domaine toujours préparés : Lumière du jour, Boule de feu.$q$, $q$sort_domaine$q$, null::jsonb),
      (29, 7, $q$Sorts de domaine (Niveau de clerc 7)$q$, $q$Sorts de domaine toujours préparés : Gardien de la foi, Mur de feu.$q$, $q$sort_domaine$q$, null::jsonb),
      (29, 9, $q$Sorts de domaine (Niveau de clerc 9)$q$, $q$Sorts de domaine toujours préparés : Frappe flamboyante, Scrutation.$q$, $q$sort_domaine$q$, null::jsonb),
      (29, 1, $q$Sort mineur supplémentaire$q$, $q$Vous connaissez le cantrip Lumière en plus des cantrips normalement connus à ce niveau.$q$, $q$sort_mineur_bonus$q$, null::jsonb),
      (29, 1, $q$Illumination protectrice$q$, $q$En réaction lorsqu'une créature à 9 m de vous subit des dégâts, vous pouvez réduire ces dégâts de 1d8 + votre niveau de clerc.$q$, null, null::jsonb),
      (29, 2, $q$Conduit divin : radiance de l'aube$q$, $q$Vous utilisez votre Conduit divin pour libérer une lumière matinale qui inflige 2d10 + votre niveau de clerc dégâts radiants aux ennemis dans un rayon de 9 m et dissipe l'obscurité magique.$q$, null, null::jsonb),
      (29, 6, $q$Illumination améliorée$q$, $q$Votre trait Illumination protectrice réduit désormais les dégâts de 1d8 + le double de votre niveau de clerc.$q$, null, null::jsonb),
      (29, 8, $q$Incantation puissante$q$, $q$Vous ajoutez votre modificateur de Sagesse aux dégâts infligés par les cantrips de clerc.$q$, null, null::jsonb),
      (29, 17, $q$Halo de lumière$q$, $q$Vous émettez en permanence une lumière vive dans un rayon de 9 m (faible dans 9 m supplémentaires) et vous êtes résistant aux dégâts radiants.$q$, null, null::jsonb),
      (30, 1, $q$Sorts de domaine (Niveau de clerc 1)$q$, $q$Sorts de domaine toujours préparés : Amitié avec les animaux, Parole avec les animaux.$q$, $q$sort_domaine$q$, null::jsonb),
      (30, 3, $q$Sorts de domaine (Niveau de clerc 3)$q$, $q$Sorts de domaine toujours préparés : Peau d'écorce, Croissance d'épines.$q$, $q$sort_domaine$q$, null::jsonb),
      (30, 5, $q$Sorts de domaine (Niveau de clerc 5)$q$, $q$Sorts de domaine toujours préparés : Croissance végétale, Marche sur l'eau.$q$, $q$sort_domaine$q$, null::jsonb),
      (30, 7, $q$Sorts de domaine (Niveau de clerc 7)$q$, $q$Sorts de domaine toujours préparés : Domination d'animal, Liane agrippante.$q$, $q$sort_domaine$q$, null::jsonb),
      (30, 9, $q$Sorts de domaine (Niveau de clerc 9)$q$, $q$Sorts de domaine toujours préparés : Fléau d'insectes, Passage par les arbres.$q$, $q$sort_domaine$q$, null::jsonb),
      (30, 1, $q$Acolyte de la nature$q$, $q$Vous apprenez un cantrip de druide de votre choix et gagnez la maîtrise d'une compétence parmi Dressage, Nature ou Survie.$q$, null, null::jsonb),
      (30, 1, $q$Maîtrise supplémentaire$q$, $q$Vous gagnez la maîtrise des armures lourdes.$q$, null, null::jsonb),
      (30, 2, $q$Conduit divin : charme des animaux et des plantes$q$, $q$Vous utilisez votre Conduit divin pour charmer les bêtes et plantes-monstres dans un rayon de 9 m, chacune devant réussir un jet de sauvegarde de Sagesse ou être charmée pendant 1 minute.$q$, null, null::jsonb),
      (30, 6, $q$Atténuation des éléments$q$, $q$Vous et vos alliés à 9 m ou moins de vous êtes résistants aux dégâts d'acide, de froid, de feu, de foudre et de tonnerre.$q$, null, null::jsonb),
      (30, 8, $q$Frappe divine$q$, $q$Une fois par tour, vous pouvez ajouter 1d8 dégâts (2d8 au niveau 14) d'un type élémentaire (acide, froid, feu, foudre ou tonnerre) sur une attaque d'arme réussie.$q$, null, null::jsonb),
      (30, 17, $q$Maître de la nature$q$, $q$Vous apprenez à parler, lire et écrire le sylvestre, et les bêtes et plantes-monstres hostiles ont un désavantage aux jets d'attaque contre vous tant qu'elles peuvent vous voir.$q$, null, null::jsonb),
      (31, 1, $q$Sorts de domaine (Niveau de clerc 1)$q$, $q$Sorts de domaine toujours préparés : Commandement, Identification.$q$, $q$sort_domaine$q$, null::jsonb),
      (31, 3, $q$Sorts de domaine (Niveau de clerc 3)$q$, $q$Sorts de domaine toujours préparés : Augure, Suggestion.$q$, $q$sort_domaine$q$, null::jsonb),
      (31, 5, $q$Sorts de domaine (Niveau de clerc 5)$q$, $q$Sorts de domaine toujours préparés : Anti-détection, Parler avec les morts.$q$, $q$sort_domaine$q$, null::jsonb),
      (31, 7, $q$Sorts de domaine (Niveau de clerc 7)$q$, $q$Sorts de domaine toujours préparés : Œil arcanique, Confusion.$q$, $q$sort_domaine$q$, null::jsonb),
      (31, 9, $q$Sorts de domaine (Niveau de clerc 9)$q$, $q$Sorts de domaine toujours préparés : Connaissance des légendes, Scrutation.$q$, $q$sort_domaine$q$, null::jsonb),
      (31, 1, $q$Bénédictions du savoir$q$, $q$Vous gagnez la maîtrise de deux compétences parmi Arcanes, Histoire, Nature ou Religion, et vous doublez votre bonus de maîtrise pour ces compétences.$q$, null, null::jsonb),
      (31, 2, $q$Conduit divin : savoir ancestral$q$, $q$Vous utilisez votre Conduit divin pour obtenir l'avantage à un test de caractéristique lié à l'Histoire, ou pour gagner la maîtrise d'une compétence pendant 10 minutes.$q$, null, null::jsonb),
      (31, 6, $q$Conduit divin : lecture des pensées$q$, $q$Vous utilisez votre Conduit divin pour lire les pensées superficielles d'une créature pendant 5 minutes ; vous pouvez ensuite tenter de sonder plus profondément (JdS d'Intelligence) ou implanter un souvenir suggéré.$q$, null, null::jsonb),
      (31, 8, $q$Incantation puissante$q$, $q$Vous ajoutez votre modificateur de Sagesse aux dégâts infligés par les cantrips de clerc.$q$, null, null::jsonb),
      (31, 17, $q$Visions du passé$q$, $q$Par un rituel de 1 minute, vous pouvez percevoir des impressions psychiques laissées dans un lieu ou un objet au cours des 10 derniers jours.$q$, null, null::jsonb),
      (32, 1, $q$Sorts de domaine (Niveau de clerc 1)$q$, $q$Sorts de domaine toujours préparés : Nuage de brouillard, Onde de choc.$q$, $q$sort_domaine$q$, null::jsonb),
      (32, 3, $q$Sorts de domaine (Niveau de clerc 3)$q$, $q$Sorts de domaine toujours préparés : Rafale de vent, Éclat.$q$, $q$sort_domaine$q$, null::jsonb),
      (32, 5, $q$Sorts de domaine (Niveau de clerc 5)$q$, $q$Sorts de domaine toujours préparés : Appel de la foudre, Tempête de neige fondue.$q$, $q$sort_domaine$q$, null::jsonb),
      (32, 7, $q$Sorts de domaine (Niveau de clerc 7)$q$, $q$Sorts de domaine toujours préparés : Contrôle de l'eau, Tempête de grêle.$q$, $q$sort_domaine$q$, null::jsonb),
      (32, 9, $q$Sorts de domaine (Niveau de clerc 9)$q$, $q$Sorts de domaine toujours préparés : Onde destructrice, Fléau d'insectes.$q$, $q$sort_domaine$q$, null::jsonb),
      (32, 1, $q$Maîtrises supplémentaires$q$, $q$Vous gagnez la maîtrise des armures lourdes et des armes de guerre.$q$, null, null::jsonb),
      (32, 1, $q$Fureur de l'ouragan$q$, $q$Quand vous infligez des dégâts de foudre ou de tonnerre avec un cantrip, vous pouvez ajouter votre modificateur de Sagesse aux dégâts.$q$, null, null::jsonb),
      (32, 2, $q$Conduit divin : fureur destructrice$q$, $q$Vous utilisez votre Conduit divin pour transformer vos dégâts de foudre ou de tonnerre en dégâts maximaux le temps d'un tour.$q$, null, null::jsonb),
      (32, 6, $q$Frappe de l'éclair$q$, $q$Quand vous infligez des dégâts de foudre à une créature avec une attaque ou un sort, vous pouvez la repousser de 3 m par une action bonus.$q$, null, null::jsonb),
      (32, 8, $q$Frappe divine$q$, $q$Une fois par tour, vous pouvez ajouter 1d8 dégâts (2d8 au niveau 14) de tonnerre sur une attaque d'arme réussie.$q$, null, null::jsonb),
      (32, 17, $q$Enfant de la tempête$q$, $q$Vous êtes résistant aux dégâts de foudre et de tonnerre, et vous pouvez voler à votre vitesse de marche pendant votre chute, sans subir de dégâts de chute.$q$, null, null::jsonb),
      (34, 1, $q$Sorts de domaine (Niveau de clerc 1)$q$, $q$Sorts de domaine toujours préparés : Identification, Frappe cuisante.$q$, $q$sort_domaine$q$, null::jsonb),
      (34, 3, $q$Sorts de domaine (Niveau de clerc 3)$q$, $q$Sorts de domaine toujours préparés : Métal brûlant, Arme magique.$q$, $q$sort_domaine$q$, null::jsonb),
      (34, 5, $q$Sorts de domaine (Niveau de clerc 5)$q$, $q$Sorts de domaine toujours préparés : Arme élémentaire, Protection contre les éléments.$q$, $q$sort_domaine$q$, null::jsonb),
      (34, 7, $q$Sorts de domaine (Niveau de clerc 7)$q$, $q$Sorts de domaine toujours préparés : Fabrication, Mur de feu.$q$, $q$sort_domaine$q$, null::jsonb),
      (34, 9, $q$Sorts de domaine (Niveau de clerc 9)$q$, $q$Sorts de domaine toujours préparés : Animation d'objets, Création.$q$, $q$sort_domaine$q$, null::jsonb),
      (34, 1, $q$Maîtrises supplémentaires$q$, $q$Vous gagnez la maîtrise des armures lourdes et des outils de forgeron.$q$, null, null::jsonb),
      (34, 1, $q$Bénédiction de la forge$q$, $q$Par un rituel nocturne, vous rendez magique une arme ou une armure non magique (+1 CA ou +1 aux dégâts selon le cas). Cette bénédiction dure jusqu'à ce que vous répétiez le rituel sur un autre objet.$q$, null, null::jsonb),
      (34, 2, $q$Conduit divin : bénédiction de l'artisan$q$, $q$Vous utilisez votre Conduit divin pour aider un artisan : le jet lié à la fabrication d'un objet non magique gagne un bonus égal à votre modificateur de Sagesse.$q$, null, null::jsonb),
      (34, 6, $q$Âme de la forge$q$, $q$Vous êtes résistant aux dégâts de feu et vous pouvez ignorer les propriétés désavantageuses d'une armure lourde ou intermédiaire que vous portez (force minimale, désavantage à la Discrétion).$q$, null, null::jsonb),
      (34, 8, $q$Frappe divine$q$, $q$Une fois par tour, vous pouvez ajouter 1d8 dégâts de feu (2d8 au niveau 14) sur une attaque d'arme réussie.$q$, null, null::jsonb),
      (34, 17, $q$Saint de la forge et du feu$q$, $q$Vous êtes immunisé aux dégâts de feu et vous gagnez la résistance aux dégâts contondants, perforants et tranchants provenant d'armes non magiques.$q$, null, null::jsonb),
      (36, 2, $q$Forme sauvage de combat$q$, $q$Vous pouvez utiliser votre Forme sauvage comme action bonus (au lieu d'une action) et dépenser des emplacements de sorts pour récupérer des points de vie temporaires en changeant de forme.$q$, null, null::jsonb),
      (36, 2, $q$Formes du cercle$q$, $q$Votre Forme sauvage vous permet de prendre l'apparence de bêtes de FP plus élevé que la normale (jusqu'à FP 1 au niveau 2, augmentant avec votre niveau de druide).$q$, null, null::jsonb),
      (36, 6, $q$Frappe primitive$q$, $q$Vos attaques d'armes naturelles sous Forme sauvage sont considérées comme magiques pour outrepasser la résistance et l'immunité aux dégâts non magiques.$q$, null, null::jsonb),
      (36, 10, $q$Forme sauvage élémentaire$q$, $q$Vous pouvez dépenser deux utilisations de Forme sauvage pour prendre la forme d'un élémentaire (Air, Terre, Eau ou Feu).$q$, null, null::jsonb),
      (36, 14, $q$Mille formes$q$, $q$Vous pouvez lancer à volonté le sort déguisement du basilic, sans dépenser d'emplacement de sort.$q$, null, null::jsonb),
      (42, 1, $q$Pic de magie sauvage$q$, $q$Après avoir lancé un sort d'ensorceleur de niveau 1 ou plus, le MJ peut vous faire lancer un d20 : sur un 1, vous déclenchez un effet aléatoire de la table Éruption sauvage.$q$, null, null::jsonb),
      (42, 1, $q$Marée du chaos$q$, $q$Vous gagnez l'avantage à un jet au prix d'une action bonus, mais le MJ peut ensuite déclencher un effet de la table Éruption sauvage à un moment ultérieur.$q$, null, '{"amount": 1, "rest_type": "repos_long"}'::jsonb),
      (42, 6, $q$Chance forcée$q$, $q$Une fois par repos long, vous pouvez transformer un échec en réussite lors d'un jet de sauvegarde, mais vous déclenchez alors un effet de la table Éruption sauvage.$q$, null, null::jsonb),
      (42, 14, $q$Chaos contrôlé$q$, $q$Quand vous déclenchez un effet de la table Éruption sauvage, vous pouvez lancer deux fois et choisir l'un des deux résultats.$q$, null, null::jsonb),
      (42, 18, $q$Bombardement de sort$q$, $q$Quand vous infligez des dégâts avec un sort d'ensorceleur et obtenez le résultat le plus bas possible sur au moins un dé de dégâts, vous pouvez relancer ce dé, potentiellement plusieurs fois en chaîne.$q$, null, null::jsonb),
      (48, 3, $q$Disciple martial$q$, $q$Vous apprenez trois manœuvres de combat de votre choix et gagnez des dés de supériorité (d8) pour les alimenter.$q$, null, null::jsonb),
      (48, 3, $q$Supériorité martiale$q$, $q$Vous disposez de 4 dés de supériorité (d8), qui augmentent en nombre et en taille à des niveaux supérieurs ; vous les regagnez tous en terminant un repos court ou long.$q$, $q$manoeuvre$q$, '{"amount": 4, "rest_type": "repos_court"}'::jsonb),
      (48, 7, $q$Observation de l’ennemi$q$, $q$Par une action bonus, vous pouvez étudier une créature visible pour en apprendre les forces et faiblesses relatives (une des six caractéristiques la plus haute/basse, ou immunités/résistances/vulnérabilités).$q$, null, null::jsonb),
      (48, 10, $q$Supériorité martiale améliorée$q$, $q$Vos dés de supériorité passent au d10, puis au d12 au niveau 18.$q$, null, null::jsonb),
      (48, 15, $q$Implacable$q$, $q$Quand vous ratez un jet d'attaque avec une arme lors de votre tour, vous pouvez, une fois par repos court ou long, refaire immédiatement le jet.$q$, null, null::jsonb),
      (48, 3, $q$Manœuvres$q$, $q$Vous choisissez des manœuvres martiales parmi une liste (ex. Attaque précise, Feinte, Parade...) qui ajoutent un effet spécial en dépensant un dé de supériorité, avec un DD de sauvegarde égal à 8 + bonus de maîtrise + modificateur de Force ou Dextérité.$q$, null, null::jsonb),
      (49, 3, $q$Incantation$q$, $q$Vous apprenez à lancer des sorts de magicien (école d'évocation et d'abjuration principalement), en utilisant l'Intelligence comme caractéristique d'incantation, avec une progression de sorts lente (un tiers du niveau de guerrier).$q$, null, null::jsonb),
      (49, 3, $q$Lien avec une arme$q$, $q$Vous liez rituellement une arme à vous-même : vous ne pouvez pas en être désarmé sans le vouloir et pouvez la faire apparaître en main par une action bonus si elle se trouve sur le même plan d'existence.$q$, null, null::jsonb),
      (49, 7, $q$Magie de guerre$q$, $q$Quand vous utilisez votre action pour lancer un cantrip, vous pouvez effectuer une attaque avec une arme en action bonus.$q$, null, null::jsonb),
      (49, 10, $q$Frappe occulte$q$, $q$Une fois par tour, quand vous touchez une créature avec votre arme liée, vous pouvez la piéger magiquement (JdS d'Intelligence) lui imposant un désavantage aux jets de sauvegarde contre vos sorts jusqu'à la fin de votre prochain tour.$q$, null, null::jsonb),
      (49, 15, $q$Charge arcanique$q$, $q$Quand vous utilisez Fougue guerrière, vous pouvez vous téléporter jusqu'à 9 m vers un espace inoccupé visible avant ou après chaque attaque supplémentaire.$q$, null, null::jsonb),
      (49, 18, $q$Magie de guerre améliorée$q$, $q$Quand vous utilisez votre action pour lancer un sort de magicien, vous pouvez effectuer une attaque avec une arme en action bonus.$q$, null, null::jsonb),
      (55, 2, $q$Abjurateur érudit$q$, $q$L'or et le temps nécessaires pour copier un sort d'abjuration dans votre grimoire sont réduits de moitié.$q$, null, null::jsonb),
      (55, 2, $q$Protection arcanique$q$, $q$Quand vous lancez un sort d'abjuration de niveau 1 ou plus, vous créez un bouclier magique qui absorbe des dégâts (2 x niveau du sort + votre niveau de magicien) jusqu'à épuisement ou fin d'un repos long.$q$, null, '{"amount": 1, "rest_type": "repos_long"}'::jsonb),
      (55, 6, $q$Protection projetée$q$, $q$Vous pouvez utiliser votre réaction pour transférer les dégâts absorbés par votre Protection arcanique sur une autre créature à 9 m que vous pouvez voir.$q$, null, null::jsonb),
      (55, 10, $q$Abjuration améliorée$q$, $q$Quand vous créez votre Protection arcanique, vous pouvez choisir jusqu'à deux créatures supplémentaires à 9 m qui bénéficient chacune de leur propre réserve de points d'absorption.$q$, null, null::jsonb),
      (55, 14, $q$Résistance aux sorts$q$, $q$Vous avez l'avantage aux jets de sauvegarde contre les sorts, et vous êtes résistant aux dégâts infligés par les sorts des autres créatures.$q$, null, null::jsonb),
      (56, 2, $q$Devin érudit$q$, $q$L'or et le temps nécessaires pour copier un sort de divination dans votre grimoire sont réduits de moitié.$q$, null, null::jsonb),
      (56, 2, $q$Présage$q$, $q$Après un repos court ou long, vous lancez deux d20 et notez les résultats ; vous pouvez ensuite les substituer à un jet d'attaque, de caractéristique ou de sauvegarde vous concernant ou concernant une créature proche.$q$, null, '{"amount": 2, "rest_type": "repos_long"}'::jsonb),
      (56, 6, $q$Divination experte$q$, $q$Quand vous lancez un sort de divination utilisant un emplacement de niveau 2 ou plus, vous récupérez un emplacement de sort d'un niveau inférieur.$q$, null, null::jsonb),
      (56, 10, $q$Troisième œil$q$, $q$Par une action, vous gagnez l'un des sens suivants jusqu'à la fin de votre tour (sans dépense) : vision dans le noir, vue éthérée, détection des invisibles, ou lecture de toute langue.$q$, null, null::jsonb),
      (56, 14, $q$Présage supérieur$q$, $q$Vous obtenez trois d20 pour votre Présage (au lieu de deux) et pouvez en utiliser plus d'un pour un même jet.$q$, null, null::jsonb),
      (57, 2, $q$Enchanteur érudit$q$, $q$L'or et le temps nécessaires pour copier un sort d'enchantement dans votre grimoire sont réduits de moitié.$q$, null, null::jsonb),
      (57, 2, $q$Regard hypnotique$q$, $q$Par une action, vous pouvez tenter d'hypnotiser une créature que vous voyez à 1,50 m (JdS de Sagesse) ; en cas d'échec, elle est incapable d'agir jusqu'à la fin de votre prochain tour.$q$, null, null::jsonb),
      (57, 6, $q$Charme instinctif$q$, $q$Une fois par tour, en réaction, vous pouvez rediriger une attaque contre vous vers une autre créature à 1,50 m (JdS de Sagesse pour l'attaquant, sinon la nouvelle cible est visée).$q$, null, null::jsonb),
      (57, 10, $q$Partage d'enchantement$q$, $q$Quand vous lancez un sort d'enchantement de niveau 1 ou plus qui ne cible qu'une créature, vous pouvez viser une seconde créature à 9 m.$q$, null, null::jsonb),
      (57, 14, $q$Altération mémorielle$q$, $q$Vous pouvez lancer le sort modification de la mémoire sans dépenser d'emplacement de sort, une fois par repos long.$q$, null, null::jsonb),
      (58, 2, $q$Illusionniste érudit$q$, $q$L'or et le temps nécessaires pour copier un sort d'illusion dans votre grimoire sont réduits de moitié.$q$, null, null::jsonb),
      (58, 2, $q$Illusion mineure améliorée$q$, $q$Votre cantrip Illusion mineure gagne deux effets supplémentaires au choix chaque fois que vous le lancez.$q$, null, null::jsonb),
      (58, 6, $q$Illusions malléables$q$, $q$Vous pouvez modifier à distance l'illusion créée par un de vos sorts, changeant sa nature dans les limites du sort d'origine.$q$, null, null::jsonb),
      (58, 10, $q$Double illusoire$q$, $q$Par une action, vous créez une illusion parfaite de vous-même à 1,50 m qui dure jusqu'à ce qu'elle soit dissipée ; vous pouvez échanger vos places avec elle magiquement.$q$, null, '{"amount": 1, "rest_type": "repos_court"}'::jsonb),
      (58, 14, $q$Réalité illusoire$q$, $q$Une fois par sort d'illusion lancé, vous pouvez rendre un objet non magique inclus dans l'illusion réel pendant 1 minute.$q$, null, null::jsonb),
      (59, 2, $q$Invocateur érudit$q$, $q$L'or et le temps nécessaires pour copier un sort d'invocation dans votre grimoire sont réduits de moitié.$q$, null, null::jsonb),
      (59, 2, $q$Invocation mineure$q$, $q$Par une action et une composante matérielle sans valeur, vous invoquez une créature spectrale minuscule qui vous obéit pendant 1 heure.$q$, null, null::jsonb),
      (59, 6, $q$Permutation$q$, $q$Quand vous lancez un sort d'invocation de niveau 1 ou plus, vous pouvez remplacer une de ses composantes matérielles non coûteuses par un geste ou une formule.$q$, null, '{"amount": 1, "rest_type": "repos_long"}'::jsonb),
      (59, 10, $q$Invocation consciencieuse$q$, $q$Quand vous invoquez une créature par un sort, elle gagne des points de vie temporaires égaux à votre niveau de magicien.$q$, null, null::jsonb),
      (59, 14, $q$Convocations coriaces$q$, $q$Les créatures que vous invoquez par un sort d'invocation sont résistantes à tous les dégâts pendant la durée du sort.$q$, null, null::jsonb),
      (60, 2, $q$Nécromancien érudit$q$, $q$L'or et le temps nécessaires pour copier un sort de nécromancie dans votre grimoire sont réduits de moitié.$q$, null, null::jsonb),
      (60, 2, $q$Sinistre moisson$q$, $q$Quand vous tuez une créature avec un sort de niveau 1 ou plus, vous récupérez des points de vie temporaires égaux au double du niveau du sort (ou du niveau du cantrip x votre niveau de magicien/2).$q$, null, null::jsonb),
      (60, 6, $q$Serviteurs morts-vivants$q$, $q$Quand vous lancez un sort qui crée des morts-vivants sous votre contrôle, ils gagnent des points de vie et des dégâts supplémentaires liés à votre niveau de magicien.$q$, null, null::jsonb),
      (60, 10, $q$Insensibilité à la non-vie$q$, $q$Votre maximum de points de vie augmente d'un montant égal à votre niveau de magicien, et vous gagnez la résistance aux dégâts nécrotiques.$q$, null, null::jsonb),
      (60, 14, $q$Contrôle des morts-vivants$q$, $q$Par une action, vous pouvez tenter de prendre le contrôle d'un mort-vivant à 18 m (JdS de Sagesse pour lui) pour un nombre d'heures égal à votre niveau de magicien.$q$, null, null::jsonb),
      (61, 2, $q$Transmutateur érudit$q$, $q$L'or et le temps nécessaires pour copier un sort de transmutation dans votre grimoire sont réduits de moitié.$q$, null, null::jsonb),
      (61, 2, $q$Alchimie mineure$q$, $q$Par 10 minutes de travail, vous transformez temporairement un matériau (bois, pierre, fer, cuivre, argent) en un autre pendant 1 heure.$q$, null, null::jsonb),
      (61, 6, $q$Pierre du transmutateur$q$, $q$Vous créez une pierre du transmutateur qui donne à son porteur, au choix, la vision dans le noir, une vitesse accrue, une compétence supplémentaire, ou la résistance à un type de dégâts.$q$, null, null::jsonb),
      (61, 10, $q$Métamorphe$q$, $q$Vous pouvez utiliser une action pour vous transformer magiquement, changeant votre apparence physique sans altérer vos capacités.$q$, null, '{"amount": 1, "rest_type": "repos_court"}'::jsonb),
      (61, 14, $q$Maître transmutateur$q$, $q$Vous pouvez utiliser votre Pierre du transmutateur pour lancer le sort transformation en pierre sans dépenser d'emplacement de sort, une fois entre deux repos longs.$q$, null, null::jsonb),
      (65, 3, $q$Arts des ombres$q$, $q$Vous pouvez dépenser 2 points de ki pour lancer, sans composante, l'un des sorts obscurité, silence, passe-partout ou détection de la magie.$q$, null, null::jsonb),
      (65, 6, $q$Foulée d'ombre$q$, $q$Vous pouvez vous téléporter jusqu'à 18 m d'une zone d'ombre à une autre en action bonus, à condition que les deux zones soient faiblement ou pas du tout éclairées.$q$, null, null::jsonb),
      (65, 11, $q$Linceul d'ombre$q$, $q$Dans une zone de faible luminosité ou d'obscurité, vous pouvez dépenser 3 points de ki pour devenir invisible tant que vous restez dans cette zone.$q$, null, null::jsonb),
      (65, 17, $q$Opportuniste$q$, $q$Quand une créature à 1,50 m de vous subit des dégâts d'une autre source que vous, vous pouvez utiliser votre réaction pour l'attaquer au corps à corps.$q$, null, null::jsonb),
      (66, 3, $q$Disciple des éléments$q$, $q$Vous apprenez des disciplines élémentaires (sorts-like alimentés par des points de ki) que vous pouvez lancer au lieu de sorts classiques, en utilisant la Sagesse comme caractéristique d'incantation.$q$, $q$discipline_elementaire$q$, null::jsonb),
      (66, 17, $q$Disciplines élémentaires$q$, $q$Vous apprenez de nouvelles disciplines élémentaires en montant de niveau, débloquant des effets tels que souffle de dragon, vague déferlante ou tempête de feu, chacune coûtant des points de ki.$q$, null, null::jsonb),
      (73, 1, $q$Liste de sorts étendue (Niveau de sort 1)$q$, $q$Liste de sorts étendue disponible au choix pour votre Magie de pacte, sorts de niveau 1 : Charme-personne, Sommeil.$q$, $q$sort_domaine$q$, null::jsonb),
      (73, 3, $q$Liste de sorts étendue (Niveau de sort 2)$q$, $q$Liste de sorts étendue, sorts de niveau 2 : Calme des émotions, Toile d'araignée.$q$, $q$sort_domaine$q$, null::jsonb),
      (73, 5, $q$Liste de sorts étendue (Niveau de sort 3)$q$, $q$Liste de sorts étendue, sorts de niveau 3 : Dissipation de la magie, Croissance végétale.$q$, $q$sort_domaine$q$, null::jsonb),
      (73, 7, $q$Liste de sorts étendue (Niveau de sort 4)$q$, $q$Liste de sorts étendue, sorts de niveau 4 : Domination de bête, Œil arcanique.$q$, $q$sort_domaine$q$, null::jsonb),
      (73, 9, $q$Liste de sorts étendue (Niveau de sort 5)$q$, $q$Liste de sorts étendue, sorts de niveau 5 : Domination de personne, Songe.$q$, $q$sort_domaine$q$, null::jsonb),
      (73, 1, $q$Présence féerique$q$, $q$Par une action, vous entourez d'une aura féerique une créature à 3 m que vous voyez (JdS de Sagesse), lui infligeant charme ou peur jusqu'à la fin de votre prochain tour.$q$, null, '{"amount": 1, "rest_type": "repos_court"}'::jsonb),
      (73, 6, $q$Échappatoire brumeuse$q$, $q$Quand vous subissez des dégâts, vous pouvez utiliser votre réaction pour devenir invisible et vous téléporter jusqu'à 18 m vers un espace inoccupé visible.$q$, null, '{"amount": 1, "rest_type": "repos_court"}'::jsonb),
      (73, 10, $q$Défenses captivantes$q$, $q$Quand une créature vous touche par une attaque de mêlée, vous pouvez utiliser votre réaction pour la forcer à effectuer un jet de sauvegarde de Sagesse ou devenir charmée par vous pendant 1 minute.$q$, null, null::jsonb),
      (73, 14, $q$Sombre délire$q$, $q$Vous pouvez plonger une créature charmée ou effrayée par vous dans un délire hypnotique, l'incapacitant tant qu'elle reste à 18 m de vous.$q$, null, '{"amount": 1, "rest_type": "repos_court"}'::jsonb),
      (74, 1, $q$Liste de sorts étendue (Niveau de sort 1)$q$, $q$Liste de sorts étendue, sorts de niveau 1 : Détection de la magie, Reflets troublants.$q$, $q$sort_domaine$q$, null::jsonb),
      (74, 3, $q$Liste de sorts étendue (Niveau de sort 2)$q$, $q$Liste de sorts étendue, sorts de niveau 2 : Détection des pensées, Toile d'araignée.$q$, $q$sort_domaine$q$, null::jsonb),
      (74, 5, $q$Liste de sorts étendue (Niveau de sort 3)$q$, $q$Liste de sorts étendue, sorts de niveau 3 : Clairvoyance, Immobilisation de monstre.$q$, $q$sort_domaine$q$, null::jsonb),
      (74, 7, $q$Liste de sorts étendue (Niveau de sort 4)$q$, $q$Liste de sorts étendue, sorts de niveau 4 : Confusion, Œil arcanique.$q$, $q$sort_domaine$q$, null::jsonb),
      (74, 9, $q$Liste de sorts étendue (Niveau de sort 5)$q$, $q$Liste de sorts étendue, sorts de niveau 5 : Domination de personne, Télépathie.$q$, $q$sort_domaine$q$, null::jsonb),
      (74, 1, $q$Esprit éveillé$q$, $q$Vous gagnez la télépathie avec toute créature que vous voyez à 9 m, sans qu'un langage commun soit nécessaire.$q$, null, null::jsonb),
      (74, 6, $q$Protection entropique$q$, $q$Quand une créature vous attaque, vous pouvez utiliser votre réaction pour lui imposer un désavantage à son jet, gagnant vous-même l'avantage à votre prochain jet de sauvegarde.$q$, null, '{"amount": 1, "rest_type": "repos_court"}'::jsonb),
      (74, 10, $q$Bouclier mental$q$, $q$Vous êtes en permanence protégé contre la détection des pensées, et quand vous subissez des dégâts psychiques, vous pouvez utiliser votre réaction pour les réduire de moitié.$q$, null, null::jsonb),
      (74, 14, $q$Asservissement$q$, $q$Par une action, vous forcez une créature à vous obéir (JdS de Sagesse), ou en cas d'échec critique elle devient incapable d'agir tant qu'elle vous entend parler.$q$, null, null::jsonb),
      (76, 1, $q$Liste de sorts étendue (Niveau de sort 1)$q$, $q$Liste de sorts étendue liée au type de génie choisi (Dao/Djinn/Éfrit/Maride), sorts de niveau 1 (ex. Bouclier ardent ou Nuage de brouillard selon le type).$q$, $q$sort_domaine$q$, null::jsonb),
      (77, 1, $q$Liste de sorts étendue (Niveau de sort 1)$q$, $q$Liste de sorts étendue liée au type de génie choisi (Dao/Djinn/Éfrit/Maride), sorts de niveau 1 (ex. Bouclier ardent ou Nuage de brouillard selon le type).$q$, $q$sort_domaine$q$, null::jsonb),
      (78, 1, $q$Liste de sorts étendue (Niveau de sort 1)$q$, $q$Liste de sorts étendue liée au type de génie choisi (Dao/Djinn/Éfrit/Maride), sorts de niveau 1 (ex. Bouclier ardent ou Nuage de brouillard selon le type).$q$, $q$sort_domaine$q$, null::jsonb),
      (79, 1, $q$Liste de sorts étendue (Niveau de sort 1)$q$, $q$Liste de sorts étendue liée au type de génie choisi (Dao/Djinn/Éfrit/Maride), sorts de niveau 1 (ex. Bouclier ardent ou Nuage de brouillard selon le type).$q$, $q$sort_domaine$q$, null::jsonb),
      (76, 3, $q$Liste de sorts étendue (Niveau de sort 2)$q$, $q$Liste de sorts étendue, sorts de niveau 2 liés au type de génie.$q$, $q$sort_domaine$q$, null::jsonb),
      (77, 3, $q$Liste de sorts étendue (Niveau de sort 2)$q$, $q$Liste de sorts étendue, sorts de niveau 2 liés au type de génie.$q$, $q$sort_domaine$q$, null::jsonb),
      (78, 3, $q$Liste de sorts étendue (Niveau de sort 2)$q$, $q$Liste de sorts étendue, sorts de niveau 2 liés au type de génie.$q$, $q$sort_domaine$q$, null::jsonb),
      (79, 3, $q$Liste de sorts étendue (Niveau de sort 2)$q$, $q$Liste de sorts étendue, sorts de niveau 2 liés au type de génie.$q$, $q$sort_domaine$q$, null::jsonb),
      (76, 5, $q$Liste de sorts étendue (Niveau de sort 3)$q$, $q$Liste de sorts étendue, sorts de niveau 3 liés au type de génie.$q$, $q$sort_domaine$q$, null::jsonb),
      (77, 5, $q$Liste de sorts étendue (Niveau de sort 3)$q$, $q$Liste de sorts étendue, sorts de niveau 3 liés au type de génie.$q$, $q$sort_domaine$q$, null::jsonb),
      (78, 5, $q$Liste de sorts étendue (Niveau de sort 3)$q$, $q$Liste de sorts étendue, sorts de niveau 3 liés au type de génie.$q$, $q$sort_domaine$q$, null::jsonb),
      (79, 5, $q$Liste de sorts étendue (Niveau de sort 3)$q$, $q$Liste de sorts étendue, sorts de niveau 3 liés au type de génie.$q$, $q$sort_domaine$q$, null::jsonb),
      (76, 7, $q$Liste de sorts étendue (Niveau de sort 4)$q$, $q$Liste de sorts étendue, sorts de niveau 4 liés au type de génie.$q$, $q$sort_domaine$q$, null::jsonb),
      (77, 7, $q$Liste de sorts étendue (Niveau de sort 4)$q$, $q$Liste de sorts étendue, sorts de niveau 4 liés au type de génie.$q$, $q$sort_domaine$q$, null::jsonb),
      (78, 7, $q$Liste de sorts étendue (Niveau de sort 4)$q$, $q$Liste de sorts étendue, sorts de niveau 4 liés au type de génie.$q$, $q$sort_domaine$q$, null::jsonb),
      (79, 7, $q$Liste de sorts étendue (Niveau de sort 4)$q$, $q$Liste de sorts étendue, sorts de niveau 4 liés au type de génie.$q$, $q$sort_domaine$q$, null::jsonb),
      (76, 9, $q$Liste de sorts étendue (Niveau de sort 5)$q$, $q$Liste de sorts étendue, sorts de niveau 5 liés au type de génie.$q$, $q$sort_domaine$q$, null::jsonb),
      (77, 9, $q$Liste de sorts étendue (Niveau de sort 5)$q$, $q$Liste de sorts étendue, sorts de niveau 5 liés au type de génie.$q$, $q$sort_domaine$q$, null::jsonb),
      (78, 9, $q$Liste de sorts étendue (Niveau de sort 5)$q$, $q$Liste de sorts étendue, sorts de niveau 5 liés au type de génie.$q$, $q$sort_domaine$q$, null::jsonb),
      (79, 9, $q$Liste de sorts étendue (Niveau de sort 5)$q$, $q$Liste de sorts étendue, sorts de niveau 5 liés au type de génie.$q$, $q$sort_domaine$q$, null::jsonb),
      (76, 17, $q$Liste de sorts étendue (Niveau de sort 9)$q$, $q$Sort supplémentaire de niveau 9 (Arcanum mystique) lié au type de génie, obtenu au niveau 17.$q$, $q$sort_domaine$q$, null::jsonb),
      (77, 17, $q$Liste de sorts étendue (Niveau de sort 9)$q$, $q$Sort supplémentaire de niveau 9 (Arcanum mystique) lié au type de génie, obtenu au niveau 17.$q$, $q$sort_domaine$q$, null::jsonb),
      (78, 17, $q$Liste de sorts étendue (Niveau de sort 9)$q$, $q$Sort supplémentaire de niveau 9 (Arcanum mystique) lié au type de génie, obtenu au niveau 17.$q$, $q$sort_domaine$q$, null::jsonb),
      (79, 17, $q$Liste de sorts étendue (Niveau de sort 9)$q$, $q$Sort supplémentaire de niveau 9 (Arcanum mystique) lié au type de génie, obtenu au niveau 17.$q$, $q$sort_domaine$q$, null::jsonb),
      (76, 1, $q$Catalyseur de Génie$q$, $q$Vous recevez une gourde magique liée à un plan élémentaire ; en buvant son contenu par une action bonus, vous gagnez un effet lié à votre type de génie (dégâts, soins ou repoussement selon le type).$q$, null, '{"amount": 1, "rest_type": "repos_long"}'::jsonb),
      (77, 1, $q$Catalyseur de Génie$q$, $q$Vous recevez une gourde magique liée à un plan élémentaire ; en buvant son contenu par une action bonus, vous gagnez un effet lié à votre type de génie (dégâts, soins ou repoussement selon le type).$q$, null, '{"amount": 1, "rest_type": "repos_long"}'::jsonb),
      (78, 1, $q$Catalyseur de Génie$q$, $q$Vous recevez une gourde magique liée à un plan élémentaire ; en buvant son contenu par une action bonus, vous gagnez un effet lié à votre type de génie (dégâts, soins ou repoussement selon le type).$q$, null, '{"amount": 1, "rest_type": "repos_long"}'::jsonb),
      (79, 1, $q$Catalyseur de Génie$q$, $q$Vous recevez une gourde magique liée à un plan élémentaire ; en buvant son contenu par une action bonus, vous gagnez un effet lié à votre type de génie (dégâts, soins ou repoussement selon le type).$q$, null, '{"amount": 1, "rest_type": "repos_long"}'::jsonb),
      (76, 6, $q$Présent élémentaire$q$, $q$Vous gagnez un trait passif lié à votre type de génie (par exemple résistance élémentaire ou vitesse de vol/nage) tant que votre gourde a une charge.$q$, null, null::jsonb),
      (77, 6, $q$Présent élémentaire$q$, $q$Vous gagnez un trait passif lié à votre type de génie (par exemple résistance élémentaire ou vitesse de vol/nage) tant que votre gourde a une charge.$q$, null, null::jsonb),
      (78, 6, $q$Présent élémentaire$q$, $q$Vous gagnez un trait passif lié à votre type de génie (par exemple résistance élémentaire ou vitesse de vol/nage) tant que votre gourde a une charge.$q$, null, null::jsonb),
      (79, 6, $q$Présent élémentaire$q$, $q$Vous gagnez un trait passif lié à votre type de génie (par exemple résistance élémentaire ou vitesse de vol/nage) tant que votre gourde a une charge.$q$, null, null::jsonb),
      (76, 10, $q$Sanctuaire du génie$q$, $q$Vous pouvez, une fois par jour, créer un espace extraplanaire sûr accessible par votre gourde où vous et vos alliés pouvez vous reposer.$q$, null, null::jsonb),
      (77, 10, $q$Sanctuaire du génie$q$, $q$Vous pouvez, une fois par jour, créer un espace extraplanaire sûr accessible par votre gourde où vous et vos alliés pouvez vous reposer.$q$, null, null::jsonb),
      (78, 10, $q$Sanctuaire du génie$q$, $q$Vous pouvez, une fois par jour, créer un espace extraplanaire sûr accessible par votre gourde où vous et vos alliés pouvez vous reposer.$q$, null, null::jsonb),
      (79, 10, $q$Sanctuaire du génie$q$, $q$Vous pouvez, une fois par jour, créer un espace extraplanaire sûr accessible par votre gourde où vous et vos alliés pouvez vous reposer.$q$, null, null::jsonb),
      (76, 14, $q$Souhait limité$q$, $q$Une fois par période longue (30 jours), vous pouvez lancer le sort souhait limité sans dépenser d'emplacement de sort.$q$, null, null::jsonb),
      (77, 14, $q$Souhait limité$q$, $q$Une fois par période longue (30 jours), vous pouvez lancer le sort souhait limité sans dépenser d'emplacement de sort.$q$, null, null::jsonb),
      (78, 14, $q$Souhait limité$q$, $q$Une fois par période longue (30 jours), vous pouvez lancer le sort souhait limité sans dépenser d'emplacement de sort.$q$, null, null::jsonb),
      (79, 14, $q$Souhait limité$q$, $q$Une fois par période longue (30 jours), vous pouvez lancer le sort souhait limité sans dépenser d'emplacement de sort.$q$, null, null::jsonb),
      (7, 3, $q$Préceptes des anciens$q$, $q$Vous vous engagez à préserver la lumière, la beauté, l'amour et la vie face aux forces qui répandraient les ténèbres et le désespoir.$q$, null, null::jsonb),
      (7, 3, $q$Sorts de serment (Niveau de paladin 3)$q$, $q$Sorts de serment toujours préparés : Amitié avec les animaux, Ensorcellement.$q$, $q$sort_domaine$q$, null::jsonb),
      (7, 5, $q$Sorts de serment (Niveau de paladin 5)$q$, $q$Sorts de serment toujours préparés : Croissance végétale, Lueur d'espoir.$q$, $q$sort_domaine$q$, null::jsonb),
      (7, 9, $q$Sorts de serment (Niveau de paladin 9)$q$, $q$Sorts de serment toujours préparés : Dissipation de la magie, Reflets troublants.$q$, $q$sort_domaine$q$, null::jsonb),
      (7, 13, $q$Sorts de serment (Niveau de paladin 13)$q$, $q$Sorts de serment toujours préparés : Domination de bête, Liberté de mouvement.$q$, $q$sort_domaine$q$, null::jsonb),
      (7, 17, $q$Sorts de serment (Niveau de paladin 17)$q$, $q$Sorts de serment toujours préparés : Communion avec la nature, Mur de vent.$q$, $q$sort_domaine$q$, null::jsonb),
      (7, 3, $q$Conduit divin$q$, $q$Vous gagnez deux options de Conduit divin propres à ce serment : Éclat de la nature (une créature à 9 m subit un désavantage à son prochain jet de sauvegarde) et Rempart de la nature (vous devenez difficile à toucher et gagnez la résistance aux dégâts).$q$, null, null::jsonb),
      (7, 7, $q$Aura de garde$q$, $q$Vous et vos alliés à 3 m (9 m au niveau 18) êtes résistants aux dégâts infligés par les sorts.$q$, null, null::jsonb),
      (7, 15, $q$Sentinelle immortelle$q$, $q$Quand vous tombez à 0 point de vie sans être tué net, vous pouvez choisir de revenir à la place avec la moitié de vos points de vie maximum, une fois par repos long.$q$, null, '{"amount": 1, "rest_type": "repos_long"}'::jsonb),
      (7, 20, $q$Champion antique$q$, $q$Vous appelez la nature à votre aide : vos armes infligent des dégâts supplémentaires et vous gagnez une vitesse de vol temporaire pendant 1 minute, une fois par repos long.$q$, null, '{"amount": 1, "rest_type": "repos_long"}'::jsonb),
      (84, 3, $q$Préceptes de vengeance$q$, $q$Vous vous engagez à traquer et punir sans relâche ceux qui commettent de grands maux, quel qu'en soit le prix personnel.$q$, null, null::jsonb),
      (84, 3, $q$Sorts de serment (Niveau de paladin 3)$q$, $q$Sorts de serment toujours préparés : Marque du chasseur, Punition sanglante.$q$, $q$sort_domaine$q$, null::jsonb),
      (84, 5, $q$Sorts de serment (Niveau de paladin 5)$q$, $q$Sorts de serment toujours préparés : Immobilisation de personne, Repli sinistre.$q$, $q$sort_domaine$q$, null::jsonb),
      (84, 9, $q$Sorts de serment (Niveau de paladin 9)$q$, $q$Sorts de serment toujours préparés : Anti-détection, Repérage.$q$, $q$sort_domaine$q$, null::jsonb),
      (84, 13, $q$Sorts de serment (Niveau de paladin 13)$q$, $q$Sorts de serment toujours préparés : Bannissement, Œil arcanique.$q$, $q$sort_domaine$q$, null::jsonb),
      (84, 17, $q$Sorts de serment (Niveau de paladin 17)$q$, $q$Sorts de serment toujours préparés : Domination de personne, Scrutation.$q$, $q$sort_domaine$q$, null::jsonb),
      (84, 3, $q$Conduit divin$q$, $q$Vous gagnez deux options de Conduit divin propres à ce serment : Menace abjuratoire (une créature à 9 m a un désavantage à ses attaques contre des cibles autres que vous) et Vœu d'inimitié (avantage à vos jets d'attaque contre une créature choisie pendant 1 minute).$q$, null, null::jsonb),
      (84, 7, $q$Vengeur implacable$q$, $q$Quand une créature que vous avez touchée à votre dernier tour se déplace sans votre permission, vous pouvez utiliser votre réaction pour vous déplacer avec elle jusqu'à sa vitesse, sans provoquer d'attaque d'opportunité.$q$, null, null::jsonb),
      (84, 15, $q$Âme vengeresse$q$, $q$Votre vitesse augmente de 3 m tant que vous n'êtes pas incapable d'agir, et les créatures que vous prenez en chasse ne peuvent pas bénéficier de la Discrétion contre vous.$q$, null, null::jsonb),
      (84, 20, $q$Ange de la vengeance$q$, $q$Par une action, vous vous transformez, faisant pousser des ailes spectrales vous octroyant une vitesse de vol de 18 m et imposant la peur à vos ennemis à 9 m (JdS de Sagesse), une fois par repos long.$q$, null, '{"amount": 1, "rest_type": "repos_long"}'::jsonb),
      (89, 3, $q$Compagnon du rôdeur$q$, $q$Vous gagnez un compagnon animal (bête de FP 1/4 maximum) qui combat à vos côtés et agit à votre initiative.$q$, null, null::jsonb),
      (89, 7, $q$Entraînement exceptionnel$q$, $q$Votre compagnon animal peut, sans utiliser votre action, se déplacer et effectuer une action (Attaquer, Aider, Esquiver, Se cacher) de son propre chef.$q$, null, null::jsonb),
      (89, 11, $q$Fureur bestiale$q$, $q$Vous pouvez ordonner à votre compagnon d'attaquer deux fois lorsque vous utilisez votre action pour l'ordre Attaquer.$q$, null, null::jsonb),
      (89, 15, $q$Partage des sorts$q$, $q$Quand vous lancez un sort sur vous-même, vous pouvez aussi affecter votre compagnon animal s'il est à 9 m ou moins.$q$, null, null::jsonb),
      (91, 3, $q$Don draconique$q$, $q$Vous gagnez un don lié aux dragons (par exemple Interprète draconique ou Résilience draconique) qui renforce votre lien avec votre futur compagnon drake.$q$, null, null::jsonb),
      (91, 3, $q$Compagnon drake$q$, $q$Un œuf de dragon magique éclot à votre contact, vous liant à un drake compagnon qui grandit et combat à vos côtés, agissant à votre initiative.$q$, null, '{"amount": 1, "rest_type": "repos_long"}'::jsonb),
      (91, 7, $q$Lien du croc et d'écailles$q$, $q$Vous et votre drake bénéficiez d'un bonus mutuel aux jets d'attaque ou de dégâts lorsque vous combattez à proximité l'un de l'autre.$q$, null, null::jsonb),
      (91, 11, $q$Souffle de drake$q$, $q$Votre drake peut utiliser une action pour exhaler un souffle d'énergie élémentaire (type déterminé par son ascendance), infligeant des dégâts dans une zone avec jet de sauvegarde.$q$, null, '{"amount": 1, "rest_type": "repos_long"}'::jsonb),
      (91, 15, $q$Lien parfait$q$, $q$Votre drake atteint sa taille adulte, gagnant des points de vie, une attaque et un souffle plus puissants, ainsi qu'une plus grande autonomie au combat.$q$, null, null::jsonb),
      (96, 3, $q$Maîtrises supplémentaires$q$, $q$Vous gagnez la maîtrise des outils de déguisement et des outils d'empoisonneur.$q$, null, null::jsonb),
      (96, 3, $q$Assassinat$q$, $q$Vous avez l'avantage aux jets d'attaque contre toute créature qui n'a pas encore agi lors du combat, et toute attaque réussie contre une créature surprise est un coup critique.$q$, null, null::jsonb),
      (96, 9, $q$Expert en infiltration$q$, $q$Vous pouvez passer 1 heure à adopter une nouvelle identité (apparence, voix, manières) crédible sans magie.$q$, null, null::jsonb),
      (96, 13, $q$Imposteur$q$, $q$Vous pouvez imiter parfaitement l'écriture, la voix et le comportement d'une autre personne après une observation suffisante.$q$, null, null::jsonb),
      (96, 17, $q$Frappe meurtrière$q$, $q$Quand vous touchez une créature surprise, elle doit réussir un jet de sauvegarde de Constitution (DD égal à votre attaque sournoise + votre modificateur de Dextérité) ou subir le double des dégâts de l'attaque.$q$, null, null::jsonb),
      (97, 3, $q$Incantation$q$, $q$Vous apprenez à lancer des sorts de magicien (surtout école d'illusion et d'enchantement), en utilisant l'Intelligence comme caractéristique d'incantation, avec une progression lente (un tiers de votre niveau de roublard).$q$, null, null::jsonb),
      (97, 3, $q$Escamotage et main de mage$q$, $q$Vous apprenez le cantrip main de mage, et pouvez le rendre invisible et l'utiliser pour voler ou manipuler des objets à distance en action bonus, en lien avec votre Ruse.$q$, null, null::jsonb),
      (97, 9, $q$Embuscade magique$q$, $q$Quand vous êtes invisible au moment de lancer un sort sur une créature, celle-ci a un désavantage à son jet de sauvegarde contre ce sort.$q$, null, null::jsonb),
      (97, 13, $q$Escroc polyvalent$q$, $q$Vous pouvez remplacer l'effet de votre main de mage invisible par un tour de passe-passe de votre choix, comme distraire une créature à distance.$q$, null, null::jsonb),
      (97, 17, $q$Voleur de sort$q$, $q$Après avoir mis hors de combat une créature capable de lancer des sorts, vous pouvez lui dérober un sort qu'elle avait préparé et le lancer vous-même une fois avant la fin de votre prochain repos long.$q$, null, '{"amount": 1, "rest_type": "repos_long"}'::jsonb),
      (100, 3, $q$Maître des intrigues$q$, $q$Vous pouvez imiter l'accent et le dialecte d'une autre personne après l'avoir écoutée pendant 1 minute, et vous gagnez deux outils de jeu ou langues supplémentaires.$q$, null, null::jsonb),
      (100, 3, $q$Maître des tactiques$q$, $q$Par une action bonus, vous aidez à distance : une créature alliée qui peut vous entendre gagne l'avantage à son prochain jet d'attaque ou de compétence avant la fin de votre prochain tour.$q$, null, null::jsonb),
      (100, 9, $q$Manipulateur perspicace$q$, $q$Après avoir parlé avec une créature pendant au moins 1 minute, vous pouvez apprendre si elle a l'intention de mentir, ses attitudes et centres d'intérêt émotionnels.$q$, null, null::jsonb),
      (100, 13, $q$Redirection$q$, $q$Quand une créature vous touche par une attaque de mêlée, vous pouvez utiliser votre réaction pour désigner une autre créature à 1,50 m qui devient la cible de l'attaque à votre place.$q$, null, null::jsonb),
      (100, 17, $q$Âme de trompeur$q$, $q$Vous pouvez utiliser votre action bonus d'Aide à distance sur deux créatures alliées à la fois, et Manipulateur perspicace vous permet aussi d'implanter une fausse impression durable.$q$, null, null::jsonb)
    ) as t(subclass_id, level, name, description, choice_type, uses_per_rest)
  loop
    if not exists (
      select 1 from public.class_features cf
      join public.translations n on n.entity_type = 'class_feature' and n.entity_id = cf.id::text and n.field_name = 'name' and n.locale = 'fr'
      where cf.subclass_id = rec.subclass_id and cf.level = rec.level and n.value = rec.name
    ) then
      insert into public.class_features (class_id, subclass_id, level, choice_type, uses_per_rest)
        values (null, rec.subclass_id, rec.level, rec.choice_type, rec.uses_per_rest)
        returning id into v_id;
      insert into public.translations (entity_type, entity_id, field_name, locale, value) values
        ('class_feature', v_id::text, 'name', 'fr', rec.name),
        ('class_feature', v_id::text, 'description', 'fr', rec.description);
    end if;
  end loop;
end $$;
